-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1072400
-- Name: Outrider Mako
addappid(1072400) -- Outrider Mako
addappid(1072401,0,"8244f520893a6ceee6f645c601e6a93e8d2c5035ed3d60d50d45feefdfa2fca5") -- Depot 1 (1072401_3125766484000474100.manifest)
setManifestid(1072401,"3125766484000474100")