-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1094600
-- Name: Kingdom of Night
addappid(1094600) -- Kingdom of Night
-- MAIN APP DEPOTS
addappid(1094601, 1, "18da74b260b5418fae1ef0bda9efa4f94e46ac6676e440789c724f4e73b66b23") -- Depot 1094601
setManifestid(1094601, "8417111482603640010", 570092960)