-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1149460
-- Name: ICARUS
addappid(1149460) -- ICARUS
addappid(1149461,0,"c71fc47ef9e1e718df06677c0d6cf06fc0f01145d8481e0db444a26eed261296") -- Depot 1 (1149461_3974862521105799072.manifest)
setManifestid(1149461,"3974862521105799072")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 2 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")