-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1167630
-- Name: Teardown
addappid(1167630) -- Teardown
addappid(2657100,0,"5df4828df3d5422b27c221a29b70af3f0a032c14f71c632237047fb4b2ab2644") -- Depot 1 (2657100_2436425693420771637.manifest)
setManifestid(2657100,"2436425693420771637")
addappid(2657080,0,"204a8120beb5167f417969cac2724a24b5a1b35019dc45f94cca8fc986512185") -- Depot 2 (2657080_1875220687609911643.manifest)
setManifestid(2657080,"1875220687609911643")
addappid(2657050,0,"74eef5a7cdbac71c450a5d63ef57f193af7d4f1fd9717a88ece34eb6d9be7c3c") -- Depot 3 (2657050_2033310289830169426.manifest)
setManifestid(2657050,"2033310289830169426")
addappid(2657060,0,"e0d5e7a570d792711265ff7532a2dc8bce4648837e8d86c94dcf77f531c09baf") -- Depot 4 (2657060_834761181041569539.manifest)
setManifestid(2657060,"834761181041569539")
addappid(1167634,0,"4e402173b44873473aa98965b7075111059716ebc005137bc93e3e645fe13027") -- Depot 5 (1167634_3968778525799277081.manifest)
setManifestid(1167634,"3968778525799277081")