-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1182620
-- Name: Impostor Factory
addappid(1182620) -- Impostor Factory
addappid(1763930,0,"5f41ae532d0a66f8a1e8b1c66f70f848e1fccc0b73eaf6674668b921518e6c66") -- Depot 1 (1763930_2450391879432627756.manifest)
setManifestid(1763930,"2450391879432627756")
addappid(228982,0,"fa2997f03c3576c41174f200596ab2246fd1e39c0911f9b869e92635ae5b0ff5") -- Depot 2 (228982_6413394087650432851.manifest)
setManifestid(228982,"6413394087650432851")
addappid(1763921,0,"4b78b2052dc8f2948579cb0d1f62bea54bbfa04a29d7050faaa5a939a23cc71d") -- Depot 3 (1763921_3608918877416564617.manifest)
setManifestid(1763921,"3608918877416564617")
addappid(1182624,0,"87bff7b03e34251bb4b1feeddbfca04b43892cc1034aa89e4326ba5d5e70a1c2") -- Depot 4 (1182624_4204789026474775648.manifest)
setManifestid(1182624,"4204789026474775648")
addappid(1182621,0,"7984248174b17eb85143514698ab15d70c876c9f20a57f8e57f5d9f9cbf74c2c") -- Depot 5 (1182621_6066795607300929789.manifest)
setManifestid(1182621,"6066795607300929789")
addappid(1182623,0,"1da79fd792868eea9952bb7cb360c60880ac8699473962313f518ddd8aa143a3") -- Depot 6 (1182623_6897702030462727367.manifest)
setManifestid(1182623,"6897702030462727367")
addappid(1182622,0,"b454e9e72b8b5509705e108663e00a95ec6ba599cdb07c1ae7e7aa0c530e8bc2") -- Depot 7 (1182622_802991323684212041.manifest)
setManifestid(1182622,"802991323684212041")
addappid(1773090,0,"689d35529fa7c9c14d8dd508aa21a3d9163dec97abe5fac88226a6a5e1a6f855") -- Depot 8 (1773090_2417750809630663094.manifest)
setManifestid(1773090,"2417750809630663094")