-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1203620
-- Name: Enshrouded
addappid(1203620) -- Enshrouded
addappid(1203621,0,"7f96699c353588876112960fa1128ff856383861b188907320369a798ecb07bb") -- Depot 1 (1203621_6618041922014637122.manifest)
setManifestid(1203621,"6618041922014637122")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(2815512,0,"1300e25a3d42f4575462d0c45d57106388d9a7edfabf92b6352c0e184d3950d0") -- Depot 3 (2815512_8341692237213806114.manifest)
setManifestid(2815512,"8341692237213806114")
addappid(2815513,0,"95d1aa60ff64ddf23447f97dace7a7b532104a9982ceffbe37c010f95077d966") -- Depot 4 (2815513_2747458637255882618.manifest)
setManifestid(2815513,"2747458637255882618")