-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1231880
-- Name: Haiku, the Robot
addappid(1231880) -- Haiku, the Robot
addappid(1231881,0,"901ba963ce62d5e82f4e565c2e15aa05de9ba0ffbff4b97f99ea41cfaa70a7c1") -- Depot 1 (1231881_7441482087859669416.manifest)
setManifestid(1231881,"7441482087859669416")
addappid(1231882,0,"b8b30912ffea1edc3be0941f251c8e9b1b87a8803c0f2faf4bde169524dc8392") -- Depot 2 (1231882_6432753082397162193.manifest)
setManifestid(1231882,"6432753082397162193")