-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1245620
-- Name: ELDEN RING
addappid(1245620) -- ELDEN RING
addappid(2855520,0,"476eca9191866d6743aa7ad82d4d7ce1fcd5e0f0613f2f4b6559635d68f8c0e3") -- Depot 1 (2855520_164164058551746673.manifest)
setManifestid(2855520,"164164058551746673")
addappid(1245623,0,"b27090a72caa5f3cf2e1f41a81c4bc1c422a6ac277e1cd3a6f1ea68200288d4b") -- Depot 2 (1245623_1668253902893969272.manifest)
setManifestid(1245623,"1668253902893969272")
addappid(1245624,0,"e194ce5e5f83c427743781c1708c4bce6683d5d65521059f6e4ca64a8f36f3cd") -- Depot 3 (1245624_6740933728493231026.manifest)
setManifestid(1245624,"6740933728493231026")
addappid(1896300,0,"946e5c4e2c91a3ed363efc688218994f7fa6e8fdd56aa8b5752456d3b28e0543") -- Depot 4 (1896300_1676464084021469100.manifest)
setManifestid(1896300,"1676464084021469100")
addappid(1896320,0,"de7086b709fdfc7d151bfce5d07509fd80a6c318a21e8fb1e820db5b1cda5860") -- Depot 5 (1896320_689917599357770984.manifest)
setManifestid(1896320,"689917599357770984")
addappid(2778580,0,"9f1556645ea8ef43529f920cf02a2682a6da5756b29e630ba376a0cde24e3908") -- Depot 6 (2778580_8226581821665546770.manifest)
setManifestid(2778580,"8226581821665546770")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 7 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(1245621,0,"5f560fca048a138487e1e634a1e60693a7ad3ae7318c31731d147f16e093f10b") -- Depot 8 (1245621_6005357081270866877.manifest)
setManifestid(1245621,"6005357081270866877")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 9 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")