-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1281040
-- Name: Baby Steps
addappid(1281040) -- Baby Steps
addappid(1281042,0,"053c7e21b7936b8331deb11bbc9ae5a3b3c6df28b450220009cd8bfc91a5173b") -- Depot 1 (1281042_4844721271178453782.manifest)
setManifestid(1281042,"4844721271178453782")