-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1281930
-- Name: tModLoader
addappid(1281930) -- tModLoader
addappid(1281931,0,"2F3D1DE6D30D21AEF8361E268A82C2B030971620D9AE0611CA452D04D3DB8481") -- Depot 1 (1281931_1779141483676093144.manifest)
setManifestid(1281931,"1779141483676093144")
addappid(1281932,0,"5385C2C3B4D8B9E7365F5679DDB90C26AF9660FB624768D2FBA141B46CF58EC8") -- Depot 2 (1281932_6901245447502135442.manifest)
setManifestid(1281932,"6901245447502135442")
addappid(1281933,0,"ACE4929293E347C514440FB664BA011219611629C187E7D79D5656EAADC70E82") -- Depot 3 (1281933_7516799259062769039.manifest)
setManifestid(1281933,"7516799259062769039")
addappid(1281934,0,"C1D827072FB6BA28CD0EB5DE52B3F9AE84506EDACBDCB8C0E006C28EE27338FE") -- Depot 4 (1281934_4054322322552939928.manifest)
setManifestid(1281934,"4054322322552939928")