-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1296400
-- Name: Architect Life: A House Design Simulator
addappid(1296400) -- Architect Life: A House Design Simulator
addappid(229000,0,"3aae9271fb93da5395ffbfe338d3647de5dcfab3fc6fb901ca2ec28849b3d6bf") -- Depot 1 (229000_4622705914179893434.manifest)
setManifestid(229000,"4622705914179893434")
addappid(1296401,0,"4e7f5f76e4b45de0a1446e15e192444674e32ac61f103d7772d63b2b88e984a2") -- Depot 2 (1296401_5242621041096419909.manifest)
setManifestid(1296401,"5242621041096419909")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 3 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 4 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")