-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1313140
-- Name: Cult of the Lamb
addappid(1313140) -- Cult of the Lamb
addappid(1313141,0,"e7826851aae21726cd847e809a97378d381ba16449186ce1cdb57c572d703460") -- Depot 1 (1313141_5099221238639206725.manifest)
setManifestid(1313141,"5099221238639206725")
addappid(1313142,0,"242e4da3afdadce6aa2329f9f1c8c71fe09c06f51a80c105a444734a12c9e3f2") -- Depot 2 (1313142_2362702533565536515.manifest)
setManifestid(1313142,"2362702533565536515")