-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1332010
-- Name: Stray
addappid(1332010) -- Stray
addappid(2086162,0,"3e67977909dc764d102e327c26e3170be1cd27cb3e0e27a62c4d20250f88579b") -- Depot 1 (2086162_7459251104222374393.manifest)
setManifestid(2086162,"7459251104222374393")
addappid(1332011,0,"e61bdb7aeaccc075f69345348178ac158f107c1433c9a28743797407dc335e4c") -- Depot 2 (1332011_1060673695878105362.manifest)
setManifestid(1332011,"1060673695878105362")
addappid(2086161,0,"fd1d42615e85864ec3fc7caf1f1b06a9ca54cabfb31bea32a6f1d08c24b78e45") -- Depot 3 (2086161_9046842279009875207.manifest)
setManifestid(2086161,"9046842279009875207")
addappid(1332012,0,"b0288825cade4cf4aceb6bf5a2e523e0c94028b45fe8095fea1f7e04e26f5728") -- Depot 4 (1332012_1039060348056700964.manifest)
setManifestid(1332012,"1039060348056700964")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 5 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 6 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")