-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1369630
-- Name: ENDER LILIES: Quietus of the Knights
addappid(1369630) -- ENDER LILIES: Quietus of the Knights
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 1 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(1369631,0,"37ffbdc102510093006d481ea5f5ee9d29a9b5f27824e96618acad7c222bce6c") -- Depot 2 (1369631_2386691140537429742.manifest)
setManifestid(1369631,"2386691140537429742")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(1369632,0,"70f3ae8930871c24f176aa4286689264f984fb94b18bbb30f2b5a46d1ec053b8") -- Depot 4 (1369632_8114088238340750719.manifest)
setManifestid(1369632,"8114088238340750719")