-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1466060
-- Name: Tainted Grail: The Fall of Avalon
addappid(1466060, 1, "f53acb7f143a62f46c302975a2d5cdb7d58fb41a5a7d9a0a03f722a39493e160") -- Tainted Grail: The Fall of Avalon
-- MAIN APP DEPOTS
addappid(1466062, 1, "b164844c9d1dcef4202a397a747eff0fc24b75b5553e21bebbd7e86042d94bca") -- Depot 1466062
setManifestid(1466062, "531689641931185835", 41196702961)
-- DLCS WITH DEDICATED DEPOTS
-- Tainted Grail The Fall of Avalon - Supporters Pack (AppID: 3687050)
addappid(3687050)
addappid(3687050, 1, "8a5843ffcee408b2a16680531955ed57dd20d577be56ebb42d7c99dd653a3b2e") -- Tainted Grail The Fall of Avalon - Supporters Pack - Depot 3687050
setManifestid(3687050, "3877787421677591921", 818012192)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(4132150) -- Tainted Grail The Fall of Avalon - Sanctuary of Sarras DLC
addappid(4183140) -- Tainted Grail The Fall of Avalon - Bonus Content 1
-- EXCLUDED DLCS:
-- UNRELEASED DLCS (COMMENTED OUT)
-- addappid(3681950) -- DLC 3681950 (unreleased)