-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1507120
-- Name: The Spirit of the Samurai
addappid(1507120) -- The Spirit of the Samurai
-- MAIN APP DEPOTS
addappid(1507121, 1, "02425c220df8a52475ce5a7368882a4cd1e42d4d9771a30300f50bc3f464e2dd") -- Depot 1507121
setManifestid(1507121, "6133698591664308197", 5219554936)