-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1534840
-- Name: Hyper Light Breaker
addappid(1534840) -- Hyper Light Breaker
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(1534841,0,"faf4cabdfd4a2697de90722f8b1f942bf0f46e34b1bc28021eebb2a0c642e612") -- Depot 2 (1534841_6716568211215307414.manifest)
setManifestid(1534841,"6716568211215307414")