-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1545450
-- Name: Incredibox
addappid(1545450) -- Incredibox
addappid(1545451,0,"59a399e17aace3e46fb1c7d7dead965a78c15b5b077b014e0b80247f51a08e5c") -- Depot 1 (1545451_1645156689185074820.manifest)
setManifestid(1545451,"1645156689185074820")
addappid(1545452,0,"7c052a610f702e815b778ce422340dc38c5f0079b5c127790261fd7ff385eb2e") -- Depot 2 (1545452_6537223933422433843.manifest)
setManifestid(1545452,"6537223933422433843")