-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1546990
-- Name: Grand Theft Auto: Vice City – The Definitive Edition
addappid(1546990) -- Grand Theft Auto: Vice City – The Definitive Edition
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 1 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(1899671,0,"b7921da5e50d00b2238d0fe870a354cb572bc5d397955fef02a439103f62827b") -- Depot 2 (1899671_3704256598511448914.manifest)
setManifestid(1899671,"3704256598511448914")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(1546991,0,"8ffae608bee3a6766651bc7b0b2122f7248955251de38eafb6161ea30434979d") -- Depot 4 (1546991_6147427494442580236.manifest)
setManifestid(1546991,"6147427494442580236")