-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1547000
-- Name: Grand Theft Auto: San Andreas – The Definitive Edition
addappid(1547000) -- Grand Theft Auto: San Andreas – The Definitive Edition
addappid(1547001,0,"625ab457b256e557dc28337fec8a01b39731624ee6008b92670ac977c2691806") -- Depot 1 (1547001_6814041191190748315.manifest)
setManifestid(1547001,"6814041191190748315")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 2 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(1899671,0,"b7921da5e50d00b2238d0fe870a354cb572bc5d397955fef02a439103f62827b") -- Depot 3 (1899671_3704256598511448914.manifest)
setManifestid(1899671,"3704256598511448914")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 4 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")