-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1551360
-- Name: Forza Horizon 5
addappid(1551360) -- Forza Horizon 5
addappid(1613280,0,"1cc274dec87bdc5651311f72c4c162f4067eafba2d8fb98cac6e3be307f5948a") -- Depot 1 (1613280_1076978755699820847.manifest)
setManifestid(1613280,"1076978755699820847")
addappid(1613281,0,"d371f628205489a48d2888a29f596b335963d189f3e822ec32978292e989483a") -- Depot 2 (1613281_8702078743692499086.manifest)
setManifestid(1613281,"8702078743692499086")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 3 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 4 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(1551361,0,"13b42353469d4bb26905e2c12e73d4cd63ad89c21f438b3cf5b4b9a9bb659227") -- Depot 5 (1551361_8170102023880354057.manifest)
setManifestid(1551361,"8170102023880354057")