-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1562700
-- Name: SANABI
addappid(1562700) -- SANABI
-- MAIN APP DEPOTS
addappid(1562701, 1, "6a61d46843f44ec57cd9d72896f19e6ae976649dc0462ea6d9874ef8be703144") -- Depot 1562701
setManifestid(1562701, "393890018283437011", 3948551240)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(3996620) -- SANABI A Haunted Day