-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1569580
-- Name: Blue Prince
addappid(1569580) -- Blue Prince
-- MAIN APP DEPOTS
addappid(1569581, 1, "31965c819c33220b429da9fb8d633a2620f3b2b9e5f7ad47380878b719d85861") -- Depot 1569581
setManifestid(1569581, "6289516525108126147", 5316133277)
addappid(1569582, 1, "cd0afbef3ec1283eefbab01fed34936a9d624cfdb0061bbed4662097d0d9d66e") -- Depot 1569582
setManifestid(1569582, "549023711031552282", 4730309731)
addappid(1569583, 1, "6dc8f52fe7e1127a4c9a0da6a7fee1874d73046b9b1678d92037c85e7feaef9a") -- Depot 1569583
setManifestid(1569583, "6222055545472646455", 3815327516)