-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1586800
-- Name: Lil Gator Game
-- Updated: February 26, 2026 at 10:19:20 PM UTC
-- Lil Gator Game
-- Created: February 26, 2026 at 17:18:56 EST
-- Website: https://manifest.morrenus.xyz/
-- Total Depots: 2
-- Total DLCs: 1

-- MAIN APPLICATION
addappid(1586800) -- Lil Gator Game
-- MAIN APP DEPOTS
addappid(1586801, 1, "227ab3e720c1ec72a87cbd830e798cf009052c2b03872d8fec0ed09e0fba893e") -- Depot 1586801
setManifestid(1586801, "6159786778601603605", 508347010)
-- DLCS WITH DEDICATED DEPOTS
-- Lil Gator Game In the Dark (AppID: 3205060)
addappid(3205060)
addappid(3205060, 1, "d7ba371352442b01727ecb6c978bc9d6c9124617f645979dd07012d63f52e590") -- Lil Gator Game In the Dark - Depot 3205060
setManifestid(3205060, "997540432387158856", 14)
