-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1601970
-- Name: Tunguska: The Visitation - Final Cut
addappid(1601970) -- Tunguska: The Visitation - Final Cut
-- MAIN APP DEPOTS
addappid(1601971, 1, "5e54b63ec13550b8bbe92b018835c1b5725fc730a71818801107cd26b4e8a79e") -- Tunguska: The Visitation Win64
setManifestid(1601971, "8504046398146637954", 4992144579)
-- SHARED DEPOTS (from other apps)
addappid(228988, 1, "1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- VC 2019 Redist (Shared from App 228980)
setManifestid(228988, "6645201662696499616", 29212173)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(1836780) -- Tunguska Ravenwood Stories
addappid(2181860) -- Tunguska Way of A Hunter
addappid(2194620) -- Tunguska Ghost of Valentin
addappid(2426340) -- Tunguska Dead Zone
addappid(2509350) -- Tunguska Shadow Master
addappid(2692830) -- Tunguska Slaughterhouse
addappid(3077300) -- Tunguska Sound of Music