-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1604180
-- Name: Laika
addappid(1604180) -- Laika
-- MAIN APP DEPOTS
addappid(1604181, 1, "ebd5a4d804bce7d3c31f451ebfc6e5f27ffc52c187e464542d830d19514bea9d") -- Depot 1604181
setManifestid(1604181, "7948168423583677411", 844040908)