-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1614440
-- Name: Bō: Path of the Teal Lotus
addappid(1614440) -- Bō: Path of the Teal Lotus
addappid(1614441,0,"da3db8e85ebe004aaddb6379888ddc7ebe35cb843b8bd1aed25c008839c26c62") -- Depot 1 (1614441_8345203248926085503.manifest)
setManifestid(1614441,"8345203248926085503")