-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1620730
-- Name: Hell is Us
addappid(1620730) -- Hell is Us
addappid(1620731,0,"b9fd543171e70e995805fd37a879ca35601536a3f52ce6d8f8c917169a88534a") -- Depot 1 (1620731_5419831228598765946.manifest)
setManifestid(1620731,"5419831228598765946")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(3494390,0,"bea2e7ba38a31645bb88f40c59e3bd9b3fd7bd536262fcfe5157f89c467b56b9") -- Depot 4 (3494390_8168865267056917171.manifest)
setManifestid(3494390,"8168865267056917171")