-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1623730
-- Name: Palworld
addappid(1623730) -- Palworld
addappid(1623731,0,"7a422988135296505205dd489945d4b17ed7414734dd627744adac84aade7b73") -- Depot 1 (1623731_7704907311656361483.manifest)
setManifestid(1623731,"7704907311656361483")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(2771111,0,"802dd0505be5518464fe77ed7afa2c28611463bf00ec5ef400643b323d09c4c7") -- Depot 4 (2771111_6472366291146846212.manifest)
setManifestid(2771111,"6472366291146846212")
addappid(2771112,0,"c385e52ae8ad3b8756ab3caa03e50b105c0157fb797bb5acbff1bbb8bb27692f") -- Depot 5 (2771112_4099416431916212746.manifest)
setManifestid(2771112,"4099416431916212746")