-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1627720
-- Name: Lies of P
addappid(1627720) -- Lies of P
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(1627722,0,"b2550c254da0b229ff5f5bb765b809d2fac5bd74a98ff3611b8cb8870e02aa6a") -- Depot 2 (1627722_6836272904728643256.manifest)
setManifestid(1627722,"6836272904728643256")
addappid(1938422,0,"ababb5e54025724a4a56f8f0f08d33282cd3ef1296cb746627419bf317d9baa4") -- Depot 3 (1938422_438812726579636010.manifest)
setManifestid(1938422,"438812726579636010")
addappid(1938421,0,"3a598dabbe2783774bd506a68f7da2189eabe7234c03bdfce88cefed14bab3d8") -- Depot 4 (1938421_431261146813820426.manifest)
setManifestid(1938421,"431261146813820426")
addappid(1627721,0,"d847ff3494ad5b72d69b7b38c52474fdb22d437421b569013dd1508d8879f7c1") -- Depot 5 (1627721_2864050144902464475.manifest)
setManifestid(1627721,"2864050144902464475")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 6 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")