-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1635450
-- Name: Longvinter
addappid(1635450) -- Longvinter
addappid(229007,0,"eba9fa9ff4f811929c119074450f49f739113bcae9317ded9bea262aa21ec58d") -- Depot 1 (229007_4477590687906973371.manifest)
setManifestid(229007,"4477590687906973371")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(1635451,0,"c2ee929e91b9cd2a8c5fbeacc241aa350dd3d69ef9b816e088ca7f13d8a1bb7c") -- Depot 3 (1635451_8439295811773953013.manifest)
setManifestid(1635451,"8439295811773953013")
addappid(1635452,0,"e8ba636ef56364d7b8ac0a117aaf34b9218b34c51597690c910afeb6f34f3f47") -- Depot 4 (1635452_8322165890528889865.manifest)
setManifestid(1635452,"8322165890528889865")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 5 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")