-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1645630
-- Name: FEROCIOUS
addappid(1645630) -- FEROCIOUS
-- MAIN APP DEPOTS
addappid(1645631, 1, "cd1a9d02b5f7edbe2bfc34b599ec8fa0b46624c0e8fff62c9fbb1c903bfdb2b4") -- Depot 1645631
setManifestid(1645631, "2165107212928608950", 56419343133)