-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1657740
-- Name: Mr. Sleepy Man
-- Updated: March 17, 2026 at 05:28:16 PM UTC
-- Mr. Sleepy Man
-- Created: March 16, 2026 at 14:11:48 EDT
-- Website: https://manifest.morrenus.xyz/
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(1657740) -- Mr. Sleepy Man
-- MAIN APP DEPOTS
addappid(1657741, 1, "8b094f0db92a6e672dc6044c7b05d281b49c2014e9c267f9c15b51b111fbf43e") -- Depot 1657741
setManifestid(1657741, "7557475835470881279", 2857610539)
