-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1658150
-- Name: Moonstone Island
addappid(1658150) -- Moonstone Island
addappid(1658152,0,"4df035403c83e43ffdd7162dd43b9a0238d8c76d3b4225c98981c268d1703671") -- Depot 1 (1658152_4743537624713702071.manifest)
setManifestid(1658152,"4743537624713702071")
addappid(2581331,0,"5c3be39d3cc670be841eee2fad2211313e06ccc6023f4300f574d9f7e9dc4b10") -- Depot 2 (2581331_2159491958622058371.manifest)
setManifestid(2581331,"2159491958622058371")
addappid(2581340,0,"4b9863518cd49b73ec6241ef7d465e9d1bb1d9f3d8505e3ed778a407ec5bbd23") -- Depot 3 (2581340_6781434090282115762.manifest)
setManifestid(2581340,"6781434090282115762")
addappid(1658151,0,"a0087e864bcd67b31d88085e60a8b344db7098cbe6d6730e9b6ebf40cb025e3f") -- Depot 4 (1658151_2178106826775562221.manifest)
setManifestid(1658151,"2178106826775562221")
addappid(2577920,0,"19d1545edc1525760b1ab0a4b3e8ddc86ecee76712b30fef6235cd3fbb7f8af5") -- Depot 5 (2577920_1660015781744199212.manifest)
setManifestid(2577920,"1660015781744199212")
addappid(1658153,0,"7193a0c74850c092dc1d90624c45c4e50216a78a699658d64d5fff26e3c8d8f7") -- Depot 6 (1658153_171350236351990646.manifest)
setManifestid(1658153,"171350236351990646")