-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1659040
-- Name: HITMAN World of Assassination
addappid(1659040) -- HITMAN World of Assassination
addappid(1659041,0,"891bd9670c03fa74065659fe448680b55b5279707dfe40493d5f00372e02b42f") -- Depot 1 (1659041_6711704740148543453.manifest)
setManifestid(1659041,"6711704740148543453")