-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1659420
-- Name: UNCHARTED™: Legacy of Thieves Collection
addappid(1659420) -- UNCHARTED™: Legacy of Thieves Collection
addappid(1659422,0,"513eb93ddc7de41caabd6dfc7f8b2f5da716cc75ca9df1df674e4e339fceada2") -- Depot 1 (1659422_9007195248264946670.manifest)
setManifestid(1659422,"9007195248264946670")
addappid(1659421,0,"54f1e37db693643220de1240ebc50a0c00d4bc3a53ffdd91cf3f52cc71c91382") -- Depot 2 (1659421_7819112604911333886.manifest)
setManifestid(1659421,"7819112604911333886")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 3 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(1659425,0,"6bc8b76c2fb8d3e01a2bb8698af8b91196dbcb08fe353fcf64b55649ae766043") -- Depot 4 (1659425_5288094124393013920.manifest)
setManifestid(1659425,"5288094124393013920")