-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1698960
-- Name: Project Kat - Paper Lily Prologue
addappid(1698960) -- Project Kat - Paper Lily Prologue
addappid(1698961,0,"4a514ccb3d03dec7f5ca2277758ea44411c9a3da3185f8747ad1ab4ac9d1bd10") -- Depot 1 (1698961_2251076504403868212.manifest)
setManifestid(1698961,"2251076504403868212")