-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1729740
-- Name: Luto
addappid(1729740) -- Luto
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(1729741,0,"ae083aff6754925333f345c885acd58509a103503fd7ce6de8abe8b03e9fe4d2") -- Depot 2 (1729741_2975965042191885637.manifest)
setManifestid(1729741,"2975965042191885637")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")