-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1744330
-- Name: No More Heroes 3
-- Updated: March 25, 2026 at 05:01:51 PM UTC
-- No More Heroes 3
-- Created: September 30, 2025 at 03:47:08 EDT
-- Website: https://manifest.morrenus.xyz/
-- Total Depots: 4
-- Total DLCs: 1
-- Shared Depots: 2

-- MAIN APPLICATION
addappid(1744330) -- No More Heroes 3
-- MAIN APP DEPOTS
addappid(1744331, 1, "35a5ff9a91ea79ea241820f3d5554be376a9c4b89f22b978a942503b118de9af") -- Depot 1744331
setManifestid(1744331, "869643955729738706", 24914479341)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
-- DLCS WITH DEDICATED DEPOTS
-- No More Heroes 3 - The Art of No More Heroes 3 (AppID: 2122940)
addappid(2122940)
addappid(2122940, 1, "ce09861c8c655507f29b5d8263d3edf1590a305e2b48e4d1d9ed9fec0bf5ec31") -- No More Heroes 3 - The Art of No More Heroes 3 - Depot 2122940
setManifestid(2122940, "2158388480751595157", 106881008)
