-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1752540
-- Name: Lost Twins 2
addappid(1752540) -- Lost Twins 2
addappid(1752543,0,"b51317d7ae6693bc392dce8680c7a76410a7cf4d6bfb098f2ca6357375124a9f") -- Depot 1 (1752543_7957628719681672178.manifest)
setManifestid(1752543,"7957628719681672178")
addappid(3937120,0,"6132b02d1d5eea3c33279cd4238883f7870a2daed2cd975fb79fcba9a68752a2") -- Depot 2 (3937120_714460463440854152.manifest)
setManifestid(3937120,"714460463440854152")
addappid(1752542,0,"692051b50f26385265b5a6b21290945e95f77df66efc9d6cf40a379cb1d690f2") -- Depot 3 (1752542_7837884630892643334.manifest)
setManifestid(1752542,"7837884630892643334")