-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1757300
-- Name: Jump Space
addappid(1757300) -- Jump Space
addappid(1757302,0,"477c69a9e90f67fcdc258a5d81db1350720e1320f906c219baf52338bef271cd") -- Depot 1 (1757302_2838027590668590412.manifest)
setManifestid(1757302,"2838027590668590412")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")