-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1763250
-- Name: SWORN
addappid(1763250) -- SWORN
addappid(1763251,0,"32467278867521bb7848990057535c82d0e863ccdfabefffa0cd87c75a6d6b56") -- Depot 1 (1763251_7766092887705091211.manifest)
setManifestid(1763251,"7766092887705091211")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")