-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1774580
-- Name: STAR WARS Jedi: Survivor™
addappid(1774580) -- STAR WARS Jedi: Survivor™
addappid(1774582,0,"b6efa1ef672dce88aa6a6a094211c19110ebe78cf04b8bb87f7ba76e7cf15243") -- Depot 1 (1774582_6113531931136169727.manifest)
setManifestid(1774582,"6113531931136169727")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 2 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(1774581,0,"94d6a0b0e4e36aadffcbc197792207f773276593c72faf9b02b4b4200135a36f") -- Depot 3 (1774581_6701111524392590510.manifest)
setManifestid(1774581,"6701111524392590510")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 4 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")