-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1782460
-- Name: Hell Clock
addappid(1782460) -- Hell Clock
addappid(1782461,0,"b87981e090ab2ad89c7a18d14898061157db6a1ed5fb03d5e9f0546d734399ce") -- Depot 1 (1782461_1448818972623981484.manifest)
setManifestid(1782461,"1448818972623981484")