-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1790600
-- Name: DRAGON BALL: Sparking! ZERO
addappid(1790600) -- DRAGON BALL: Sparking! ZERO
addappid(2957490,0,"1b1f85ab25eb92147de8a0c1531d9ed57f3e01cfd46c9bb37be377251c2d24cd") -- Depot 1 (2957490_9060747264604927849.manifest)
setManifestid(2957490,"9060747264604927849")
addappid(2957480,0,"a8bbd2bdc3022cc2edc229e300b7583436b29d0e469662a8a277cf066798aa9f") -- Depot 2 (2957480_8386927810532837243.manifest)
setManifestid(2957480,"8386927810532837243")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 3 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(1790601,0,"0721a07eb97ba7b4e59e31606ae9f0d67c66309cc467c5da1aa79a924c34e7d8") -- Depot 4 (1790601_4594551172414663128.manifest)
setManifestid(1790601,"4594551172414663128")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 5 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")