-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1796470
-- Name: Haste
addappid(1796470) -- Haste
addappid(3587101,0,"2c0b7404519eef3fad96505eee8ef9dfd335c1c26ede4ca40ffa3ab7d0f0617e") -- Depot 1 (3587101_5671927963192264899.manifest)
setManifestid(3587101,"5671927963192264899")
addappid(3587102,0,"3480d60cd7ed2b25daa568920bcea90ab3b655070f8d80eae64afd9a66abb8a0") -- Depot 2 (3587102_2925846499593192497.manifest)
setManifestid(3587102,"2925846499593192497")
addappid(1796471,0,"1be44ffc3d55a3bfef475a9ca61508d531a7ff622c0d1ae83629e6b393fa0932") -- Depot 3 (1796471_6737724112648281378.manifest)
setManifestid(1796471,"6737724112648281378")