-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1803140
-- Name: Deer & Boy
-- Updated: June 27, 2026 at 03:00:53 PM UTC
-- Deer & Boy
-- Created: June 23, 2026 at 10:06:41 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 2
-- Total DLCs: 1

-- MAIN APPLICATION
addappid(1803140) -- Deer & Boy
-- MAIN APP DEPOTS
addappid(1803141, 1, "7f1be7e70ae816785005a1d080b888fe50252b9360724c423b04989d290a4c4f") -- Depot 1803141
setManifestid(1803141, "5598883002638000003", 5326827121)
-- DLCS WITH DEDICATED DEPOTS
-- Deer  Boy - The Art of Deer  Boy (AppID: 4588480)
addappid(4588480)
addappid(4588480, 1, "111a29a40a59a9a4d7ccb6013ba5bfbf9fc4086f68e35a7be8458d80f0fec7c1") -- Deer  Boy - The Art of Deer  Boy - Depot 4588480
setManifestid(4588480, "6866155599362871734", 2466995539)
