-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1811340
-- Name: Spray Paint Simulator
addappid(1811340) -- Spray Paint Simulator
addappid(1811341,0,"7b55c2b537b574df16fc24077a09521709c1f8bc8763eeb8eb8583485ef4a2ac") -- Depot 1 (1811341_5250885859107814062.manifest)
setManifestid(1811341,"5250885859107814062")