-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1820000
-- Name: Homura Hime
addappid(1820000) -- Homura Hime
-- MAIN APP DEPOTS
addappid(1820001, 1, "d2cd36f5c31810a42e9f6042ad4218698a686e24251cb65c3a3547b4dece81df") -- Depot 1820001
setManifestid(1820001, "1986474193915562529", 37617665082)