-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1850570
-- Name: DEATH STRANDING DIRECTOR'S CUT
addappid(1850570) -- DEATH STRANDING DIRECTOR'S CUT
addappid(1850571,0,"f0c67b235585f625ae33882c4547f9ef4404e96c5ad0a1fb4dbf43da61e04e24") -- Depot 1 (1850571_5054031739229969224.manifest)
setManifestid(1850571,"5054031739229969224")
addappid(1946740,0,"e01735660cdb310784cc00ba796a0b48c48605b9b94cf3e4d473b3a5ae97af32") -- Depot 2 (1946740_8878465371266993543.manifest)
setManifestid(1946740,"8878465371266993543")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 3 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")