-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1866130
-- Name: Morbid Metal
-- Updated: April 8, 2026 at 06:43:18 PM UTC
-- Morbid Metal
-- Created: April 08, 2026 at 11:32:05 EDT
-- Website: https://manifest.morrenus.xyz/
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(1866130) -- Morbid Metal
-- MAIN APP DEPOTS
addappid(1866131, 1, "9a7af3314bcdbbdffc8786b07b14c52230f77ae27ddc1479f060fca1b6c96d7f") -- Depot 1866131
setManifestid(1866131, "5602419405164883090", 14136435605)
