-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1874880
-- Name: Arma Reforger
addappid(1874880) -- Arma Reforger
addappid(1874881,0,"f1bc308d3a58a8d144a76dc02d552819b433bda49c325060fcab53e8100cead3") -- Depot 1 (1874881_2280300354030658070.manifest)
setManifestid(1874881,"2280300354030658070")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(1874882,0,"c964efe3e6ee7295beeb474f46e6c78d1f2f62097dc3c793b1474cfab9f2f055") -- Depot 3 (1874882_1650233779375073015.manifest)
setManifestid(1874882,"1650233779375073015")