-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1878490
-- Name: Gales of Nayeli
addappid(1878490) -- Gales of Nayeli
addappid(1878494,0,"9663fd6df002fa97f1bbfc1c75e123021d54a132bd430e3dbf6084d8559ac975") -- Depot 1 (1878494_4236728599136812884.manifest)
setManifestid(1878494,"4236728599136812884")