-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1888930
-- Name: The Last of Us™ Part I
addappid(1888930) -- The Last of Us™ Part I
addappid(1888931,0,"19cd197b4bc7e62551196ec84d00da135a4dedeb5edca50804001bf9e90b6b70") -- Depot 1 (1888931_4376931508237195356.manifest)
setManifestid(1888931,"4376931508237195356")
addappid(1888932,0,"20a675f9d2a0efd0cf0f8985b2a1c67d5d64e1c2b5aee665d3692969b28b1be4") -- Depot 2 (1888932_7992746905878846452.manifest)
setManifestid(1888932,"7992746905878846452")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 3 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(1888933,0,"035887e659bc052ab1d1801d1665304be7da49992076cd123e25b9bd06a64134") -- Depot 4 (1888933_415512790401871364.manifest)
setManifestid(1888933,"415512790401871364")