-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1902690
-- Name: Fate/Samurai Remnant
addappid(1902690) -- Fate/Samurai Remnant
-- MAIN APP DEPOTS
addappid(1902696, 1, "2c161b45268703111406d401c4988a92b8b22736a9d11cc377ca3b3268f70917") -- Depot 1902696
setManifestid(1902696, "4548950199439298883", 24094256430)
-- SHARED DEPOTS (from other apps)
addappid(228988, 1, "1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- VC 2019 Redist (Shared from App 228980)
setManifestid(228988, "6645201662696499616", 29212173)
-- DLCS WITH DEDICATED DEPOTS
-- FateSamurai Remnant - Bonus Equipment Hallowed Relic Sword Mountings (AppID: 2407210)
addappid(2407210)
addappid(2407210, 1, "7ef987ddbc066ec90fc0ce6780ecfe9b3e572d75f23fbd4111188736220c3b9a") -- FateSamurai Remnant - Bonus Equipment Hallowed Relic Sword Mountings - Depot 2407210
setManifestid(2407210, "647100067656198888", 4100588)
-- FateSamurai Remnant Digital Artbook  Soundtrack (AppID: 2426930)
addappid(2426930)
addappid(2426930, 1, "806974bd1ef3c87685e036622b684475f53f159bca5c91e1130c48b84321ef42") -- FateSamurai Remnant Digital Artbook  Soundtrack - Depot 2426930
setManifestid(2426930, "2098950453280292557", 322338799)
-- FateSamurai Remnant - Phantasmal Dress Miyamoto Musashi (AppID: 2426931)
addappid(2426931)
addappid(2426931, 1, "30b65ae5700ef23c64e451ca5eef1569c408cde1e62c32a5fc69176acd1dcab6") -- FateSamurai Remnant - Phantasmal Dress Miyamoto Musashi - Depot 2426931
setManifestid(2426931, "7369580410311963650", 18470704)
-- FateSamurai Remnant - Phantasmal Dress Saber (AppID: 2473120)
addappid(2473120)
addappid(2473120, 1, "9f6ac4db531848ea7d51cd02597bb7b06c347b48d364c8e5ad22039314393d7a") -- FateSamurai Remnant - Phantasmal Dress Saber - Depot 2473120
setManifestid(2473120, "8409075833980402044", 25231528)
-- FateSamurai Remnant - Phantasmal Dress Miyamoto Iori (AppID: 2473121)
addappid(2473121)
addappid(2473121, 1, "fe7031829b6066c50276bd75f06ba9cbe3b97595a9767aff42585dcafe796945") -- FateSamurai Remnant - Phantasmal Dress Miyamoto Iori - Depot 2473121
setManifestid(2473121, "885585049724543573", 17115919)
-- FateSamurai Remnant - Additional Episode 1 Records Fragment Keian Command Championship (AppID: 2494230)
addappid(2494230)
addappid(2494230, 1, "d136683c9a9576398983a74ffcac9bafe750915d1376beb4a2653f63e1bf1c9c") -- FateSamurai Remnant - Additional Episode 1 Records Fragment Keian Command Championship - Depot 2494230
setManifestid(2494230, "8122817334744600211", 708156504)
-- FateSamurai Remnant - Additional Episode 2 Records Fragment Yagyu Sword Chronicles (AppID: 2494240)
addappid(2494240)
addappid(2494240, 1, "db064c19da0817e0898deb4cd5f4ddefc8ea01d695549eae9272582791f2b5e3") -- FateSamurai Remnant - Additional Episode 2 Records Fragment Yagyu Sword Chronicles - Depot 2494240
setManifestid(2494240, "6455346510925305790", 751993775)
-- FateSamurai Remnant - Additional Episode 3 Records Fragment Bailong and the Crimson Demon (AppID: 2494250)
addappid(2494250)
addappid(2494250, 1, "6fbac1b05b4e9bb70dd3df8668778c966c84faefd5edadb34170d3d5a63f5a52") -- FateSamurai Remnant - Additional Episode 3 Records Fragment Bailong and the Crimson Demon - Depot 2494250
setManifestid(2494250, "5502418925699870178", 1239356534)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(2494220) -- FateSamurai Remnant Season Pass
-- EMPTY DEPOTS (no content on any branch)
-- addappid(1902694) -- Depot 1902694 (empty depot)
-- addappid(1902695) -- Depot 1902695 (empty depot)