-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1903340
-- Name: Clair Obscur: Expedition 33
-- Updated: March 18, 2026 at 08:17:57 PM UTC
-- Clair Obscur: Expedition 33
-- Created: March 17, 2026 at 06:21:50 EDT
-- Website: https://manifest.morrenus.xyz/
-- Total Depots: 3
-- Total DLCs: 1
-- Shared Depots: 2

-- MAIN APPLICATION
addappid(1903340, 1, "302b1b9c8eb04ca24027876370a3072643790a12b835cabccaecb15b226075e8") -- Clair Obscur: Expedition 33
-- MAIN APP DEPOTS
addappid(1903341, 1, "8593f9c4cd595f833d5344e55cd6c6fdb73d9a4fa05dab033ba71622265e8c82") -- Depot 1903341
setManifestid(1903341, "6814586708324036237", 47010910595)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(3228520) -- Clair Obscur Expedition 33  Deluxe Edition Upgrade
