-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1903340
-- Name: Clair Obscur: Expedition 33
addappid(1903340) -- Clair Obscur: Expedition 33
addappid(3405510,0,"d05c5a4e1666b64375d849a60b8f3694548fd5f756513928e1458c033101b848") -- Depot 1 (3405510_2478102260985916962.manifest)
setManifestid(3405510,"2478102260985916962")
addappid(1903341,0,"8593f9c4cd595f833d5344e55cd6c6fdb73d9a4fa05dab033ba71622265e8c82") -- Depot 2 (1903341_5254624293993445364.manifest)
setManifestid(1903341,"5254624293993445364")
addappid(3405511,0,"8cb3c5d263faf7383c63bcb27fb60e3f0a4de6b3a8c8f1fac33c9d12f41848ee") -- Depot 3 (3405511_763786632002146609.manifest)
setManifestid(3405511,"763786632002146609")