-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1909950
-- Name: SUPER ROBOT WARS Y
addappid(1909950) -- SUPER ROBOT WARS Y
addappid(3483900,0,"109130b59df37285a9a1e75cdb50516fb303e6694d4ae1d72e1c41cc7ef31cec") -- Depot 1 (3483900_2408797858890454844.manifest)
setManifestid(3483900,"2408797858890454844")
addappid(1909951,0,"77fcc720c77a9d762fca608c74046980979badaf8ce497d8494b3c2da40d3ddb") -- Depot 2 (1909951_6045651923644363701.manifest)
setManifestid(1909951,"6045651923644363701")
addappid(3483840,0,"c7108fbc58e82ebc3b10935a5048e2da2860b20e89c11f063d9ffe3cd1f6f638") -- Depot 3 (3483840_1145738050661138623.manifest)
setManifestid(3483840,"1145738050661138623")
addappid(3483870,0,"9cbfb79f2b6e617b33b8011be6be19e88089ae8343b6b83b7087a59cb1507f7d") -- Depot 4 (3483870_9219054550646773475.manifest)
setManifestid(3483870,"9219054550646773475")
addappid(3483830,0,"e32b0227a39c74cf84056450d0d93a70f6c229494b783b3a81935018c7ba5f31") -- Depot 5 (3483830_9089033282010469365.manifest)
setManifestid(3483830,"9089033282010469365")
addappid(3390820,0,"d22f81e1d50c71064d093e98fd8d79be8fe2443c109def325c1589235ddee9f2") -- Depot 6 (3390820_7112124880795295060.manifest)
setManifestid(3390820,"7112124880795295060")
addappid(3483910,0,"4a871e042cdbc9309625b25d1178c4a4b761e122b26e96f50a31cb4c80031be3") -- Depot 7 (3483910_7610336536250456307.manifest)
setManifestid(3483910,"7610336536250456307")