-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1920960
-- Name: VPet-Simulator
addappid(1920960) -- VPet-Simulator
addappid(1920963,0,"b32f451d9a2b48559bb18319906ee0a08556499d2e82dde42187a38a325adf12") -- Depot 1 (1920963_4319848444330254705.manifest)
setManifestid(1920963,"4319848444330254705")
addappid(1920962,0,"b794b9f1512eea471fcc6e78eff98d2fff7bcdb475166ad200365ab56cb12cb4") -- Depot 2 (1920962_2025884683050475961.manifest)
setManifestid(1920962,"2025884683050475961")
addappid(2639250,0,"ea76ffc614979026368548287258e7c179eba210d6b7b9b1136fc47888eae322") -- Depot 3 (2639250_1267585035493503641.manifest)
setManifestid(2639250,"1267585035493503641")
addappid(2607351,0,"f0bc56fa0483749ee2b75d5fb7b0b17e3cce79382e7543ba3fecb2fb6883ec17") -- Depot 4 (2607351_7865182294745255121.manifest)
setManifestid(2607351,"7865182294745255121")
addappid(1920961,0,"f3c1dca72c3176fb5d7a9796466ca62b5c92ca622523560d9a453b18eb257d12") -- Depot 5 (1920961_2598267325131691698.manifest)
setManifestid(1920961,"2598267325131691698")