-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1933000
-- Name: Luna Abyss
-- Updated: May 26, 2026 at 10:53:19 PM UTC
-- Luna Abyss
-- Created: May 23, 2026 at 02:27:21 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 3
-- Total DLCs: 0
-- Shared Depots: 2

-- MAIN APPLICATION
addappid(1933000, 1, "bfa64a6484a159f9f2fce18c45256ef35cb9699e77cb8409c61a3addcfb50716") -- Luna Abyss
-- MAIN APP DEPOTS
addappid(1933001, 1, "053e48598d2860c9d84005844ad2ba7158e805efa30803798f2d4d9c9b6bacc6") -- Depot 1933001
setManifestid(1933001, "3660680832711043914", 9624518857)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
