-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1941540
-- Name: Mafia: The Old Country
addappid(1941540) -- Mafia: The Old Country
addappid(1941541,0,"47c1ea957b9ecc8662a117fa6b19eea01ed30ef06478a364110fe40afa4e9f0e") -- Depot 1 (1941541_8117999326836103113.manifest)
setManifestid(1941541,"8117999326836103113")
addappid(229002,0,"f95e8545cfe871c330a483b25520ba7ed3750d21b9a51791ff0f0ed0dae33738") -- Depot 2 (229002_7260605429366465749.manifest)
setManifestid(229002,"7260605429366465749")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 3 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 4 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")