-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1953230
-- Name: Whisper Mountain Outbreak
addappid(1953230) -- Whisper Mountain Outbreak
addappid(1953231,0,"c52dabd72185ea327cf8203293b4ea730984114a8b183f1535e9b5a83410a086") -- Depot 1 (1953231_2484233797256727195.manifest)
setManifestid(1953231,"2484233797256727195")