-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1984270
-- Name: Digimon Story Time Stranger
addappid(1984270) -- Digimon Story Time Stranger
addappid(1984271,0,"b0aa8ddfef2996e3122b0bda1d02f7ceb28f608ac8c1d853e6793790aaab8860") -- Depot 1 (1984271_238061488930819289.manifest)
setManifestid(1984271,"238061488930819289")
addappid(229007,0,"eba9fa9ff4f811929c119074450f49f739113bcae9317ded9bea262aa21ec58d") -- Depot 2 (229007_4477590687906973371.manifest)
setManifestid(229007,"4477590687906973371")
addappid(3524350,0,"388eb5d2862631b327cd83e312bc69e3f14ecf6087a6a2ec0860f20df764139d") -- Depot 3 (3524350_3574787827120316187.manifest)
setManifestid(3524350,"3574787827120316187")
addappid(3524360,0,"9ac71aa654d8726aaf514236b138ac5c075854dd8f33abbfeb1b4316302c7f7b") -- Depot 4 (3524360_9075694746551360982.manifest)
setManifestid(3524360,"9075694746551360982")
addappid(3524330,0,"2358d5ff200cefb1eef6f77277f04089a01daaea4418cd48d530b4de3fe53f61") -- Depot 5 (3524330_9011286650463550421.manifest)
setManifestid(3524330,"9011286650463550421")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 6 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(3524340,0,"5441f08ccf7ebad6314bac9d071ba47a41e709f4000e121004752959138bb2dc") -- Depot 7 (3524340_9171927283280801773.manifest)
setManifestid(3524340,"9171927283280801773")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 8 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(3524240,0,"f06dc8a525a2fb5e03453da570b80915bd7c02daae714ac854c86283a2bc4e18") -- Depot 9 (3524240_6662609926555286405.manifest)
setManifestid(3524240,"6662609926555286405")
addappid(3524320,0,"0da086161abea2f6ce0863a530fefc41ac12993fb4308ff16301926398803a27") -- Depot 10 (3524320_2937343108483999987.manifest)
setManifestid(3524320,"2937343108483999987")