-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2014550
-- Name: Voidwrought
addappid(2014550) -- Voidwrought
addappid(2014551,0,"6d2ed618640bb062b370e4f15dc33c4cfddb5536b55bc4bf6b3d633885110588") -- Depot 1 (2014551_660015679237291422.manifest)
setManifestid(2014551,"660015679237291422")