-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2020030
-- Name: Tails Noir Preludes
-- Updated: May 24, 2026 at 01:20:34 PM UTC
-- Tails Noir Preludes
-- Created: October 02, 2025 at 09:22:33 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 3
-- Total DLCs: 0
-- Shared Depots: 2

-- MAIN APPLICATION
addappid(2020030) -- Tails Noir Preludes
-- MAIN APP DEPOTS
addappid(2020031, 1, "7205cb1188048b571a80e58ebcaefb45c970c3c219c65fbdc578fd52c8e240d1") -- Depot 2020031
setManifestid(2020031, "8655990926128133968", 1082024038)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
