-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2066520
-- Name: Ritual of Raven
addappid(2066520) -- Ritual of Raven
addappid(2066521,0,"c4bf32712b4399cb66f20d193f4e28362f4fefe34803a3333c337ee9ff9db2a3") -- Depot 1 (2066521_9086765672912626681.manifest)
setManifestid(2066521,"9086765672912626681")