-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2071280
-- Name: Ravenswatch
addappid(2071280) -- Ravenswatch
addappid(3113130,0,"d599bff2a5cf7c111a24f0fdceff1571f319bd064f49239e640c15c6356b8fd7") -- Depot 1 (3113130_8098826225145136318.manifest)
setManifestid(3113130,"8098826225145136318")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 2 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(2071281,0,"708c675853989cbd400455e166d30f9dec051473847f4577ef48f7c9331edb97") -- Depot 3 (2071281_5015178691456899887.manifest)
setManifestid(2071281,"5015178691456899887")