-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2085540
-- Name: Stick It to the Stickman
addappid(2085540) -- Stick It to the Stickman
addappid(2085541,0,"770f40e40d880628981e51726a0b14c9516704fc8154041d894b7fd0257b4050") -- Depot 1 (2085541_7868258480699000897.manifest)
setManifestid(2085541,"7868258480699000897")