-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 209100
-- Name: Resident Evil: Operation Raccoon City
addappid(209100) -- Resident Evil: Operation Raccoon City
addappid(210014,0,"ae16d95c7e1b1cb592a2256129cb9c3ab82d9c1c0e6b490cf6c1c5b9a741b9c0") -- Depot 1 (210014_6929097708000127585.manifest)
setManifestid(210014,"6929097708000127585")
addappid(210018,0,"38daf59157cd92a5da021ac4bdfead8f1e6221cdd7d8626589ff842a05e74b9a") -- Depot 2 (210018_8775897540560642606.manifest)
setManifestid(210018,"8775897540560642606")
addappid(210013,0,"11a1d2d64ee443e4ac618d9c0d424ee6d68bb830034f70c6b33e455d5c7b4d28") -- Depot 3 (210013_8905134226746428943.manifest)
setManifestid(210013,"8905134226746428943")
addappid(210017,0,"7cc5209e5fa52feca4047b105ad0a3d9762e8a104ef91f64469c6ab8cdd2233c") -- Depot 4 (210017_5881169774455065208.manifest)
setManifestid(210017,"5881169774455065208")
addappid(210016,0,"f26ba9e157c543c4b85a9fc7752522028eb99b1ab154f8c7cd573a10d420a8eb") -- Depot 5 (210016_8165546360368386361.manifest)
setManifestid(210016,"8165546360368386361")
addappid(210012,0,"b66f99c08b15b07edaab9c45a6bddcecbda138e31c6136c9d9543278ff7cab7a") -- Depot 6 (210012_5768689185529545089.manifest)
setManifestid(210012,"5768689185529545089")
addappid(210015,0,"5d91d23e61ddb257ac0fd2902243f3c45d2d52104361cb9492487ceb235ea014") -- Depot 7 (210015_3095055180986312337.manifest)
setManifestid(210015,"3095055180986312337")
addappid(209101,0,"0cb75133d130a7f7e5291ee1f5324f3eb890004c910cec3777467cbeb4d95840") -- Depot 8 (209101_419826520612959058.manifest)
setManifestid(209101,"419826520612959058")
addappid(210011,0,"1dbe894edc1b1c111f6f7156c42b1ff91a94ef953210399bbc345a9b76d287cf") -- Depot 9 (210011_8733898632540622121.manifest)
setManifestid(210011,"8733898632540622121")
addappid(210019,0,"be0a09b9ce70a9f38db057df6085b3d644d941a9c31595ca64bebd86ac0a1671") -- Depot 10 (210019_1626462342786322075.manifest)
setManifestid(210019,"1626462342786322075")