-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2101960
-- Name: Cronos: The New Dawn
addappid(2101960) -- Cronos: The New Dawn
addappid(229000,0,"3aae9271fb93da5395ffbfe338d3647de5dcfab3fc6fb901ca2ec28849b3d6bf") -- Depot 1 (229000_4622705914179893434.manifest)
setManifestid(229000,"4622705914179893434")
addappid(3748551,0,"a00d5fc8b73f7250ff62ca6a67441ad191eb2a2415db2d0db193285a7bb92780") -- Depot 2 (3748551_2053467992832422812.manifest)
setManifestid(3748551,"2053467992832422812")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 3 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(2101962,0,"d3f3ea72d940025825a5859f4747ec70d37c6b3df38f8ec038c1c70911d4e0ac") -- Depot 4 (2101962_2694394940284212263.manifest)
setManifestid(2101962,"2694394940284212263")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 5 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(2101961,0,"7f2c42a3171b51a0ea7463a8acbf143d1341f27c8e7babad3fa9eeef66f133eb") -- Depot 6 (2101961_3456900193582232476.manifest)
setManifestid(2101961,"3456900193582232476")