-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 21100
-- Name: F.E.A.R. 3
-- Updated: May 22, 2026 at 02:32:39 AM UTC
-- F.E.A.R. 3
-- Created: May 20, 2026 at 12:24:50 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 9
-- Total DLCs: 0 (2 excluded)

-- MAIN APPLICATION
addappid(21100, 1, "5598f4b26285091cd7b7071ecffcfb21dd0e0d224b563d8aa7177fee2a530d66") -- F.E.A.R. 3
-- MAIN APP DEPOTS
addappid(21102, 1, "7013a143f441beb09084cd5428103293baa61470594c4c622d70dbea23c6165c") -- F.E.A.R. 3 Code
setManifestid(21102, "7144802411701100270", 40051467)
addappid(21101, 1, "ba10622b48dd42a9e3941bce6da0417a57f676495edf533eabd2496edfdc2d40") -- F.E.A.R. 3 Resources
setManifestid(21101, "2891779319386338582", 4414661965)
addappid(21109, 1, "a35eea34e0af13b68d30fddc068ded42455e580131eb56bc4dfdb4124e5ace5f") -- F.E.A.R. 3 Low Violence Japan
setManifestid(21109, "7576372264763091427", 103219200)
addappid(21108, 1, "67a96846c0db3d26b323abb2ff918bdc12acdefc5a0924040c8ec8c922420430") -- F.E.A.R. 3 Low Violence Germany
setManifestid(21108, "2016332705521324808", 103219200)
addappid(21103, 1, "a69cce87cd47ecee7373c646a45e3ab23298e7cd3aa5e7bdc97d70475e7ba55e") -- F.E.A.R. 3 French
setManifestid(21103, "3204094799544998125", 89784320)
addappid(21104, 1, "c24fbd4c2d9338e1aac3a4f941f07fed9168e61853346e886c646fe7d6dffa93") -- F.E.A.R. 3 German
setManifestid(21104, "3587288302195043981", 107118592)
addappid(21105, 1, "3682793c0655c3933288f1c3f22caaac7db3c66995cb45c5ce2cab787d636e33") -- F.E.A.R. 3 Italian
setManifestid(21105, "7549567142992712760", 91062272)
addappid(21106, 1, "b268a1b39c880bf54108aba9aa7fa06c0684c0fe937ae097f9cd071510147657") -- F.E.A.R. 3 Spanish
setManifestid(21106, "2714512157704046773", 91488256)
addappid(21107, 1, "635ad7a5304754a0be85f9eab3a23b5697ac40b8a9afed43a6173c2910f48f9d") -- F.E.A.R. 3 Japanese
setManifestid(21107, "343303969601804912", 93847552)
-- EXCLUDED DLCS:
-- DLCS EXCLUDED (MISSING DEPOT KEYS)
-- F.E.A.R. 3 Hammer (AppID: 21150) - missing depot keys
-- addappid(21150)
-- F.E.A.R. 3 Shredder (AppID: 21160) - missing depot keys
-- addappid(21160)
