-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2124490
-- Name: SILENT HILL 2
addappid(2124490) -- SILENT HILL 2
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(2951541,0,"e089852efbe924984e137b7c02cf0f4d4481f091625dd22b61be2e5ffd02b994") -- Depot 2 (2951541_4181790107554818304.manifest)
setManifestid(2951541,"4181790107554818304")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(2124491,0,"1a14569bdc22983489a37bb81ed420c6230f43e84548d0ec0d4a3e9687861955") -- Depot 4 (2124491_4138456104249046245.manifest)
setManifestid(2124491,"4138456104249046245")