-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2129530
-- Name: REANIMAL
addappid(2129530) -- REANIMAL
-- MAIN APP DEPOTS
addappid(2129531, 1, "8c619e3fd74002747f22974390275782dc2b568bc92b52859f0c5688a4a663f7") -- Depot 2129531
setManifestid(2129531, "6819213190492602437", 15560181875)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
-- DLCS WITH DEDICATED DEPOTS
-- REANIMAL - Full Game (AppID: 4351720)
addappid(4351720)
addappid(4351720, 1, "6dba1be22c2161793226a2567e1ab5d6f153799494d7b26684d00e692ec041be") -- REANIMAL - Full Game - Depot 4351720
setManifestid(4351720, "8301697922046029259", 15485976327)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(3954470) -- REANIMAL - Foxhead and Muttonhead Masks
addappid(4112550) -- REANIMAL  Season Pass