-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2131650
-- Name: METAL GEAR SOLID 3: Snake Eater - Master Collection Version
-- Updated: March 19, 2026 at 11:41:26 PM UTC
-- METAL GEAR SOLID 3: Snake Eater - Master Collection Version
-- Created: March 18, 2026 at 02:27:29 EDT
-- Website: https://manifest.morrenus.xyz/
-- Total Depots: 10
-- Total DLCs: 3
-- Shared Depots: 2

-- MAIN APPLICATION
addappid(2131650, 1, "04d785f1b132636a833d300dbe499f0c6ac1c85d9c94ba4c293b4df2844919f6") -- METAL GEAR SOLID 3: Snake Eater - Master Collection Version
-- MAIN APP DEPOTS
addappid(2131652, 1, "65ab5efe73d2ad271b6038a0632621f95755aa433619ed4223eb115634d035ff") -- Depot 2131652
setManifestid(2131652, "7645578694842454403", 18838501178)
addappid(2131651, 1, "0073fe0583da7d2329aee1439801c51c48ee664444fa0f669155c1e51d331fe8") -- Depot 2131651
setManifestid(2131651, "6695587154341534306", 16856674192)
addappid(2131653, 1, "987453f27f184d3ffa2cdbdec5ad68315467386a0f05d348b076d3fdc5b072f4") -- Depot 2131653
setManifestid(2131653, "2112137862776922236", 16857644268)
addappid(2131654, 1, "5a546c87b8553c36c0b7c7ad9ea7aed11c225ff288a3077f0ce9236dababfa09") -- Depot 2131654
setManifestid(2131654, "1288863419166058256", 18839471250)
-- SHARED DEPOTS (from other apps)
addappid(228988, 1, "1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- VC 2019 Redist (Shared from App 228980)
setManifestid(228988, "6645201662696499616", 29212173)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
-- DLCS WITH DEDICATED DEPOTS
-- METAL GEAR SOLID 3 Snake Eater - Master Collection Version Japanese Language Pack (AppID: 2314280)
addappid(2314280)
addappid(2314280, 1, "1741d8bab672cba92e86f4f476a811e7e9e39685a9269a7040437c907492d334") -- METAL GEAR SOLID 3 Snake Eater - Master Collection Version Japanese Language Pack - Depot 2314280
setManifestid(2314280, "5445412728386120678", 5329278580)
-- METAL GEAR SOLID 3 Snake Eater - Master Collection Version International Language Pack (AppID: 2314281)
addappid(2314281)
addappid(2314281, 1, "5267831e9c74001101fdcd5e5987108b01c2c9fc3a3ad44c53f9bce2a3468e77") -- METAL GEAR SOLID 3 Snake Eater - Master Collection Version International Language Pack - Depot 2314281
setManifestid(2314281, "2259101554323948940", 7311105566)
-- METAL GEAR SOLID 3 Snake Eater - Master Collection Version High Resolution Texture Pack (AppID: 2314282)
addappid(2314282)
addappid(2314282, 1, "9584e2a3c4196fe4ad8bb6abefbce60a06710eb351f832abbec0be982d06f789") -- METAL GEAR SOLID 3 Snake Eater - Master Collection Version High Resolution Texture Pack - Depot 2314282
setManifestid(2314282, "4435371496659335891", 65721381983)
addappid(2314283, 1, "67624392f2d731364ecf93e7b110d97ef1abcb7440355225cb44625b8f6d74cb") -- METAL GEAR SOLID 3 Snake Eater - Master Collection Version High Resolution Texture Pack - Depot 2314283
setManifestid(2314283, "4327820012053922733", 86432)
