-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2133760
-- Name: Tiny Bookshop
addappid(2133760) -- Tiny Bookshop
addappid(2133763,0,"788e7476ac625a7a50f7add2445dc120f1524ee6dc56b8f14edec6a2f954474a") -- Depot 1 (2133763_7542272157823563357.manifest)
setManifestid(2133763,"7542272157823563357")
addappid(2133764,0,"1ebff4822d7fe419fe87324ea8a05d3dc5b985322407afcd0ad15c10f340eba7") -- Depot 2 (2133764_5128791478238300237.manifest)
setManifestid(2133764,"5128791478238300237")
addappid(2133762,0,"d52e06a500706a15e7821f6a7c3e30d1a2bce0ea65b784d6a387cdadef756a78") -- Depot 3 (2133762_7660041461646137790.manifest)
setManifestid(2133762,"7660041461646137790")