-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2138720
-- Name: REMATCH
addappid(2138720) -- REMATCH
addappid(2138721,0,"c1a2b9eea7346395b175b2d8458f566dcabe83b99822111d3446a5ce377bdc52") -- Depot 1 (2138721_6926894029455577193.manifest)
setManifestid(2138721,"6926894029455577193")