-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2172010
-- Name: Until Dawn™
addappid(2172010) -- Until Dawn™
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(2172011,0,"b8955754339fd50012ea607b7095692a80fdcb5b93df0e9dd837dfa5c6e3aabf") -- Depot 2 (2172011_8034387937407970920.manifest)
setManifestid(2172011,"8034387937407970920")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(2172012,0,"3dee1125193274da66e531b4c674f7787d08405c3f39309b0f72d9fe96d6ba74") -- Depot 4 (2172012_5223895161202821946.manifest)
setManifestid(2172012,"5223895161202821946")