-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2178070
-- Name: Towers of Aghasba
addappid(2178070) -- Towers of Aghasba
addappid(2178071,0,"a0cc1ebf88bc7bfcac11875c070fb0a2b0b439f439779695e2f7a3499ebcc7fd") -- Depot 1 (2178071_5602090986682064648.manifest)
setManifestid(2178071,"5602090986682064648")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")