-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2183900
-- Name: Warhammer 40,000: Space Marine 2
addappid(2183900) -- Warhammer 40,000: Space Marine 2
addappid(3202690,0,"00c47f82b08192958b11307abb87c755003eb8dfae75063373e379c296b26083") -- Depot 1 (3202690_5771349107512329188.manifest)
setManifestid(3202690,"5771349107512329188")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(2183901,0,"8df236a6a5084039477362b31157e7e0eb66554a744762d6782c544ab64d0c4e") -- Depot 3 (2183901_1531572827807667742.manifest)
setManifestid(2183901,"1531572827807667742")
addappid(3212022,0,"924f67387bb12cfc2988a7decd11c8ace7b5b38ae9d07397e246b36d01c1e5c5") -- Depot 4 (3212022_2274340000490854200.manifest)
setManifestid(3212022,"2274340000490854200")
addappid(3212040,0,"e3818ce0f203d78eed2647e6364bd19a702fd8d7a01230f77a038e0fd26b0ffb") -- Depot 5 (3212040_7457655780363166458.manifest)
setManifestid(3212040,"7457655780363166458")
addappid(3212023,0,"ad43f8052145e7fad816f6b2299a1ae217fc78bd8e1c769cb0ad3e0272d843d0") -- Depot 6 (3212023_4686517121168409350.manifest)
setManifestid(3212023,"4686517121168409350")
addappid(3212021,0,"01e7d7bd4abcb8946df7226afc08075b26c702659cf81018580d5f8e597b6c93") -- Depot 7 (3212021_4575728820807956562.manifest)
setManifestid(3212021,"4575728820807956562")