-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2183900
-- Name: Warhammer 40,000: Space Marine 2
addappid(2183900) -- Warhammer 40,000: Space Marine 2
addappid(3202690,0,"00c47f82b08192958b11307abb87c755003eb8dfae75063373e379c296b26083") -- Depot 1 (3202690_5771349107512329188.manifest)
setManifestid(3202690,"5771349107512329188")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(3212040,0,"e3818ce0f203d78eed2647e6364bd19a702fd8d7a01230f77a038e0fd26b0ffb") -- Depot 3 (3212040_7457655780363166458.manifest)
setManifestid(3212040,"7457655780363166458")
addappid(2183901,0,"8df236a6a5084039477362b31157e7e0eb66554a744762d6782c544ab64d0c4e") -- Depot 4 (2183901_6489772080429035133.manifest)
setManifestid(2183901,"6489772080429035133")