-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2195410
-- Name: Songs of Silence
addappid(2195410) -- Songs Of Silence
-- MAIN APP DEPOTS
addappid(2195411, 1, "9634043c605d62441a08ab388b7013a6cedb82be1cff7dbcdf8a8f77045a773a") -- Depot 2195411
setManifestid(2195411, "4951226601898122867", 7506495261)
-- DLCS WITH DEDICATED DEPOTS
-- Songs of Silence - Digital Goodies  Artbook (AppID: 2685660)
addappid(2685660)
addappid(2685660, 1, "cc0b59ac911cd40a3cd44ae65b636028fbd95e1ba6f5d5f28aecbc188aa53197") -- Songs of Silence - Digital Goodies  Artbook - Depot 2685660
setManifestid(2685660, "6711543990859668314", 1723998782)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(3400120) -- Songs of Silence - Lighteaters
addappid(3560460) -- Songs of Silence - Luminant Supporter Upgrade
addappid(3670070) -- Songs of Silence - Starborn Supporter Upgrade
addappid(3676040) -- Songs of Silence - Firstborn Supporter Upgrade
addappid(3774820) -- Songs of Silence - Year 1 Champions Frame
addappid(3776820) -- Songs of Silence - Year 1 Crafters Frame
addappid(4179260) -- Songs of Silence - Celestial Church Expansion