-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2200780
-- Name: My Dream Setup
addappid(2200780) -- My Dream Setup
addappid(2200781,0,"29406521ce5331ba5fdd43d43177449ef8464b67e6b6de257c894a5dbdb26cb1") -- Depot 1 (2200781_839722454156246755.manifest)
setManifestid(2200781,"839722454156246755")
addappid(2200782,0,"112155b443b5d2147602ac203014c4d4baeb01b241d22704420be8135a38f04a") -- Depot 2 (2200782_6310855528661276956.manifest)
setManifestid(2200782,"6310855528661276956")