-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2201320
-- Name: Date Everything!
addappid(2201320) -- Date Everything!
addappid(2201321,0,"173bd7627cf18657ea58531a712c028386d6385bfe84eb20b756333989d603d3") -- Depot 1 (2201321_1491398690208743097.manifest)
setManifestid(2201321,"1491398690208743097")