-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 221100
-- Name: DayZ
addappid(221100) -- DayZ
addappid(229004,0,"56ebe05d052f59ad2e9b101102de603dca17402a9bb2ef0015962c6b3275a2d0") -- Depot 1 (229004_5220958916987797232.manifest)
setManifestid(229004,"5220958916987797232")
addappid(1151700,0,"ed6fa275132bd015ad355b4058b0e4af4a79d000c2f912d1e28a19185ef3c1eb") -- Depot 2 (1151700_3323236725842480808.manifest)
setManifestid(1151700,"3323236725842480808")
addappid(228983,0,"77c8e812cd79e67e2d376721253ebb07e06b3646f05671c6c9517b27be14734b") -- Depot 3 (228983_8124929965194586177.manifest)
setManifestid(228983,"8124929965194586177")
addappid(221101,0,"9d9c5d3d77309bbe701a3f018cea877d22d07160b4ea2b65bdf261d0dc399c15") -- Depot 4 (221101_4317457313883759714.manifest)
setManifestid(221101,"4317457313883759714")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 5 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(228985,0,"21a2f639584d9bd462c5c4b3e10f881cba8a17ae674c830c4f083551cd356e9c") -- Depot 6 (228985_3966345552745568756.manifest)
setManifestid(228985,"3966345552745568756")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 7 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(221102,0,"fe6ef04ad5778ee58766d4c8b7057fa84feb52c2cc0155d808fb40ca1bd42789") -- Depot 8 (221102_6257360505448895155.manifest)
setManifestid(221102,"6257360505448895155")