-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 222480
-- Name: Resident Evil Revelations
addappid(222480) -- Resident Evil Revelations
addappid(229628,0,"deda58ec7e09d693118e91f904d7e25e08198a746dfe30f5a988ade2caf96dbb") -- Depot 1 (229628_1091544035272724112.manifest)
setManifestid(229628,"1091544035272724112")
addappid(229627,0,"05fe47e8229993a4957c546b6b11f34f46e75c4344ec653a896e52fcfb8d4343") -- Depot 2 (229627_6146425481277420255.manifest)
setManifestid(229627,"6146425481277420255")
addappid(229621,0,"cd908e40d47ae228e942070e0e6e9dd87d874f16434488b0b6d70091915ec999") -- Depot 3 (229621_1729720183785589076.manifest)
setManifestid(229621,"1729720183785589076")
addappid(229626,0,"1badd29cc032ee6227834ed10f78d0f4e785be725ae708391b1d6083e9d0fd67") -- Depot 4 (229626_1462684019205755272.manifest)
setManifestid(229626,"1462684019205755272")
addappid(222481,0,"65e75d906613ce658af73b8db0772cf9f6fa3905427161dd1c0482572da72c0d") -- Depot 5 (222481_2624313053854726936.manifest)
setManifestid(222481,"2624313053854726936")
addappid(229630,0,"c338077d7ee7ef5a03646b62ae08290d05705e25da98b945e75cc86b5c3da7a3") -- Depot 6 (229630_8821996626474824228.manifest)
setManifestid(229630,"8821996626474824228")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 7 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(229622,0,"ae8ea828b9a2c97510d5968ce55a9dae3a04346865801ac4757d7cd7ff106d9d") -- Depot 8 (229622_5762540738354433494.manifest)
setManifestid(229622,"5762540738354433494")
addappid(229629,0,"c9a80ed80166abc5061fe93f2ca57b2a013075300639e2a7963909215b3cdc57") -- Depot 9 (229629_7610772433233583544.manifest)
setManifestid(229629,"7610772433233583544")