-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2226730
-- Name: OVIS LOOP
addappid(2226730) -- OVIS LOOP
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(2226731,0,"e024ff155fb9f3ce8e387c1c4d4fb860d5f5959d17c8d99d6edbd005e25816a4") -- Depot 2 (2226731_3016413762168638337.manifest)
setManifestid(2226731,"3016413762168638337")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")