-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2239710
-- Name: Into the Dead: Our Darkest Days
addappid(2239710) -- Into the Dead: Our Darkest Days
addappid(2239712,0,"713b1f42f286d0647a93eb4b1ce92343c3294fbb200f2f937fa695d914c2d66b") -- Depot 1 (2239712_3653879240879270969.manifest)
setManifestid(2239712,"3653879240879270969")
addappid(2239711,0,"b157624d7bd77e603f16902ecbb3c59596e83a552e4089ce119057efa9d2f0b4") -- Depot 2 (2239711_8563104309309599618.manifest)
setManifestid(2239711,"8563104309309599618")