-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2239710
-- Name: Into the Dead: Our Darkest Days
addappid(2239710) -- Into the Dead: Our Darkest Days
addappid(2239711,0,"b157624d7bd77e603f16902ecbb3c59596e83a552e4089ce119057efa9d2f0b4") -- Depot 1 (2239711_2816804106952118932.manifest)
setManifestid(2239711,"2816804106952118932")