-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2240620
-- Name: UNBEATABLE
addappid(2240620) -- UNBEATABLE
-- MAIN APP DEPOTS
addappid(2240621, 1, "80b19fbd6c9057548e637a2e743cb48d753af68fa08227be8200dc8e3cc33753") -- Depot 2240621
setManifestid(2240621, "8439936538591813180", 34525636029)
-- DLCS WITH DEDICATED DEPOTS
-- UNBEATABLE - Breakout Edition Upgrade (AppID: 3951650)
addappid(3951650)
addappid(3951650, 1, "706689526031d649f39c7ce4ed4c578bfffbc570afae867b5c7464e12b7259ed") -- UNBEATABLE - Breakout Edition Upgrade - Depot 3951650
setManifestid(3951650, "4379137370641358211", 33766292)