-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2246340
-- Name: Monster Hunter Wilds
addappid(2246340) -- Monster Hunter Wilds
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 2 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(2246341,0,"15f418b98b8ade3be07b095f07a9ffc62ab918cf659a2fd7465fcb41c462f0af") -- Depot 3 (2246341_4888870531036709961.manifest)
setManifestid(2246341,"4888870531036709961")
addappid(3308900,0,"86e9ff2249c193631e8e04855d9c6154071b06491dced87279c1c72b1662556d") -- Depot 4 (3308900_2294659812094538398.manifest)
setManifestid(3308900,"2294659812094538398")