-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2273430
-- Name: BlazBlue Entropy Effect
addappid(2273430) -- BlazBlue Entropy Effect
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(2273432,0,"61cf08549f627caaf2793f6324710aa2bc1e9ce5b15ddd5f91a07fe323c89cef") -- Depot 2 (2273432_8647357607935395000.manifest)
setManifestid(2273432,"8647357607935395000")
addappid(2771142,0,"f79ddf0111ff5d536aff589dfda6390b06a13d28f116f9eae97bc36fac3f8a6a") -- Depot 3 (2771142_7333669365228745470.manifest)
setManifestid(2771142,"7333669365228745470")
addappid(2771130,0,"9252ee34ddef99b9842cf9b953a265b23f119aac46977475999deac055a2aa24") -- Depot 4 (2771130_8440413603119081723.manifest)
setManifestid(2771130,"8440413603119081723")
addappid(2273431,0,"8208c2f3da1d2334a1bdfdce064948df43608a9dce229fd006defc11ec0bb5ff") -- Depot 5 (2273431_5585592230693079363.manifest)
setManifestid(2273431,"5585592230693079363")
addappid(2771141,0,"4ea322c9278e847cc773c832e891c5d181c97706fe6327de5dcb50376c1be9c1") -- Depot 6 (2771141_5359888352168889722.manifest)
setManifestid(2771141,"5359888352168889722")