-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2277560
-- Name: WUCHANG: Fallen Feathers
addappid(2277560) -- WUCHANG: Fallen Feathers
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(2277561,0,"6db3af8b5be3def24c758a005feb7fa0f65750716392328e2f14321340adb273") -- Depot 2 (2277561_1216061457784642911.manifest)
setManifestid(2277561,"1216061457784642911")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")