-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2286600
-- Name: HOTEL BARCELONA
addappid(2286600) -- HOTEL BARCELONA
addappid(2286601,0,"44bbec5f278faf65d38103f6f36845df491764a05fc5da38e1d7ff60a7cc8704") -- Depot 1 (2286601_6193046431843237419.manifest)
setManifestid(2286601,"6193046431843237419")