-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2288350
-- Name: RAIDOU Remastered: The Mystery of the Soulless Army
addappid(2288350) -- RAIDOU Remastered: The Mystery of the Soulless Army
addappid(2486845,0,"b5ec8393c1fa4a977d0dba88aff0281a930e0341190fa65158c6067f8836a309") -- Depot 1 (2486845_9187613266433653033.manifest)
setManifestid(2486845,"9187613266433653033")
addappid(2288351,0,"584b8f457ad0579c460b81cc7584871d2076e59040b8e355650051f39e5509f3") -- Depot 2 (2288351_8954425886569925147.manifest)
setManifestid(2288351,"8954425886569925147")