-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2289720
-- Name: Kaiju Princess 2
addappid(2289720) -- Kaiju Princess 2
addappid(3350771,0,"6a742ed9433fdae3a6672cad8164d006a18603cf0e55d63109d7704000df7ede") -- Depot 1 (3350771_7160583029318906925.manifest)
setManifestid(3350771,"7160583029318906925")
addappid(3350471,0,"aa455c139ed574eeb891aa6af5fc41b4e177da3a64738c09fa7371a200156726") -- Depot 2 (3350471_7801301057959222722.manifest)
setManifestid(3350471,"7801301057959222722")
addappid(2289721,0,"9fc3429c350b7acd178867e645e958b1fafa2cf615acb4bdae830eaac032bdd0") -- Depot 3 (2289721_7245443010215709834.manifest)
setManifestid(2289721,"7245443010215709834")