-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2313700
-- Name: Constance
addappid(2313700) -- Constance
-- MAIN APP DEPOTS
addappid(2313701, 1, "96431a8a22bd40bb4eaad78944c3edcc24fa407ee951d461050bc7d4f4ac4cde") -- Depot 2313701
setManifestid(2313701, "2118596564020769011", 1523042689)