-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2319790
-- Name: Captain Wayne - Vacation Desperation
addappid(2319790) -- Captain Wayne - Vacation Desperation
-- MAIN APP DEPOTS
addappid(2319791, 1, "3a1f69fd013ffc978c79810d64ff3cc67ea729388a870c63f55b2c63268c4488") -- Depot 2319791
setManifestid(2319791, "1283969765421118223", 629578572)