-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2322010
-- Name: God of War Ragnarök
addappid(2322010) -- God of War Ragnarök
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(2322011,0,"78758c85a2a8b04770fb4fe430ac7a215a959b72e496d94f6a0ec5ac38066f49") -- Depot 2 (2322011_3011634702942262327.manifest)
setManifestid(2322011,"3011634702942262327")
addappid(2974311,0,"fadc9bf7352e7ae30b2451f6605c9cc89ea27b23388f2788cd5223df14bac32f") -- Depot 3 (2974311_6676705054900401854.manifest)
setManifestid(2974311,"6676705054900401854")