-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2322010
-- Name: God of War Ragnarök
addappid(2322010) -- God of War Ragnarök
addappid(2974340,0,"b54ec4dbd1528067329c6ce102d3dc0501401e41b08a6cabc0c947d0c9541baf") -- Depot 1 (2974340_192176833100020722.manifest)
setManifestid(2974340,"192176833100020722")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(2322011,0,"78758c85a2a8b04770fb4fe430ac7a215a959b72e496d94f6a0ec5ac38066f49") -- Depot 3 (2322011_151255971557114067.manifest)
setManifestid(2322011,"151255971557114067")