-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2325920
-- Name: Forestrike
addappid(2325920) -- Forestrike
-- MAIN APP DEPOTS
addappid(2325921, 1, "58a47ef0da4d1c9cbee3849cfc8d552d835433c211a890943212b44b7e2b2ab5") -- Depot 2325921
setManifestid(2325921, "7597417926452995552", 2966503684)