-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2343880
-- Name: The Diary
addappid(2343880) -- The Diary
addappid(2343881,0,"b649fe78222dc93d505d94fa40b76ee5c07791d38a473748ea57d371ec717c44") -- Depot 1 (2343881_8880239236506339589.manifest)
setManifestid(2343881,"8880239236506339589")