-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 235460
-- Name: METAL GEAR RISING: REVENGEANCE
addappid(235460) -- METAL GEAR RISING: REVENGEANCE
addappid(235462,0,"9bd8396f037cbbbc99c00d4acbc1744b2f518b774e4793cbb251a11afdfdca99") -- Depot 1 (235462_3091722681535053275.manifest)
setManifestid(235462,"3091722681535053275")
addappid(235461,0,"528bc8a310c4fe4defee57487f61d183ced5856c81a68f4b9818b97e7c60b11f") -- Depot 2 (235461_6603353085526272974.manifest)
setManifestid(235461,"6603353085526272974")