-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2354000
-- Name: Slackers - Carts of Glory
addappid(2354000) -- Slackers - Carts of Glory
addappid(2354001,0,"58cb30bea27ac9a9ebada223076288b2fed6909a307190d3e00784768c5f8244") -- Depot 1 (2354001_5553243640639099388.manifest)
setManifestid(2354001,"5553243640639099388")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")