-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2373990
-- Name: Solo Leveling: ARISE OVERDRIVE
addappid(2373990) -- Solo Leveling: ARISE OVERDRIVE
-- MAIN APP DEPOTS
addappid(2373991, 1, "5a97586d39bdb2a503376a75e3cae7d1f7e2de1bcb9ced523a73b21ca79de413") -- Depot 2373991
setManifestid(2373991, "147933327784089744", 43870958466)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(3638570) -- Solo LevelingARISE OVERDRIVE - Deluxe Edition