-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2377280
-- Name: Eriksholm: The Stolen Dream
addappid(2377280) -- Eriksholm: The Stolen Dream
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(2377281,0,"58a58e579e7cd5eda9f52f2c969e712a18acb42d6abb0cbacca8916304b2ffc0") -- Depot 2 (2377281_2176156223061833676.manifest)
setManifestid(2377281,"2176156223061833676")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")