-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2379780
-- Name: Balatro
addappid(2379780) -- Balatro
addappid(2379781,0,"16261e41d3e864018778d4a1d81658521a67d9ffb8543ea7e3e21f0685721af1") -- Depot 1 (2379781_3512319404653808464.manifest)
setManifestid(2379781,"3512319404653808464")
addappid(2834461,0,"4f3bc0746cd896ec3e138561b98b1d1b0e8a1e0d771c8f013f5badb7cd39dc32") -- Depot 2 (2834461_6087158023115835459.manifest)
setManifestid(2834461,"6087158023115835459")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 3 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(2379782,0,"d0d563bdb51d625d0ed3a3234be0282f8d9a25d81dce599cdcace7b88c3b4719") -- Depot 4 (2379782_1898957422191678575.manifest)
setManifestid(2379782,"1898957422191678575")