-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2380050
-- Name: Star Trucker
addappid(2380050) -- Star Trucker
-- MAIN APP DEPOTS
addappid(2380051, 1, "a692f8ffe9b6df42b1c9344a8d1f0f92109fc67c1d094414b767b5e6a641d27a") -- Depot 2380051
setManifestid(2380051, "5593944289169561312", 5601438419)
-- DLCS WITH DEDICATED DEPOTS
-- Star Trucker - Amped Customization Pack (AppID: 2873570)
addappid(2873570)
addappid(2873570, 1, "0112e9dce211b80465433d8f75f2aaddb769530350f876f1fbc6be52efc5ab11") -- Star Trucker - Amped Customization Pack - Depot 2873570
setManifestid(2873570, "4353674739525365458", 6)
-- Star Trucker - Heavy Duty Pack (AppID: 3088950)
addappid(3088950)
addappid(3088950, 1, "360ccc21ba2392f48bb79f55743a3883e02b09f007ab33d464b425f8378a326e") -- Star Trucker - Heavy Duty Pack - Depot 3088950
setManifestid(3088950, "9140824127826252003", 6)
-- Star Trucker - Star Truck Owners Manual (AppID: 3933200)
addappid(3933200)
addappid(3933200, 1, "9d449a98594ddf34570f09eab17b67d5339f2371c53780614a891329312624e1") -- Star Trucker - Star Truck Owners Manual - Depot 3933200
setManifestid(3933200, "8824499844711689272", 9194911)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(3218640) -- Star Trucker - Hallows Eve Pack
addappid(3285520) -- Star Trucker - SteelSeries Promotional Pack