-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2383200
-- Name: PATAPON 1+2 REPLAY
addappid(2383200) -- PATAPON 1+2 REPLAY
addappid(2383201,0,"e6ab327b2ce7b1d4a38492ab781adbe69841ef9b0a99d0d939c6c9d65eed4950") -- Depot 1 (2383201_4584414798360174724.manifest)
setManifestid(2383201,"4584414798360174724")