-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2384580
-- Name: DYNASTY WARRIORS: ORIGINS
addappid(2384580) -- DYNASTY WARRIORS: ORIGINS
addappid(3319850,0,"95133ff39c5da8ae0536933d236bb7eab7c1df24a6fedc606bcf5d0867c1a016") -- Depot 1 (3319850_575849332506894225.manifest)
setManifestid(3319850,"575849332506894225")
addappid(3319840,0,"e3daad5e8a9c79487f8ea299232fe177f346a535339aced3dbb44b4123959142") -- Depot 2 (3319840_4766733277274996871.manifest)
setManifestid(3319840,"4766733277274996871")
addappid(2384581,0,"c9bfe8a78dc43f75438b3a8e602c7a322b0b53418f80be108058121a71371130") -- Depot 3 (2384581_7914776441828737685.manifest)
setManifestid(2384581,"7914776441828737685")
addappid(3319870,0,"69380b72ac8cb5b3f7914bbb0e828d1529ef6b2a20076ceb73945c656515e5c7") -- Depot 4 (3319870_2027069962015143615.manifest)
setManifestid(3319870,"2027069962015143615")
addappid(3319860,0,"eb5c039bb499de6dea3bb580083c831393d697ff12404bae8b7ffcc0d8fe9f28") -- Depot 5 (3319860_7820196852362389506.manifest)
setManifestid(3319860,"7820196852362389506")
addappid(3319890,0,"ee47966cbf4e985ece4730ea8e94a7766202486517e1dba9de172b6fe849760d") -- Depot 6 (3319890_1226171390310445224.manifest)
setManifestid(3319890,"1226171390310445224")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 7 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(3319940,0,"3a41ae63aea1d4d9ba069358a1159daa92ead59d2790df626c089512e6018c1f") -- Depot 8 (3319940_4542174949091178289.manifest)
setManifestid(3319940,"4542174949091178289")