-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2387430
-- Name: SKY THE SCRAPER
addappid(2387430) -- SKY THE SCRAPER
addappid(2387431,0,"e46f1fe8c53efcd97812cd67285c4b623d782673a4f0ee243734437418c703e8") -- Depot 1 (2387431_6383470990073155656.manifest)
setManifestid(2387431,"6383470990073155656")