-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2389120
-- Name: 战姬军团
addappid(2389120) -- 战姬军团
addappid(2389121,0,"e66b46c3ce6fbe07784d2b0ecf1b475b03fb0b58fe6b75ebc77602cbbf0894db") -- Depot 1 (2389121_252576813000665425.manifest)
setManifestid(2389121,"252576813000665425")