-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2396990
-- Name: Fate/hollow ataraxia REMASTERED
addappid(2396990) -- Fate/hollow ataraxia REMASTERED
addappid(2396991,0,"5100b046f94ce318bd23122f91c9d90b4a0e8c0e873bee7bde1cea354300cc52") -- Depot 1 (2396991_3661608204531561468.manifest)
setManifestid(2396991,"3661608204531561468")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")