-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2399830
-- Name: ARK: Survival Ascended
addappid(2399830) -- ARK: Survival Ascended
addappid(3059650,0,"84b1a413568c28ea0226bbd983fbf08741ead907cc7cd9cdd447056405850bd2") -- Depot 1 (3059650_8484240895594028313.manifest)
setManifestid(3059650,"8484240895594028313")
addappid(3349320,0,"e0cbc7f932b6b5ffa7e36b9fe8ccf5b2317d5073f520b8a357a7bb8e32d7a181") -- Depot 2 (3349320_8500374987678115960.manifest)
setManifestid(3349320,"8500374987678115960")
addappid(2849450,0,"06a4aa068a1a3940e0c7eff34508ad6474806f4b46520ef9ea12b4b7f77a3d0e") -- Depot 3 (2849450_6915182534741338736.manifest)
setManifestid(2849450,"6915182534741338736")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 4 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(3675020,0,"5028ee914f2c74aba43cc91d7f2f49fd5ad0ec96dcb76372ed26deec22b0e88c") -- Depot 5 (3675020_123027605500077636.manifest)
setManifestid(3675020,"123027605500077636")
addappid(3483400,0,"8f2706fe64f86426091cbb9a23dedbc3ec0c53a78877abb9b549edded5f436ea") -- Depot 6 (3483400_2512399748177501131.manifest)
setManifestid(3483400,"2512399748177501131")
addappid(2399831,0,"320e0bcc46f1e7d88e18488c73990878eedbc06c3284015e1d0af97abe143e23") -- Depot 7 (2399831_7782980494517730658.manifest)
setManifestid(2399831,"7782980494517730658")
addappid(2827030,0,"ca47571a30440cd0d827bee6a57a945cf56d25fd4dbc19435d608994b021302a") -- Depot 8 (2827030_5143505551879053052.manifest)
setManifestid(2827030,"5143505551879053052")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 9 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")