-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2399830
-- Name: ARK: Survival Ascended
addappid(2399830) -- ARK: Survival Ascended
addappid(2849450,0,"06a4aa068a1a3940e0c7eff34508ad6474806f4b46520ef9ea12b4b7f77a3d0e") -- Depot 1 (2849450_1624016385229805643.manifest)
setManifestid(2849450,"1624016385229805643")
addappid(2827030,0,"ca47571a30440cd0d827bee6a57a945cf56d25fd4dbc19435d608994b021302a") -- Depot 2 (2827030_1058467195873061797.manifest)
setManifestid(2827030,"1058467195873061797")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 3 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(3059650,0,"84b1a413568c28ea0226bbd983fbf08741ead907cc7cd9cdd447056405850bd2") -- Depot 4 (3059650_2861139125995862983.manifest)
setManifestid(3059650,"2861139125995862983")
addappid(3349320,0,"e0cbc7f932b6b5ffa7e36b9fe8ccf5b2317d5073f520b8a357a7bb8e32d7a181") -- Depot 5 (3349320_7137009401095872016.manifest)
setManifestid(3349320,"7137009401095872016")
addappid(3483400,0,"8f2706fe64f86426091cbb9a23dedbc3ec0c53a78877abb9b549edded5f436ea") -- Depot 6 (3483400_8042832511502621718.manifest)
setManifestid(3483400,"8042832511502621718")
addappid(2399831,0,"320e0bcc46f1e7d88e18488c73990878eedbc06c3284015e1d0af97abe143e23") -- Depot 7 (2399831_9030075863479071109.manifest)
setManifestid(2399831,"9030075863479071109")
addappid(3675020,0,"5028ee914f2c74aba43cc91d7f2f49fd5ad0ec96dcb76372ed26deec22b0e88c") -- Depot 8 (3675020_5487482431083855565.manifest)
setManifestid(3675020,"5487482431083855565")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 9 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")