-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2400510
-- Name: Dungeons & Degenerate Gamblers
addappid(2400510) -- Dungeons & Degenerate Gamblers
addappid(2400512,0,"492f6a3d8ac2649a1c06a2e0c3f57d43056f49ce83f432ab0a56349256f1b86d") -- Depot 1 (2400512_8003257899301765304.manifest)
setManifestid(2400512,"8003257899301765304")
addappid(2400513,0,"fad855e6d88be1c801695aef8326b8b1e27914f761f41a4a89d110df9a7524e3") -- Depot 2 (2400513_9211408250343994891.manifest)
setManifestid(2400513,"9211408250343994891")
addappid(2400511,0,"f08be77434663a38ec425845293b8bda95d36ff7a388d6750b7a7169681e2500") -- Depot 3 (2400511_3651503894282785756.manifest)
setManifestid(2400511,"3651503894282785756")