-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2407270
-- Name: AI LIMIT
addappid(2407270) -- AI LIMIT
addappid(2407271,0,"7fbec0c07311645df5048184f930dab908082e6a96be2f0814a3159eaa8de5a6") -- Depot 1 (2407271_6712268877519353141.manifest)
setManifestid(2407271,"6712268877519353141")