-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2419670
-- Name: Eclipsium
addappid(2419670) -- Eclipsium
addappid(2419671,0,"c41e1728cc55c498046c15e73e08dca0970c9dbb67d95bb5231e4f1e53166437") -- Depot 1 (2419671_7064562144397460882.manifest)
setManifestid(2419671,"7064562144397460882")