-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 242760
-- Name: The Forest
addappid(242760) -- The Forest
addappid(242761,0,"786dfb9db41be351c888b4a930d5295dfe6c8c4bbc4e442f0e1ced301c4d24df") -- Depot 1 (242761_5529756524060062456.manifest)
setManifestid(242761,"5529756524060062456")