-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2429050
-- Name: Fretless - The Wrath of Riffson
addappid(2429050) -- Fretless - The Wrath of Riffson
addappid(2429051,0,"4f1e7142a2497f0428cee5e8d6d4a924e045d14557f49467637fb94a5a0fbd96") -- Depot 1 (2429051_4631832360276106572.manifest)
setManifestid(2429051,"4631832360276106572")