-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2444750
-- Name: Shape of Dreams
addappid(2444750) -- Shape of Dreams
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 2 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(2444751,0,"ef362189306209d0c11c3b509c34fd001aed76b0fc0ea258001430f6793519a5") -- Depot 3 (2444751_7544377441490399661.manifest)
setManifestid(2444751,"7544377441490399661")