-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2446540
-- Name: SLEEP AWAKE
addappid(2446540) -- SLEEP AWAKE
-- MAIN APP DEPOTS
addappid(2446541, 1, "da3466e97426dd8d04399ff6f8d9c38cbf484ac99b368e9be7fb657229567b02") -- Depot 2446541
setManifestid(2446541, "535783086943941089", 49441358435)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)