-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2448020
-- Name: Yooka-Replaylee
addappid(2448020) -- Yooka-Replaylee
addappid(2448021,0,"0087364299b86dce13084a6e34fc1292ca9587691740ac9b8b93fe737b8af5b0") -- Depot 1 (2448021_8203004014523827167.manifest)
setManifestid(2448021,"8203004014523827167")