-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2456740
-- Name: inZOI
addappid(2456740) -- inZOI
addappid(3887681,0,"443b555d0c838bd99b995ed172ed1d49f028e6347a1f27e3d74e648cd5718bc2") -- Depot 1 (3887681_133730821882841897.manifest)
setManifestid(3887681,"133730821882841897")
addappid(3887680,0,"25ed1bd4d03ac4fd1a739171c82248fe6db511beea87dccfe33721091039e9c8") -- Depot 2 (3887680_8311539386067681848.manifest)
setManifestid(3887680,"8311539386067681848")
addappid(2456741,0,"e91cba2d1d471bdfb115bee76ac997858f84e6ab0a82af5f17d0054f8a3c9686") -- Depot 3 (2456741_9018784956877747845.manifest)
setManifestid(2456741,"9018784956877747845")
addappid(2456742,0,"7c9a756f88682f7ae0913792f29b1c2ad7c702cb41859ecb9965e8c8760aff0d") -- Depot 4 (2456742_5776505101187743596.manifest)
setManifestid(2456742,"5776505101187743596")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 5 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 6 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")