-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2464280
-- Name: Tormented Souls 2
addappid(2464280, 1, "b88f19c06483bf20aeee143ffdadb0e517e4d861ea8f11c7cd104a867c1578c4") -- Tormented Souls 2
-- MAIN APP DEPOTS
addappid(2464281, 1, "35ad79ec9649e9b4e9adf4595a0cf6a5f154af8dba7cd93afef6a346dea7002d") -- Depot 2464281
setManifestid(2464281, "5320910804439947340", 47775866630)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(3908350) -- Tormented Souls 2 - Digital Deluxe Edition Upgrade