-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2464530
-- Name: VOIN
-- Updated: April 9, 2026 at 11:19:20 PM UTC
-- VOIN
-- Created: October 23, 2025 at 13:11:14 EDT
-- Website: https://manifest.morrenus.xyz/
-- Total Depots: 3
-- Total DLCs: 0
-- Shared Depots: 2

-- MAIN APPLICATION
addappid(2464530) -- VOIN
-- MAIN APP DEPOTS
addappid(2464531, 1, "97e330a8fab2c3c5b986850ae289c9fb852bad4b6a15f04d0695d62cb23a218d") -- Depot 2464531
setManifestid(2464531, "3210997103592602820", 3248110301)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
