-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2472940
-- Name: Wanderer: The Fragments of Fate
addappid(2472940) -- Wanderer: The Fragments of Fate
-- MAIN APP DEPOTS
addappid(2472941, 1, "8368ef651d2001ae277c701dfce8f8d973c7d05655033ec8c9ce8e29148d82e6") -- Depot 2472941
setManifestid(2472941, "5086306755712006565", 40126568821)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)