-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 24740
-- Name: Burnout Paradise: The Ultimate Box
addappid(24740) -- Burnout Paradise: The Ultimate Box
addappid(24741,0,"bf9b197b173bddfda183a9b2d645aa30840ac2187661b1950a6a326a6e6c2347") -- Depot 1 (24741_1700837137338513047.manifest)
setManifestid(24741,"1700837137338513047")