-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2486820
-- Name: Sonic Racing: CrossWorlds
addappid(2486820) -- Sonic Racing: CrossWorlds
addappid(2486821,0,"08e2539b55bc79fefa9447d3479c57b481c4256c12ebd50529fc3722fcc3727f") -- Depot 1 (2486821_4568197498656447880.manifest)
setManifestid(2486821,"4568197498656447880")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")