-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2506530
-- Name: It Has My Face
addappid(2506530) -- It Has My Face
addappid(2506531,0,"80c4294f187f8851e0f632effc5b8621fd291ecc6d016f57bb6c749c2742862e") -- Depot 1 (2506531_2731898589165370915.manifest)
setManifestid(2506531,"2731898589165370915")