-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2512380
-- Name: CULT OF FLIES
-- Updated: April 12, 2026 at 10:00:37 AM UTC
-- CULT OF FLIES
-- Created: April 12, 2026 at 05:59:58 EDT
-- Website: https://manifest.morrenus.xyz/
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(2512380) -- CULT OF FLIES
-- MAIN APP DEPOTS
addappid(2512382, 1, "99566361fc7706e20760ed8dca1bfc6a6c0df7300b0e677b479ec9143ff950f6") -- Depot 2512382
setManifestid(2512382, "2277091194018123977", 803594594)
