-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 251570
-- Name: 7 Days to Die
addappid(251570) -- 7 Days to Die
addappid(251578,0,"4550672ef4a498246530208707b36b490dd3bb73c6b54ba6b832dd48db88f71a") -- Depot 1 (251578_8287144542041066476.manifest)
setManifestid(251578,"8287144542041066476")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(228983,0,"77c8e812cd79e67e2d376721253ebb07e06b3646f05671c6c9517b27be14734b") -- Depot 3 (228983_8124929965194586177.manifest)
setManifestid(228983,"8124929965194586177")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 4 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(251571,0,"2787b64cd24c9e42a114df4d2559813dc0f63405faa2f7e41cc77e6c3cc67bd0") -- Depot 5 (251571_8628486239191323866.manifest)
setManifestid(251571,"8628486239191323866")
addappid(251577,0,"53a3478a67db1f8ed8030e845ec1be174a60cea2448401ffd4dda0c4838cbb84") -- Depot 6 (251577_949611504741668687.manifest)
setManifestid(251577,"949611504741668687")
addappid(251576,0,"525d3fda8d2195cf5a8bd10c0c158513d9f870f99a036830287c1465c73c6979") -- Depot 7 (251576_133976342143448674.manifest)
setManifestid(251576,"133976342143448674")