-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 252490
-- Name: Rust
addappid(252490) -- Rust
addappid(252492,0,"96b750328197855f4311ba6ad6d86e9051866cc6b9a6c851de55cc41b8ad9a24") -- Depot 1 (252492_8149307904467569375.manifest)
setManifestid(252492,"8149307904467569375")
addappid(229002,0,"f95e8545cfe871c330a483b25520ba7ed3750d21b9a51791ff0f0ed0dae33738") -- Depot 2 (229002_7260605429366465749.manifest)
setManifestid(229002,"7260605429366465749")
addappid(252494,0,"5d5f72c0460cb7598666696c1b2f612f22efb43fb87cf4322e596bfec8a231ec") -- Depot 3 (252494_3379208401631610803.manifest)
setManifestid(252494,"3379208401631610803")
addappid(252495,0,"728fcdc1c6af4454f3c86e5bc62a75875af5ba790cc8a2623620e216086e034d") -- Depot 4 (252495_1382918731180776708.manifest)
setManifestid(252495,"1382918731180776708")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 5 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")