-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2529750
-- Name: Raining City: Millions Recollections
addappid(2529750) -- Raining City: Millions Recollections
addappid(2529751,0,"a36a34bfcb62e0d6e68a34d55ec7cd582d54a2a9063a62f32d0d8ffb701738ea") -- Depot 1 (2529751_8397419066769161359.manifest)
setManifestid(2529751,"8397419066769161359")