-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2531310
-- Name: The Last of Us™ Part II Remastered
addappid(2531310) -- The Last of Us™ Part II Remastered
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(2531313,0,"a88758211f172f53efb57ad5c819b9d5f34b0796b44bd876639a09029e6a8089") -- Depot 2 (2531313_5241159688705703611.manifest)
setManifestid(2531313,"5241159688705703611")
addappid(2531314,0,"3dc1a7d997476f1b4eb3a78f11af1be0d750a14719dc5d5eaeb940bcd44b74e5") -- Depot 3 (2531314_191855825481859544.manifest)
setManifestid(2531314,"191855825481859544")
addappid(2531311,0,"f7506952e736e71547c2d3c2c82959438e836c66d5b8b8f3208ccc082f60df23") -- Depot 4 (2531311_5151442398504601055.manifest)
setManifestid(2531311,"5151442398504601055")