-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2533600
-- Name: Bloodthief
addappid(2533600) -- Bloodthief
addappid(2533602,0,"606392b40fe9ebd0fa02f290d9dd3f162e84333f972524e0b930215e454bb369") -- Depot 1 (2533602_4205314110720416969.manifest)
setManifestid(2533602,"4205314110720416969")