-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2537590
-- Name: Microsoft Flight Simulator 2024
addappid(2537590) -- Microsoft Flight Simulator 2024
addappid(2537591,0,"a149759cc259406fd0f2255297e089d9deb63fb59c263b7f2d1b7fcd7aded1a4") -- Depot 1 (2537591_3625077327977271163.manifest)
setManifestid(2537591,"3625077327977271163")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")