-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2542120
-- Name: NINJA GAIDEN: Ragebound
addappid(2542120) -- NINJA GAIDEN: Ragebound
addappid(2542121,0,"ddd21357db67ee08b9fe146fe995760876a9fd89db8fd7e4389a982f7d28cf14") -- Depot 1 (2542121_1398797921565314396.manifest)
setManifestid(2542121,"1398797921565314396")