-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2545710
-- Name: Tony Hawk's™ Pro Skater™ 3 + 4
addappid(2545710) -- Tony Hawk's™ Pro Skater™ 3 + 4
addappid(2545712,0,"8027343d1efbd17177d104a56462394d6507a9d68f348e96e365b9d9db954804") -- Depot 1 (2545712_3420129442075334686.manifest)
setManifestid(2545712,"3420129442075334686")
addappid(2545711,0,"cc91db4546139b89ff7216df6c489b4c157da8515a88f2491921ae845b9dab5a") -- Depot 2 (2545711_1955691280552900405.manifest)
setManifestid(2545711,"1955691280552900405")