-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 254700
-- Name: Resident Evil 4 (2005)
addappid(254700) -- Resident Evil 4 (2005)
addappid(272260,0,"887fbc832b41f133430f20d78b365b07c724dd04c51ddcc48f879d907c4fd055") -- Depot 1 (272260_8170509752846139490.manifest)
setManifestid(272260,"8170509752846139490")
addappid(272261,0,"e899c415aef8a533e80abb6c72b6bf3602f0b9b064c1bbb381a655667c576336") -- Depot 2 (272261_4849919482799769104.manifest)
setManifestid(272261,"4849919482799769104")
addappid(254701,0,"138bb1e5f555bb1881214eced9844b83b643695fc8726786a42b42a3f5c27902") -- Depot 3 (254701_6999377187357974260.manifest)
setManifestid(254701,"6999377187357974260")
addappid(228983,0,"77c8e812cd79e67e2d376721253ebb07e06b3646f05671c6c9517b27be14734b") -- Depot 4 (228983_8124929965194586177.manifest)
setManifestid(228983,"8124929965194586177")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 5 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(254704,0,"870c561ed9cbeb8f5733db64c240b45b609f1b8440890d999af03e206733d31d") -- Depot 6 (254704_7927591321049438693.manifest)
setManifestid(254704,"7927591321049438693")