-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2564520
-- Name: Lost in Random: The Eternal Die
addappid(2564520) -- Lost in Random: The Eternal Die
addappid(2564521,0,"4b679f8c7ffc59c1398369a7bb72987e78717c22d81ec186eb11bb0cc0e5f6e8") -- Depot 1 (2564521_30759469985090769.manifest)
setManifestid(2564521,"30759469985090769")
addappid(3478380,0,"08b4f767f1591c4c96ec034dd7c78d0d442ac1d6c39586fff1ece5f94a7e4e6c") -- Depot 2 (3478380_8781692662282280762.manifest)
setManifestid(3478380,"8781692662282280762")