-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2581950
-- Name: Tiny Aquarium: Social Fishkeeping
addappid(2581950) -- Tiny Aquarium: Social Fishkeeping
addappid(2581952,0,"8ed572ef0cd138022a5bec468f7e8b882ec28a56a821f5a26c0766ce76482926") -- Depot 1 (2581952_492387074954113832.manifest)
setManifestid(2581952,"492387074954113832")