-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2589500
-- Name: Whisper of the House
addappid(2589500) -- Whisper of the House
addappid(2589501,0,"6f51226f61dd888511279cdc32b68f2eafddb79f8d92998ffcac30e6dae73021") -- Depot 1 (2589501_3635821901262768480.manifest)
setManifestid(2589501,"3635821901262768480")
addappid(2589502,0,"4b0d0eb017d111efc9280dba6335288de7d0c691d506d8ab30559a254745f0c2") -- Depot 2 (2589502_6504351145135758598.manifest)
setManifestid(2589502,"6504351145135758598")