-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2591310
-- Name: Pure Badminton
addappid(2591310) -- Pure Badminton
-- MAIN APP DEPOTS
addappid(2591312, 1, "ed8066779946e28b115187ad2fe7e2bb8a359c4811efe4c1d8621171f8962a99") -- Depot 2591312
setManifestid(2591312, "1442757797499812455", 4682979122)