-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2600
-- Name: Vampire: The Masquerade - Bloodlines
addappid(2600) -- Vampire: The Masquerade - Bloodlines
addappid(2604,0,"bd949f3356db457ac868d03ed76922436bf32e542357418b5e40c0cc73d3bbd5") -- Depot 1 (2604_215762182350885820.manifest)
setManifestid(2604,"215762182350885820")
addappid(2602,0,"b927197ffca00e23bf86b5bff4a74aecafb78b6b60e661eb1b4461f4bdff6b20") -- Depot 2 (2602_5942701187426550593.manifest)
setManifestid(2602,"5942701187426550593")
addappid(2605,0,"d7952ec7dac0218ed27476b8c6fbfd6c5dba91b98a4dacd67b7dc0aa366218e0") -- Depot 3 (2605_4881312952147864264.manifest)
setManifestid(2605,"4881312952147864264")
addappid(2601,0,"9d9a44e23934058d06dd944ade19bcb15c26d94c19606d9780c300b7590b3eea") -- Depot 4 (2601_7559191905314037026.manifest)
setManifestid(2601,"7559191905314037026")
addappid(2603,0,"b6b13add8afbdac9895ceae218f9d35243e840fb8a89fd9ff5c11a6ab33e3036") -- Depot 5 (2603_1507670812436564491.manifest)
setManifestid(2603,"1507670812436564491")