-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2604480
-- Name: City Transport Simulator®
addappid(2604480) -- City Transport Simulator
-- MAIN APP DEPOTS
addappid(2604481, 1, "f90984d0922ee373e6a38ccc5dd98001fbf35a3abc8e101f8e6ebd27f9b53ee0") -- Depot 2604481
setManifestid(2604481, "6427813133129898179", 18210331244)
-- SHARED DEPOTS (from other apps)
addappid(228985, 1, "21a2f639584d9bd462c5c4b3e10f881cba8a17ae674c830c4f083551cd356e9c") -- VC 2013 Redist (Shared from App 228980)
setManifestid(228985, "3966345552745568756", 13699237)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(3028650) -- City Transport Simulator StadtRegioTram Add-On
addappid(3100390) -- City Transport Simulator Type D Vienna Add-On
addappid(3323410) -- City Transport Simulator E1 Vienna Add-On
addappid(3323420) -- City Transport Simulator GT8N Mannheim Add-On
addappid(3323430) -- City Transport Simulator Tram Depot  Southern-Route Add-On
addappid(3592100) -- City Transport Simulator Tram Module
addappid(3592110) -- City Transport Simulator Bus Module
addappid(3711620) -- City Transport Simulator - Bus DLC GrfSteyr NG235
addappid(3711640) -- City Transport Simulator - Bus DLC MAN Lions City A23
addappid(3721360) -- City Transport Simulator - Tram DLC GT6 Mannheim
addappid(3864830) -- City Transport Simulator - Bus DLC MAN Lions City A47  A26
addappid(3864840) -- City Transport Simulator - Bus DLC MAN New Lions City
addappid(4132300) -- City Transport Simulator - Cosmetic DLC Basel Style