-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2614380
-- Name: Martha's Dolls
addappid(2614380) -- Martha's Dolls
addappid(2614381,0,"0a0affa364cd72bdb4f34f73ae4c24128fdeb17c6580015e50cb75b3eee83cdb") -- Depot 1 (2614381_1401734170325924323.manifest)
setManifestid(2614381,"1401734170325924323")