-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2615540
-- Name: VOID/BREAKER
addappid(2615540) -- VOID/BREAKER
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(2615541,0,"030fe7383fbdaf786d7c7551a16c2fb2eb6e211f1e0ca9766a6b1640c48664b2") -- Depot 2 (2615541_6298228385566204227.manifest)
setManifestid(2615541,"6298228385566204227")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")