-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2620730
-- Name: DEVIATOR
addappid(2620730) -- DEVIATOR
addappid(2620731,0,"d7a48e5026010c357d7b5c8064679e589f8def84dc2689b353b600df90a785d5") -- Depot 1 (2620731_50329268842442584.manifest)
setManifestid(2620731,"50329268842442584")