-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2622380
-- Name: ELDEN RING NIGHTREIGN
addappid(2622380) -- ELDEN RING NIGHTREIGN
addappid(2622381,0,"c3e9ccfedcda0cd10e53938e15261130b2e166007d2ca8f13aa5a05f06bd2630") -- Depot 1 (2622381_5633027460234818365.manifest)
setManifestid(2622381,"5633027460234818365")
addappid(2622383,0,"c6e496ba5ae5c8bfa358f3a7d923ec39964fa0a41c4fa77006249fe34e677af2") -- Depot 2 (2622383_3594833111882348402.manifest)
setManifestid(2622383,"3594833111882348402")
addappid(3515600,0,"698188f58b73df7953b831a1e83a2b75cce4a3ec24d6c8ea3e3869bed96219dd") -- Depot 3 (3515600_6784183289585886224.manifest)
setManifestid(3515600,"6784183289585886224")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 4 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 5 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(2622384,0,"029f67382779483e0b34bc2f1a1fae303e7f83a4efead9ed076448f386afd28f") -- Depot 6 (2622384_1210662523227354393.manifest)
setManifestid(2622384,"1210662523227354393")