-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2622380
-- Name: ELDEN RING NIGHTREIGN
addappid(2622380) -- ELDEN RING NIGHTREIGN
addappid(2622383,0,"c6e496ba5ae5c8bfa358f3a7d923ec39964fa0a41c4fa77006249fe34e677af2") -- Depot 1 (2622383_818727658284817322.manifest)
setManifestid(2622383,"818727658284817322")
addappid(2622381,0,"c3e9ccfedcda0cd10e53938e15261130b2e166007d2ca8f13aa5a05f06bd2630") -- Depot 2 (2622381_9139632565061756864.manifest)
setManifestid(2622381,"9139632565061756864")