-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2627260
-- Name: NINJA GAIDEN 4
addappid(2627260) -- Ninja Gaiden 4
-- MAIN APP DEPOTS
addappid(2627261, 1, "1dbbfa4a1302ac713af5d572bd94e7d0708ba581ca184c4124588ff3fdc06481") -- Depot 2627261
setManifestid(2627261, "4989820315570254152", 58644108257)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(3717100) -- NINJA GAIDEN 4 Deluxe Edition Content