-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2661300
-- Name: Grounded 2
addappid(2661300) -- Grounded 2
addappid(228984,0,"df7df98d3134f5e0009d5ebcaaf3bbb91ea2f7cbad81a37a9d16bc1835f57068") -- Depot 1 (228984_2547553897526095397.manifest)
setManifestid(228984,"2547553897526095397")
addappid(2661301,0,"cac026f4758d6992ff85de08375749a662b82dc6517be7dc72368060eca7427d") -- Depot 2 (2661301_3063070535031670480.manifest)
setManifestid(2661301,"3063070535031670480")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 3 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(228983,0,"77c8e812cd79e67e2d376721253ebb07e06b3646f05671c6c9517b27be14734b") -- Depot 4 (228983_8124929965194586177.manifest)
setManifestid(228983,"8124929965194586177")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 5 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")