-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2667950
-- Name: Gloomy Eyes
addappid(2667950) -- Gloomy Eyes
addappid(2667951,0,"0f05520aee6a7e9f4eb7a71e3dce66c71a5fcba243213418047cb83558064502") -- Depot 1 (2667951_7121230381635522253.manifest)
setManifestid(2667951,"7121230381635522253")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 2 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")