-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2670630
-- Name: Supermarket Simulator
addappid(2670630) -- Supermarket Simulator
addappid(2670631,0,"72fc26c211612ffaa7b30cdfea152be9628668260d7f8c375980e0f96e445701") -- Depot 1 (2670631_8201240390525612375.manifest)
setManifestid(2670631,"8201240390525612375")