-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2680010
-- Name: The First Berserker: Khazan
addappid(2680010) -- The First Berserker: Khazan
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(2680011,0,"fe9a3ee6a263260b75cf97d27ffc4eeda8c9eebc8019bdc57c247a546f450077") -- Depot 2 (2680011_1557784681110806112.manifest)
setManifestid(2680011,"1557784681110806112")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")