-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2688950
-- Name: Planet Coaster 2
addappid(2688950) -- Planet Coaster 2
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 2 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(2688951,0,"d1fc4044f8dbec56ccd7ccac0a38810470c5fecf00dedc36a294c39453f9adb0") -- Depot 3 (2688951_4110779745368312121.manifest)
setManifestid(2688951,"4110779745368312121")