-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 268910
-- Name: Cuphead
addappid(268910) -- Cuphead
addappid(268911,0,"5f5e2d0105e9fcfbd0c7151658efd92af0181865fe434192f8e2c5d24d4940da") -- Depot 1 (268911_6818141525323043853.manifest)
setManifestid(268911,"6818141525323043853")
addappid(1117851,0,"1d08dafb023ed4a43d3def619d54ace53b3b4bced035e744da83b4449f26cac7") -- Depot 2 (1117851_819870908970387521.manifest)
setManifestid(1117851,"819870908970387521")
addappid(704711,0,"355f7a6485745876ae337f59efb63a2a7c2012d8cfcbaf99fe6e93b511184b03") -- Depot 3 (704711_4630179950063277534.manifest)
setManifestid(704711,"4630179950063277534")
addappid(2072992,0,"fff30d5cdd3c7b9f7436ac0f2c962ec5ab80282ddb8cf0129eaa6723909c9724") -- Depot 4 (2072992_6626318741336770131.manifest)
setManifestid(2072992,"6626318741336770131")
addappid(268912,0,"6378a6f3808fd925e8fdc2cd115d7b60f1908a6dff6b5f6c1fb0af7f392db1e4") -- Depot 5 (268912_8633535714830637397.manifest)
setManifestid(268912,"8633535714830637397")
addappid(2072991,0,"2b53c9cd8ecf62cc469ee5f1f0cecb6e1217f9c766e5c58eb95084107868da66") -- Depot 6 (2072991_7794271606339901763.manifest)
setManifestid(2072991,"7794271606339901763")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 7 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(1117850,0,"c40d10dcd40756563a4956777e0bb4333e48d34c00e2836edd3d5fdbc0eba095") -- Depot 8 (1117850_468317947627682665.manifest)
setManifestid(1117850,"468317947627682665")
addappid(704712,0,"1d311725ca119b72edfa849cbbe123b72e39cdaef19dc8a22f15529d8ef2a556") -- Depot 9 (704712_7905790265200937644.manifest)
setManifestid(704712,"7905790265200937644")