-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2716400
-- Name: The Rise of the Golden Idol
addappid(2716400) -- The Rise of the Golden Idol
addappid(3333880,0,"1a7ba8ee1daadc056b3316e58463f01679a4266c1cdc4f6d6598072e65ce0443") -- Depot 1 (3333880_215519558629572677.manifest)
setManifestid(3333880,"215519558629572677")
addappid(3333870,0,"27c915af9c80ea8746d49e5832f54c3637bd9a20db457028196b94222b47142d") -- Depot 2 (3333870_2122439079419578985.manifest)
setManifestid(3333870,"2122439079419578985")
addappid(3335341,0,"2000a328e7913b585f04f3db4284593d30a52908720f87c3db07ccbaa9aa596c") -- Depot 3 (3335341_7859512607994307435.manifest)
setManifestid(3335341,"7859512607994307435")
addappid(3333860,0,"2adfc1b7518f90239656a9f29587c851f9b8f206381b83d6f0efef44af1bb663") -- Depot 4 (3333860_2431964205450928389.manifest)
setManifestid(3333860,"2431964205450928389")
addappid(2716401,0,"369c88aa7a34e596ee6cf0e3eb93af0259fe3ef7de70e1e285e73557f365188f") -- Depot 5 (2716401_2005169269265051408.manifest)
setManifestid(2716401,"2005169269265051408")