-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2717880
-- Name: The Rogue Prince of Persia
addappid(2717880) -- The Rogue Prince of Persia
addappid(2717882,0,"9cf88420d3b56db810785d1f9254e8368b15540c6441246024469862221f7edd") -- Depot 1 (2717882_7057619591713518713.manifest)
setManifestid(2717882,"7057619591713518713")
addappid(2717881,0,"4f68e98dcd0e02d77029d74ec41d2bb82ac62a486db69b9a034683ae1bddbf41") -- Depot 2 (2717881_5807315004995814392.manifest)
setManifestid(2717881,"5807315004995814392")