-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2719750
-- Name: Star Birds
addappid(2719750) -- Star Birds
addappid(2719752,0,"14b66813cc3109312baf1d0c3fe4a3a5383c7d481d10f24a289cdcab933598fe") -- Depot 1 (2719752_2555590868938535556.manifest)
setManifestid(2719752,"2555590868938535556")