-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2735580
-- Name: Netherworld Covenant
addappid(2735580) -- Netherworld Covenant
addappid(2735583,0,"c55904da7d44d2a56d195136d0a47a4c722bd166cd278e69055417c1972b39be") -- Depot 1 (2735583_5380353752190294095.manifest)
setManifestid(2735583,"5380353752190294095")