-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2737070
-- Name: Crime Simulator
addappid(2737070) -- Crime Simulator
addappid(2737071,0,"36e272c2274c8d6dbf4a697d1faa618de36bbacf8439215d60cca4350601aedb") -- Depot 1 (2737071_2542679740768906713.manifest)
setManifestid(2737071,"2542679740768906713")