-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2744010
-- Name: Urban Jungle
addappid(2744010) -- Urban Jungle
-- MAIN APP DEPOTS
addappid(2744011, 1, "e9485680f74b921003e502e7360fe17360400e4c16d3e0c5c0d93be67dbd83d2") -- Depot 2744011
setManifestid(2744011, "6558734518054352941", 3592594740)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(4036100) -- Urban Jungle Brothers Wedding Story