-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2752180
-- Name: No Sleep For Kaname Date - From AI: THE SOMNIUM FILES
addappid(2752180) -- No Sleep For Kaname Date - From AI: THE SOMNIUM FILES
addappid(2752181,0,"0a7d69eea05820bf0a2c94443b9bb36b696a100428805572662c91948c032886") -- Depot 1 (2752181_1615048623698072800.manifest)
setManifestid(2752181,"1615048623698072800")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 2 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")