-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 275850
-- Name: No Man's Sky
addappid(275850) -- No Man's Sky
addappid(275851,0,"a5ce5217e5d5d20115ea81209764d4e89f37bed55b84690951d5df23e73852a6") -- Depot 1 (275851_1785595455807704408.manifest)
setManifestid(275851,"1785595455807704408")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(275852,0,"1f8fb10eb2401484d32af8e6c0d3b7e4148e78e4cf8f632afe1ab6600fb7e57d") -- Depot 3 (275852_9012531614157709016.manifest)
setManifestid(275852,"9012531614157709016")
addappid(228983,0,"77c8e812cd79e67e2d376721253ebb07e06b3646f05671c6c9517b27be14734b") -- Depot 4 (228983_8124929965194586177.manifest)
setManifestid(228983,"8124929965194586177")
addappid(228985,0,"21a2f639584d9bd462c5c4b3e10f881cba8a17ae674c830c4f083551cd356e9c") -- Depot 5 (228985_3966345552745568756.manifest)
setManifestid(228985,"3966345552745568756")