-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2800080
-- Name: Thief VR: Legacy of Shadow
addappid(2800080) -- Thief VR: Legacy of Shadow
-- MAIN APP DEPOTS
addappid(2800081, 1, "97e6b86cbd24c949ee37e954ed05c6c6a874270cf39a3ba8759228d80abbbc67") -- Depot 2800081
setManifestid(2800081, "4710639321106229005", 34881917022)