-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2808930
-- Name: Lust Goddess
addappid(2808930) -- Lust Goddess
addappid(2808932,0,"4e6ec6d50ec30535e617715f1f8031adbb9512e759e369469e271977753128f3") -- Depot 1 (2808932_97133473466275944.manifest)
setManifestid(2808932,"97133473466275944")
addappid(2808931,0,"56d0d282de07ffeea381c878beba19735867e44776afdbd8dd5bba34de41db9e") -- Depot 2 (2808931_5671524184786961625.manifest)
setManifestid(2808931,"5671524184786961625")