-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2833580
-- Name: BRAVELY DEFAULT FLYING FAIRY HD Remaster
addappid(2833580) -- BRAVELY DEFAULT FLYING FAIRY HD Remaster
-- MAIN APP DEPOTS
addappid(2833581, 1, "5ff21e6a3f7dfdd86e8ed49a695b5c520086a36bb2f76d190222a18d2fda5f96") -- Depot 2833581
setManifestid(2833581, "3997184168768107255", 10100586980)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)