-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2880730
-- Name: AI2U: With You 'Til The End
addappid(2880730) -- AI2U: With You 'Til The End
addappid(2880731,0,"e2ca87b16b3ac8c52ccd235d0e58670b6d208f1fa79f280ba0b72586dc36340a") -- Depot 1 (2880731_4246938597435330126.manifest)
setManifestid(2880731,"4246938597435330126")