-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2915460
-- Name: OneShot: World Machine Edition
addappid(2915460, 1, "0f083b1eb3484c2c869b76d1e20a96ace234ce6834e525161e610991757f3b9f") -- OneShot: World Machine Edition
-- MAIN APP DEPOTS
addappid(2915461, 1, "022099f7246ff72908c4a31e8fec337cfc87537266af23bd5ff99d327fc1ecb4") -- Depot 2915461
setManifestid(2915461, "888638496164293001", 1515352202)
addappid(2915462, 1, "150de419c191473e164661c3112e25c71c12e3c22eba48b89584280b57297a93") -- Depot 2915462
setManifestid(2915462, "680733440133106805", 1590561455)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)