-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2966320
-- Name: Starsand Island
addappid(2966320) -- Starsand Island
-- MAIN APP DEPOTS
addappid(2966321, 1, "ce86c628c5c525587d2aea36d5a745c980584e22eca6389d8bfd7a63c0db1c4c") -- Depot 2966321
setManifestid(2966321, "8918682171961676262", 10813742625)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(4391920) --  DLC
addappid(4395490) --  DLC
addappid(4424260) --  DLC