-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2989180
-- Name: Darwin's Paradox!
-- Updated: April 2, 2026 at 11:23:22 AM UTC
-- Darwin's Paradox
-- Created: April 02, 2026 at 03:55:14 EDT
-- Website: https://manifest.morrenus.xyz/
-- Total Depots: 3
-- Total DLCs: 1
-- Shared Depots: 2

-- MAIN APPLICATION
addappid(2989180) -- Darwin's Paradox
-- MAIN APP DEPOTS
addappid(2989181, 1, "51cd23f2f591d2786878933882bf37d6dc8887678b82a909dedae4a9ae6e4ebf") -- Depot 2989181
setManifestid(2989181, "5720863090843276452", 8068473100)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(3990600) -- Darwin Pre-Order Skin Pack
