-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2996660
-- Name: 怪物的王座
addappid(2996660) -- 怪物的王座
addappid(2996661,0,"a431e120b998262d3bbf1e9ad6f4327bf5945f9e5d10655902517505d4015012") -- Depot 1 (2996661_3769925907007321777.manifest)
setManifestid(2996661,"3769925907007321777")