-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2997230
-- Name: Planet of Lana II
addappid(2997230) -- Planet of Lana II
-- MAIN APP DEPOTS
addappid(2997231, 1, "a397e3852d84a423e6087d18c06db8f5a9123a2b20acee6f925c214b021dfd2d") -- Depot 2997231
setManifestid(2997231, "4871357915864752788", 43354623122)
-- DLCS WITH DEDICATED DEPOTS
-- Planet of Lana II - Supporter Pack (AppID: 4349060)
addappid(4349060)
addappid(4349060, 1, "3bbe18ac24992eb412d137d3a12eb9405da20f0db5804decada1d8aec939a1fd") -- Planet of Lana II - Supporter Pack - Depot 4349060
setManifestid(4349060, "5452787470878400762", 117905407)