-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2998600
-- Name: Back from the other world, I missed love.
addappid(2998600) -- Back from the other world, I missed love.
addappid(229000,0,"3aae9271fb93da5395ffbfe338d3647de5dcfab3fc6fb901ca2ec28849b3d6bf") -- Depot 1 (229000_4622705914179893434.manifest)
setManifestid(229000,"4622705914179893434")
addappid(229020,0,"efca2304d92ac2bb7ebca174e6e5015fb0daf45d7db8ecfc1db6eaccdc7b27d9") -- Depot 2 (229020_5799761707845834510.manifest)
setManifestid(229020,"5799761707845834510")
addappid(229012,0,"421e499f39a617c1a3b6baf11fbc65ffebd541d2c39c38d3bf6ffbd87919ce12") -- Depot 3 (229012_4353723233161159493.manifest)
setManifestid(229012,"4353723233161159493")
addappid(2998601,0,"c7476c7ce2f864843409c407b3eb1442e85227db356042d2fb903915e4acbc1d") -- Depot 4 (2998601_1549929342878654029.manifest)
setManifestid(2998601,"1549929342878654029")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 5 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 6 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")