-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3008340
-- Name: Day of the Shell
addappid(3008340) -- Day of the Shell
addappid(3008341,0,"8299698430162c8893c22bc715cc0ba223c1ebbe539e3fa6213e443aa61e4d2a") -- Depot 1 (3008341_1806474902988538264.manifest)
setManifestid(3008341,"1806474902988538264")