-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3014080
-- Name: The Hundred Line -Last Defense Academy-
addappid(3014080) -- The Hundred Line -Last Defense Academy-
addappid(3313476,0,"62e0bf9e3a7f470967ba2bc5e91a0f92301a1cd96480c8129b2756c2236e91b4") -- Depot 1 (3313476_312663337026652661.manifest)
setManifestid(3313476,"312663337026652661")
addappid(3319760,0,"fe92de42a7232fcb703844d0f9644a24611561c408aa574d4dba47f3ee44b769") -- Depot 2 (3319760_2992787271555217105.manifest)
setManifestid(3319760,"2992787271555217105")
addappid(3313475,0,"8b6728f6eac52d923e015280a35003cc3a44368a53126caa4f419e340b4e96e1") -- Depot 3 (3313475_2668544798282893607.manifest)
setManifestid(3313475,"2668544798282893607")
addappid(3313474,0,"cc700042dbbffb57753bc0af37d5b8f8983c6913ce31f98c42ba3968739eeb22") -- Depot 4 (3313474_1129197215123705621.manifest)
setManifestid(3313474,"1129197215123705621")
addappid(3313473,0,"7139c9b192d7d27f8735a404af47a898e4218cdd8653933a6680df1ed49013b7") -- Depot 5 (3313473_1114607683842095068.manifest)
setManifestid(3313473,"1114607683842095068")
addappid(3014081,0,"9c8b0e729ef1fce35224045a12393cf5a7069e60692bc9b3bf2d64b0bb37b6a3") -- Depot 6 (3014081_4580204265212912643.manifest)
setManifestid(3014081,"4580204265212912643")