-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3014080
-- Name: The Hundred Line -Last Defense Academy-
addappid(3014080) -- The Hundred Line -Last Defense Academy-
addappid(3319760,0,"fe92de42a7232fcb703844d0f9644a24611561c408aa574d4dba47f3ee44b769") -- Depot 1 (3319760_2992787271555217105.manifest)
setManifestid(3319760,"2992787271555217105")
addappid(3014081,0,"9c8b0e729ef1fce35224045a12393cf5a7069e60692bc9b3bf2d64b0bb37b6a3") -- Depot 2 (3014081_7379430715548697808.manifest)
setManifestid(3014081,"7379430715548697808")