-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3032010
-- Name: The Supper: New Blood
addappid(3032010) -- The Supper: New Blood
addappid(3032011,0,"9f7485547b481726e56144a2d3df3f2ac0045ebf7d1614d19ceb3719b4f5984a") -- Depot 1 (3032011_2805394906415017456.manifest)
setManifestid(3032011,"2805394906415017456")