-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3039890
-- Name: Bubsy in: The Purrfect Collection
addappid(3039890) -- Bubsy in: The Purrfect Collection
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(3039891,0,"908f0d0cd786d8c3fecea6b1ec98fa35d4652328e43959ac5efd5863032ceccf") -- Depot 2 (3039891_6104050582827056214.manifest)
setManifestid(3039891,"6104050582827056214")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")