-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 304240
-- Name: Resident Evil
addappid(304240) -- Resident Evil
addappid(345190,0,"60ab048988d781e57c9bbc1881b3a4fbc67178b649d758ef782277efc5f073f5") -- Depot 1 (345190_7864329718337415853.manifest)
setManifestid(345190,"7864329718337415853")
addappid(304242,0,"e86af320324228098bed69cf389ccd1b7af582a1f5725a1952a5815fd7cc1313") -- Depot 2 (304242_9087090834863155228.manifest)
setManifestid(304242,"9087090834863155228")
addappid(304241,0,"628406156243272990c118c3a8497b1bdc8b03a11cd1b21e986ff86c89a45f49") -- Depot 3 (304241_110278523771241710.manifest)
setManifestid(304241,"110278523771241710")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 4 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(345191,0,"eb7b2280a99010609c30169ce5ea98a4052c54a7139feab5e3ffacdac64035fd") -- Depot 5 (345191_7576499935902985330.manifest)
setManifestid(345191,"7576499935902985330")