-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3059520
-- Name: F1® 25
addappid(3059520) -- F1® 25
addappid(3059522,0,"136b91fa8f220638f0a95077f481dbcb9c6f8d5a936401ec0222ddc2cc73de68") -- Depot 1 (3059522_5001141504202113278.manifest)
setManifestid(3059522,"5001141504202113278")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(3059524,0,"0f267a629c6d00a85bbea9fcadd7a8031d68da2504ea8e24821967b15c695e01") -- Depot 3 (3059524_2970295120781387815.manifest)
setManifestid(3059524,"2970295120781387815")
addappid(3059521,0,"69b468d1904c13ad60ff37077c6c6350439f3e70a1df3afcfc075f41325f6b8b") -- Depot 4 (3059521_2861963114185030019.manifest)
setManifestid(3059521,"2861963114185030019")
addappid(3059523,0,"0fefd33650cc16731c9eaa7582b567f5ab2e1dfe22480ba457f704740cb59275") -- Depot 5 (3059523_5193400739583936358.manifest)
setManifestid(3059523,"5193400739583936358")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 6 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")