-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3067890
-- Name: Star Fire: Eternal Cycle
addappid(3067890) -- Star Fire: Eternal Cycle
addappid(3067891,0,"72a0b4eeae9db9d6be05f64f080e53e2a7a10f121635390a1997a4f3b9aba479") -- Depot 1 (3067891_3226242105023666977.manifest)
setManifestid(3067891,"3226242105023666977")