-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3074840
-- Name: Utawarerumono: ZAN
addappid(3074840) -- Utawarerumono: ZAN
-- MAIN APP DEPOTS
addappid(3074841, 1, "8f28dab410df56078a608788e3377f4c463ad81f28ebc78aa078ac1198d0991a") -- Depot 3074841
setManifestid(3074841, "1702452996808401555", 7806642867)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(3959270) -- Utawarerumono ZAN - DLC Character Oshtor
addappid(3959280) -- Utawarerumono ZAN - DLC Character Munechika
addappid(3978880) -- Utawarerumono ZAN - DLC Outfit Haku
addappid(3978900) -- Utawarerumono ZAN - DLC Outfit Kuon
addappid(3978920) -- Utawarerumono ZAN - DLC Outfit Rulutieh
addappid(3978930) -- Utawarerumono ZAN - DLC Outfit Nekone
addappid(3978940) -- Utawarerumono ZAN - DLC Outfit Kiwru
addappid(3978950) -- Utawarerumono ZAN - DLC Outfit Uruuru  Saraana
addappid(3978960) -- Utawarerumono ZAN - DLC Outfit Nosuri
addappid(3978970) -- Utawarerumono ZAN - DLC Outfit Ougi
addappid(3978980) -- Utawarerumono ZAN - DLC Outfit Ukon
addappid(3978990) -- Utawarerumono ZAN - DLC Outfit Maroro
addappid(3979010) -- Utawarerumono ZAN - DLC Outfit Atuy
addappid(3979020) -- Utawarerumono ZAN - DLC Outfit Jachdwalt
addappid(4201540) -- Utawarerumono ZAN - DLC Outfit Kuons Hood
addappid(4218120) -- Utawarerumono ZAN Sticker Set 1
addappid(4218130) -- Utawarerumono ZAN Sticker Set 2