-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3093400
-- Name: Knightica
addappid(3093400) -- Knightica
addappid(3093401,0,"fba8be508356b56d8c8a45b64116e7e109f4faea526311d2ea0beed8ea40c52f") -- Depot 1 (3093401_549673424907946287.manifest)
setManifestid(3093401,"549673424907946287")