-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3141130
-- Name: 100 Italy Cats
addappid(3141130) -- 100 Italy Cats
addappid(3141131,0,"a031a5a52cfba1769268c1df773853eca5acca6c5ba2eada1f5f9a4666d7e73d") -- Depot 1 (3141131_1981676596519827791.manifest)
setManifestid(3141131,"1981676596519827791")