-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3150480
-- Name: Agatha Christie - Death on the Nile
addappid(3150480) -- Agatha Christie - Death on the Nile
addappid(3957320,0,"2ca9d400c23276cc092fa4e0fcf3c6714051836e235c6ce9f0c72ea9aa0b6e48") -- Depot 1 (3957320_6147225638822141144.manifest)
setManifestid(3957320,"6147225638822141144")
addappid(3150481,0,"9e961aeaf789de2af860bc2c0cd909bfe4e74777accc39cec2aee7449e0412cb") -- Depot 2 (3150481_149712653633380880.manifest)
setManifestid(3150481,"149712653633380880")