-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3159330
-- Name: Assassin’s Creed Shadows
addappid(3159330) -- Assassin’s Creed Shadows
addappid(1716751,0,"84780b728a23b1dabbe8b064807ccd3dbd40c67139ed569101104a418c581675") -- Depot 1 (1716751_818295193716041715.manifest)
setManifestid(1716751,"818295193716041715")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(3159334,0,"919bdf5d6752a3dfc2cf5f76c6800e25059aeab0489c2ec656e1bb938fef0f13") -- Depot 3 (3159334_4089506801826452583.manifest)
setManifestid(3159334,"4089506801826452583")
addappid(3159336,0,"10867627410a4ed3756f1263fe75741717e2c6f7797ff9af89cd7c5749a14f2b") -- Depot 4 (3159336_1120211533521827360.manifest)
setManifestid(3159336,"1120211533521827360")
addappid(3159331,0,"a1a2865a35a1aa7255e0d1a8d6cedab23f2b34346e4a359a283f1a5ceb826ddf") -- Depot 5 (3159331_7491124791681029149.manifest)
setManifestid(3159331,"7491124791681029149")
addappid(3159333,0,"24bbf4e14d616c7df7c56696e444569bcf5689554a6a79f731426e4fac7d66ea") -- Depot 6 (3159333_2890497842286120105.manifest)
setManifestid(3159333,"2890497842286120105")
addappid(3159337,0,"e4e59c05f264ffc35d4c0629f2f887bee3dc7848b240411d65a8f2e2d793843b") -- Depot 7 (3159337_8152455803407100798.manifest)
setManifestid(3159337,"8152455803407100798")
addappid(3159335,0,"843ebde3282fd10fe2204126d7be3c471c849e01618fd2419fd56be6a2e4fc72") -- Depot 8 (3159335_7433144042915746485.manifest)
setManifestid(3159335,"7433144042915746485")