-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3164500
-- Name: Schedule I
addappid(3164500) -- Schedule I
addappid(3164501,0,"81d0de07788de885787b0519b9dabf51618be6cba9124497decf572ac96624f4") -- Depot 1 (3164501_4917957940192610936.manifest)
setManifestid(3164501,"4917957940192610936")