-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3166200
-- Name: Across the Abyss: Voidborn
addappid(3166200) -- Across the Abyss: Voidborn
addappid(3166201,0,"21f7fe3295cd7c7d62ab1efa79bccaba68fc95402f2e10f592a10a090aef949e") -- Depot 1 (3166201_6758072010788289515.manifest)
setManifestid(3166201,"6758072010788289515")