-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3177890
-- Name: Rana Card
addappid(3177890) -- Rana Card
addappid(3177891,0,"344bcf8bc7e6615ce2520bdf84cbf5ad3430bc44909cef5998141e64fa3474e7") -- Depot 1 (3177891_7537055392985684812.manifest)
setManifestid(3177891,"7537055392985684812")