-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3180070
-- Name: No, I'm not a Human
addappid(3180070) -- No, I'm not a Human
addappid(3180071,0,"46e2cd1b157fec728146480948f03addd84b05ad244310eea46c81c3ebb47971") -- Depot 1 (3180071_6481422090201577381.manifest)
setManifestid(3180071,"6481422090201577381")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")