-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3183280
-- Name: Game of Thrones: Kingsroad
addappid(3183280) -- Game of Thrones: Kingsroad
addappid(3183281,0,"68dce48db7977a0ea03b654ede2a578765ee4320c93955e29aeae0ef9bb43c9e") -- Depot 1 (3183281_5318696957565459391.manifest)
setManifestid(3183281,"5318696957565459391")
addappid(3183282,0,"7fda33f42919c3fececa548528f54b0514a220b324f6a87377d20f63a8d7982f") -- Depot 2 (3183282_4251713182975288230.manifest)
setManifestid(3183282,"4251713182975288230")
addappid(3477690,0,"09ad1044265abc607d130258e11d192531c0471b4755edbe711911048d6bd94f") -- Depot 3 (3477690_6790709864012105538.manifest)
setManifestid(3477690,"6790709864012105538")