-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3201010
-- Name: Starlight Revolver
addappid(3201010) -- Starlight Revolver
addappid(3201012,0,"751e4bb432fc4bc3ad95b25303eaaeab8c958a2a7f5743d83cd1122a17fb45ce") -- Depot 1 (3201012_7657118855442245741.manifest)
setManifestid(3201012,"7657118855442245741")
addappid(3201011,0,"d1d08539c276061ca3555b2aab801c92cf7791cc7dd48861a8d92a1a5217b0cb") -- Depot 2 (3201011_3230846765447900968.manifest)
setManifestid(3201011,"3230846765447900968")