-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 322330
-- Name: Don't Starve Together
addappid(322330) -- Don't Starve Together
addappid(322333,0,"065e9fc3141e45c895786254045560d2af8860c513d0a6077fceaca5fda4c32f") -- Depot 1 (322333_1999511978834168015.manifest)
setManifestid(322333,"1999511978834168015")
addappid(228982,0,"fa2997f03c3576c41174f200596ab2246fd1e39c0911f9b869e92635ae5b0ff5") -- Depot 2 (228982_6413394087650432851.manifest)
setManifestid(228982,"6413394087650432851")
addappid(322331,0,"3ee94d4c47554fc580de37cdeb4bb41020ece2d5ab195d51d8b87f5e438e9f23") -- Depot 3 (322331_703388324512726297.manifest)
setManifestid(322331,"703388324512726297")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 4 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 5 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(322332,0,"8f36286253d1b2e61f2e7bfec57510d6ec34da84a9d126dc4adf19f6cff117be") -- Depot 6 (322332_8063403489762830098.manifest)
setManifestid(322332,"8063403489762830098")