-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3228590
-- Name: Deadzone: Rogue
addappid(3228590) -- Deadzone: Rogue
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 2 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(3228591,0,"ff50f696309f1bdaedc819a0dfc5ad20497d9884179b19683f5ceba047094567") -- Depot 3 (3228591_1837336244158265072.manifest)
setManifestid(3228591,"1837336244158265072")