-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3231090
-- Name: Amarillo's Butt Slapper
addappid(3231090) -- Amarillo's Butt Slapper
addappid(3231091,0,"d1ad5cf0111a45abfbe5d87463f55175c6c6914dc78fe4388d5ec9580c3b03d3") -- Depot 1 (3231091_5832010787502848819.manifest)
setManifestid(3231091,"5832010787502848819")