-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3237970
-- Name: Bubsy 4D
-- Updated: May 24, 2026 at 11:40:56 AM UTC
-- Bubsy 4D
-- Created: May 23, 2026 at 02:28:08 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 2
-- Total DLCs: 0
-- Shared Depots: 1

-- MAIN APPLICATION
addappid(3237970, 1, "869fc4d23152cb51db98af7544da6d7805cdecc88a24a7b125f22d38c328ca60") -- Bubsy 4D
-- MAIN APP DEPOTS
addappid(3237971, 1, "451fa3287362f020a4a9730d7eb4672dd2a6c1933387b7dcffe79cc161fed8a1") -- Depot 3237971
setManifestid(3237971, "4791817002485724149", 1632560753)
-- SHARED DEPOTS (from other apps)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
