-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3238670
-- Name: Conquest Dark
addappid(3238670) -- Conquest Dark
-- MAIN APP DEPOTS
addappid(3238671, 1, "13cd290bb2c0f5a7295e7fb13e3a40c979c54085244db28c2251421edde94157") -- Depot 3238671
setManifestid(3238671, "6630438080667384836", 647827297)