-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3241660
-- Name: R.E.P.O.
addappid(3241660) -- R.E.P.O.
addappid(3241661,0,"0a0fcffb2de6fb0fa6caff076a5a8cb960903d17320968d5c042fd5a4f9ad2ad") -- Depot 1 (3241661_4154963422191387469.manifest)
setManifestid(3241661,"4154963422191387469")