-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3247750
-- Name: Mycopunk
addappid(3247750) -- Mycopunk
addappid(3247751,0,"888bdd148939bec18022ebea7b4041f7d8a6de44b5779a16ded755e6917cea6f") -- Depot 1 (3247751_2342846826034245660.manifest)
setManifestid(3247751,"2342846826034245660")