-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3269600
-- Name: Flowers And Favours: Florist Simulator
addappid(3269600) -- Flowers And Favours: Florist Simulator
addappid(3269601,0,"c67f952b90a63038175d54af1590c28f7a8aa1378ecd8a71a6b657c8b0cb7a14") -- Depot 1 (3269601_8854961461476894007.manifest)
setManifestid(3269601,"8854961461476894007")