-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3279830
-- Name: 导演，请多多指教
addappid(3279830) -- 导演，请多多指教
addappid(3279831,0,"a97b3d7e7d372df4ed0f8b87cfa87f9187fc28e7fbd40666c356f024179d0e6f") -- Depot 1 (3279831_3946244805037492762.manifest)
setManifestid(3279831,"3946244805037492762")