-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3288300
-- Name: Dark Fairy Tale: Dreamland Survivors
addappid(3288300) -- Dark Fairy Tale: Dreamland Survivors
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(3288301,0,"54e8719fe2d4ca369a41e7c8bbe6db4dea81fbcac6cdd4ccd064d7dda6f7548e") -- Depot 2 (3288301_125569355464272998.manifest)
setManifestid(3288301,"125569355464272998")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")