-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3298910
-- Name: Once a Pawn a King
addappid(3298910) -- Once a Pawn a King
addappid(3298911,0,"149a8c27b2d44eeb69af95a2efb2ba8b17afd29259fdcb20f1783610e4e24811") -- Depot 1 (3298911_6902432948511366697.manifest)
setManifestid(3298911,"6902432948511366697")