-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3301060
-- Name: Desktop Mate
addappid(3301060) -- Desktop Mate
addappid(3301061,0,"6e7d44d14db1b1b4e5d43a64af62fb4845066fe0ccacef125ac6390978ac97d0") -- Depot 1 (3301061_3968337802164451354.manifest)
setManifestid(3301061,"3968337802164451354")
addappid(3465160,0,"7a1e4b009760e36441de4593f40020f18b3372217a998f459694bcc43b371cbd") -- Depot 2 (3465160_8155672395498371516.manifest)
setManifestid(3465160,"8155672395498371516")
addappid(3533450,0,"9c3422e204117b9185c9474c97cfb09cc8f9dffd5bf40704c2747623474dea8f") -- Depot 3 (3533450_9194202751680967547.manifest)
setManifestid(3533450,"9194202751680967547")
addappid(3359730,0,"0f11d40d2674cb19a055d6d65f4d4d845bec01167e0977aba91558bb93d4cad6") -- Depot 4 (3359730_4663382237700679265.manifest)
setManifestid(3359730,"4663382237700679265")