-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3319120
-- Name: Don't Play This
-- Updated: May 31, 2026 at 05:52:02 AM UTC
-- Don't Play This
-- Created: April 19, 2026 at 20:27:40 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(3319120) -- Don't Play This
-- MAIN APP DEPOTS
addappid(3319121, 1, "081b808d615a6c347a03391403bec98c3dea52102b6691dce858a563b1ad631a") -- Depot 3319121
setManifestid(3319121, "3524511638640060163", 8975889428)
