-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3327640
-- Name: hololive Holo's Hanafuda
addappid(3327640) -- hololive Holo's Hanafuda
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(3327641,0,"2b4addb7e1b468cfaaf3fe68a2f4c86583c7d1a09048c61bf7367a388ef1fbe8") -- Depot 2 (3327641_5387861859184337319.manifest)
setManifestid(3327641,"5387861859184337319")