-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3337140
-- Name: After Inc: Revival
addappid(3337140) -- After Inc: Revival
addappid(3337143,0,"93279b68247b5e1c1f5f74972baf9058c3a7479c4b67cbe68a6e53aa60915819") -- Depot 1 (3337143_4470410249243289545.manifest)
setManifestid(3337143,"4470410249243289545")