-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3350200
-- Name: 情感反诈模拟器
addappid(3350200) -- 情感反诈模拟器
addappid(3350201,0,"974375ed45d0dfd5d3224cfbd5397125e752a9a2d4c309473f9b613abdefb3f8") -- Depot 1 (3350201_1618837803766536349.manifest)
setManifestid(3350201,"1618837803766536349")