-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3350200
-- Name: 情感反诈模拟器
addappid(3350200) -- 情感反诈模拟器
addappid(3350201,0,"974375ed45d0dfd5d3224cfbd5397125e752a9a2d4c309473f9b613abdefb3f8") -- Depot 1 (3350201_6226275911610796995.manifest)
setManifestid(3350201,"6226275911610796995")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(3350202,0,"80afb11fa9e728e5367517c4c4987b73fb3ea468f97b3ffaaff8801399c2cbbd") -- Depot 3 (3350202_6347966735381210873.manifest)
setManifestid(3350202,"6347966735381210873")