-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3354750
-- Name: skate.
addappid(3354750) -- skate.
addappid(3354751,0,"12f0eab99e98b8912cb7e80d06eb068409135cc2968fc071880ac3f5850e1722") -- Depot 1 (3354751_876401416436541781.manifest)
setManifestid(3354751,"876401416436541781")