-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3357380
-- Name: NEDRA
addappid(3357380) -- NEDRA
addappid(3357381,0,"f6ddf3011a0f746ebcc750cf1315450781e39e18ea59864afb2c3f961708685f") -- Depot 1 (3357381_6623312871033569898.manifest)
setManifestid(3357381,"6623312871033569898")