-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3361510
-- Name: Coal LLC
addappid(3361510) -- Coal LLC
addappid(3361511,0,"603aa781476bfd4d6e22387bf16d703ad2c49998204542539dc9f0b08ac89299") -- Depot 1 (3361511_6527071444935977876.manifest)
setManifestid(3361511,"6527071444935977876")