-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3362660
-- Name: World War Z VR
addappid(3362660) -- World War Z VR
addappid(3362661,0,"328584ca8c49db6ff51252af9f782149e472055b0550cb64a4953739fe11d673") -- Depot 1 (3362661_7903418327869468349.manifest)
setManifestid(3362661,"7903418327869468349")