-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3365050
-- Name: Atelier Ryza 3: Alchemist of the End & the Secret Key DX
addappid(3365050) -- Atelier Ryza 3: Alchemist of the End & the Secret Key DX
-- MAIN APP DEPOTS
addappid(3365051, 1, "5f0ac27fa68bdbbb717f526d76c9a8c440ae3cfd217b65f183fa281d0b1cdf85") -- Depot 3365051
setManifestid(3365051, "4145926627037928955", 48862714474)
-- SHARED DEPOTS (from other apps)
addappid(228988, 1, "1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- VC 2019 Redist (Shared from App 228980)
setManifestid(228988, "6645201662696499616", 29212173)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(3782470) -- Atelier Ryza 3 Alchemist of the End  the Secret Key DX - DX Version Pre-order Bonus