-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3378960
-- Name: Lost Soul Aside™
addappid(3378960) -- Lost Soul Aside™
addappid(3378961,0,"02157efe6285cacaa20730d8f0bd83c4b020ec25cd0c75e88ad7ac83465a570a") -- Depot 1 (3378961_8610612055954563073.manifest)
setManifestid(3378961,"8610612055954563073")
addappid(3484241,0,"850583f98b56a2b21b65c877cf536c83830fa54c21f30ce3c6397935f065b2bc") -- Depot 2 (3484241_7238494630064099886.manifest)
setManifestid(3484241,"7238494630064099886")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 3 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 4 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(229006,0,"9bc3e05ce55153e5c315cb18024602ca15958a7be03adc5ffbe53b00a8524416") -- Depot 5 (229006_1784011429307107530.manifest)
setManifestid(229006,"1784011429307107530")