-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3380520
-- Name: ToHeart
addappid(3380520) -- ToHeart
addappid(3380521,0,"76ab56f6f887226caa5e5f8453facba45a2f5df5475fd6788484b6dec37a3f76") -- Depot 1 (3380521_7244426734737988142.manifest)
setManifestid(3380521,"7244426734737988142")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 2 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")