-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3405340
-- Name: Megabonk
addappid(3405340) -- Megabonk
-- MAIN APP DEPOTS
addappid(3405342, 1, "0fbab2971279bba685debbfa503e2da7e014fb5066cec822fcda80f9465e304e") -- Depot 3405342
setManifestid(3405342, "1165100047291666655", 439644625)