-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3412310
-- Name: Aeternum Grand Plaza
addappid(3412310) -- Aeternum Grand Plaza
addappid(3412311,0,"f389e67ab03c16c370a2cecc5cce44b5ee3233faeb4ff7aa945c2f3080e3a471") -- Depot 1 (3412311_5560808176843470698.manifest)
setManifestid(3412311,"5560808176843470698")