-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3417510
-- Name: Goblintown: Really Hard Driving Game
addappid(3417510) -- Goblintown: Really Hard Driving Game
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 2 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(3417511,0,"82923f6d966077a0b27b51b4bda1c169308085be88b1278d62a3557b657432dc") -- Depot 3 (3417511_3232079873295195643.manifest)
setManifestid(3417511,"3232079873295195643")