-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3439030
-- Name: The King Of Truancy
addappid(3439030) -- The King Of Truancy
addappid(3439031,0,"96571fc504ae964f63a9b1c3df74bb1e9542111348e93c4fb95cae8edfda14d7") -- Depot 1 (3439031_1217577801825030751.manifest)
setManifestid(3439031,"1217577801825030751")