-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3454980
-- Name: Mortal Kombat: Legacy Kollection
addappid(3454980) -- Mortal Kombat: Legacy Kollection
-- MAIN APP DEPOTS
addappid(3454981, 1, "a411f1c5ad0ff5f71b4e8aab564c7fd8fbd44ac3598a07480f2af377bcf65a9f") -- Depot 3454981
setManifestid(3454981, "6560034032350423247", 13390184276)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)