-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3460110
-- Name: Breaker of fatalism
addappid(3460110) -- Breaker of fatalism
addappid(3460111,0,"d03ec0d3fcbaddda47fe14e2b82f56e030fb49d36adf609f3b33407e95183e75") -- Depot 1 (3460111_360484998412325442.manifest)
setManifestid(3460111,"360484998412325442")