-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3470610
-- Name: Dawn Break
-- Updated: April 9, 2026 at 09:34:30 PM UTC
-- Dawn Break
-- Created: April 09, 2026 at 17:05:19 EDT
-- Website: https://manifest.morrenus.xyz/
-- Total Depots: 3
-- Total DLCs: 0
-- Shared Depots: 2

-- MAIN APPLICATION
addappid(3470610, 1, "16839233a4666084165098e140a42c41087d94b10f2eea05b65a2c0a5dfbc1a2") -- Dawn Break
-- MAIN APP DEPOTS
addappid(3470611, 1, "ef35a45bc08c765df84f3d1e4f82274a19f5399c43464a4914f3fdbd9898b8e2") -- Depot 3470611
setManifestid(3470611, "4066570047835987846", 16719683905)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
