-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3472040
-- Name: NBA 2K26
addappid(3472040) -- NBA 2K26
addappid(3472042,0,"34db1ecbd759eab0b3e63e7304bc8fe901b1ca351a3d453affb865d97c5e62be") -- Depot 1 (3472042_9074774104163492402.manifest)
setManifestid(3472042,"9074774104163492402")
addappid(3472041,0,"98720ddedf5fb5a37faf70ca90602a9949e727a7f7b6b9171ecc2764ee2d3b21") -- Depot 2 (3472041_2148284382507516386.manifest)
setManifestid(3472041,"2148284382507516386")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 3 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 4 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")