-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3474900
-- Name: Anima Engine
-- Updated: March 23, 2026 at 03:26:52 PM UTC
-- AnimaEngine
-- Created: March 18, 2026 at 22:16:03 EDT
-- Website: https://manifest.morrenus.xyz/
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(3474900, 1, "6962e235f2435a469ecb60cd81380e00dc587a5d3bcb7d7090db101661c4990b") -- AnimaEngine
-- MAIN APP DEPOTS
addappid(3474901, 1, "fbc9891a1c20a2a57931cc7ac38cec562cf9fb996f284e99863b13fb98f140d8") -- Depot 3474901
setManifestid(3474901, "1534812974247746624", 3056194189)
-- EMPTY DEPOTS (no content on any branch)
-- addappid(3474902) -- Depot 3474902 (empty depot)
