-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3477300
-- Name: Scope X
addappid(3477300) -- Scope X
addappid(3477301,0,"4d68ce9188c501ebc1df053a10c9bdf69f8912d30a218f65286981b081f80e58") -- Depot 1 (3477301_6778843678973934599.manifest)
setManifestid(3477301,"6778843678973934599")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")