-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3478050
-- Name: Road To Empress
addappid(3478050) -- Road To Empress
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(3478051,0,"b6dfb81926ab11079fe9a9966f287b28e32479c417877c63847d8d422e12aea9") -- Depot 2 (3478051_626939672709548902.manifest)
setManifestid(3478051,"626939672709548902")