-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3483740
-- Name: Cast n Chill
addappid(3483740) -- Cast n Chill
addappid(3483742,0,"3413029df000861faa325cd3547914567f865ffb3c71247b47a8b9d7d57c7f6f") -- Depot 1 (3483742_7715911724658189809.manifest)
setManifestid(3483742,"7715911724658189809")
addappid(3483741,0,"0085e2ab6e91d273c72748b41db876429a43a28e359be3bd5519ddfa4d8ac501") -- Depot 2 (3483741_8849892373387178259.manifest)
setManifestid(3483741,"8849892373387178259")