-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3489700
-- Name: Stellar Blade™
addappid(3489700) -- Stellar Blade™
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(3596190,0,"1e65f8baa259f487dcdc1d3dce1e198dd23c9f7b77236e4e56fcc9f6b915a449") -- Depot 2 (3596190_3119456928663392571.manifest)
setManifestid(3596190,"3119456928663392571")
addappid(3489701,0,"2266ca31f6f2666ebe75906201e72f9398694030ff1c8214aacebcf74dc94ee3") -- Depot 3 (3489701_4947667343661089824.manifest)
setManifestid(3489701,"4947667343661089824")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 4 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(3596180,0,"a55f79607c32a7e24a388464ddc3cfbc91b2dcee6691061bca3fb32d231ccb32") -- Depot 5 (3596180_6319771942931301862.manifest)
setManifestid(3596180,"6319771942931301862")