-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3495730
-- Name: Lucid Blocks
-- Updated: April 8, 2026 at 06:43:25 PM UTC
-- Lucid Blocks
-- Created: March 21, 2026 at 10:40:23 EDT
-- Website: https://manifest.morrenus.xyz/
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(3495730, 1, "5955dac15268e6a6f9bf632060820e9e1fa0758a10abc471fc57fd09dab146b7") -- Lucid Blocks
-- MAIN APP DEPOTS
addappid(3495731, 1, "5787592669080ba4b91a5ca38ff3070ba3d207ec1a61fb65c53110bebe4ec916") -- Depot 3495731
setManifestid(3495731, "620783789656177605", 1029211784)
