-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3496000
-- Name: Ship, Inc.
addappid(3496000) -- Ship, Inc.
addappid(3496001,0,"ab5f7aa3985fbccdb6589b71db8c36547133ecf078cf8935abd0f2964f35f10a") -- Depot 1 (3496001_792387092515986484.manifest)
setManifestid(3496001,"792387092515986484")