-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3516180
-- Name: Don't FOOL ME, Beauties!
addappid(3516180) -- Don't FOOL ME, Beauties!
addappid(3516181,0,"dc747063c492b3c7c598538d95e4a8f61cb724864be1a6eb46e07103bce91942") -- Depot 1 (3516181_983863286284085986.manifest)
setManifestid(3516181,"983863286284085986")