-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3516580
-- Name: Ballshit
addappid(3516580) -- 无基之谈
-- MAIN APP DEPOTS
addappid(3516581, 1, "bccfbee0d6d97df703409b58bfa713164ac8450ba1d5fefd8117531d16a7f1c9") -- Depot 3516581
setManifestid(3516581, "7887809713495066536", 5063732750)