-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3546440
-- Name: Rentlord
addappid(3546440) -- Rentlord
addappid(3546441,0,"f303e6656cf9ab575ee79e1a326af48358d9efb35bf85df55ccf125a2079f491") -- Depot 1 (3546441_319481518625964091.manifest)
setManifestid(3546441,"319481518625964091")