-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3570340
-- Name: 这个CEO我当定了！
addappid(3570340) -- 这个CEO我当定了！
addappid(4039780,0,"42feba6e3551c72cae650a0230e20142d12cb82dcffc50def9b80b2f3754cc69") -- Depot 1 (4039780_5287989820293749103.manifest)
setManifestid(4039780,"5287989820293749103")
addappid(3570341,0,"0daeb13752d79b61c8619efee594bea3e4b923cdba0c490e0e0e91f5a005874e") -- Depot 2 (3570341_5671268887956013914.manifest)
setManifestid(3570341,"5671268887956013914")