-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3586250
-- Name: Empire Game
addappid(3586250) -- Empire Game
addappid(3586251,0,"cd3ac0795fb7457dbb247c4a160b052e397ff42d600d432ff5768f622b1ce71e") -- Depot 1 (3586251_6889919222262314230.manifest)
setManifestid(3586251,"6889919222262314230")