-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3587140
-- Name: Ark Re:Code
addappid(3587140) -- Ark Re:Code
addappid(3587141,0,"5818a2345c0591e29f1a577dbc2662e11bc2e27570a93652463070dd969551ae") -- Depot 1 (3587141_7072547692485384166.manifest)
setManifestid(3587141,"7072547692485384166")