-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3602290
-- Name: FEMBOY FUTA HOUSE
addappid(3602290) -- FEMBOY FUTA HOUSE
addappid(3963390,0,"1d4ff18e36cb5855151cb3e52a33f0717b51a4d7a26d5e72c97de74292263eec") -- Depot 1 (3963390_3275917072001749456.manifest)
setManifestid(3963390,"3275917072001749456")
addappid(3602291,0,"902bbf5f342cf5125a99fb40b231479b9547a9f597d3c915f9c91f72d27b875d") -- Depot 2 (3602291_8932635081948766286.manifest)
setManifestid(3602291,"8932635081948766286")
addappid(3963420,0,"70f8d950f1e77bd927f59391cd61634caf6bfb04632b34c6b0f7ad5341db11c5") -- Depot 3 (3963420_81016670117772740.manifest)
setManifestid(3963420,"81016670117772740")