-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3614980
-- Name: Keytamine
addappid(3614980) -- Keytamine
addappid(3614981,0,"013dfca214b71934b93d877868f720b5faaafd6dcc4852e524fc2d4345411e1a") -- Depot 1 (3614981_8005065928755938485.manifest)
setManifestid(3614981,"8005065928755938485")