-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3616550
-- Name: Car Dealership Simulator 2
addappid(3616550) -- Car Dealership Simulator 2
addappid(3616551,0,"321f51821758384501bec04ad6a82ad3bab317a8de1b00971de7161775883c48") -- Depot 1 (3616551_6943994955126695053.manifest)
setManifestid(3616551,"6943994955126695053")