-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3636960
-- Name: Violent Horror Stories 2
addappid(3636960) -- Violent Horror Stories: Anthology 2
-- MAIN APP DEPOTS
addappid(3636961, 1, "5cdbeb07c6db039a53fe874518f3294034a7ab7489bbbb09c2b5db8164092ddd") -- Depot 3636961
setManifestid(3636961, "3290775475683045441", 4934437595)