-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3655390
-- Name: Alien: Rogue Incursion Evolved Edition
addappid(3655390) -- Alien: Rogue Incursion Evolved Edition
addappid(3655391,0,"4289857b0b55b53b17c6143a6727f746e475c76253e99cff492725e4ad9e3e13") -- Depot 1 (3655391_7853570933328751435.manifest)
setManifestid(3655391,"7853570933328751435")