-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3668560
-- Name: Happy Island Fantasy
addappid(3668560) -- Happy Island Fantasy
addappid(3668561,0,"2fba95b2f05878acc5d5b57f1429cc236645a6aed513ae6d733ed589422235ec") -- Depot 1 (3668561_6944526703509760264.manifest)
setManifestid(3668561,"6944526703509760264")