-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3668370
-- Name: Night Swarm
addappid(3668370) -- Night Swarm
-- MAIN APP DEPOTS
addappid(3668371, 1, "980df52f8f9145bce6710c1de03dd3e91fce5c30ba47bf36ef798b1217b54718") -- Depot 3668371
setManifestid(3668371, "6586233938223058762", 1875200380)