-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3672720
-- Name: Prison Escape Simulator: Dig Out
addappid(3672720) -- Prison Escape Simulator: Dig Out
addappid(3672722,0,"9b3449633eddd535ba0aa2b2b242cbe7f1bbedf545cec40ef03704ea188b19f7") -- Depot 1 (3672722_3646906447751805720.manifest)
setManifestid(3672722,"3646906447751805720")