-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 367520
-- Name: Hollow Knight
addappid(367520) -- Hollow Knight
addappid(367522,0,"c7e67c6bf87d7128302920e88b17cb6ee322e69585472cbcd2a3d913c7d3579a") -- Depot 1 (367522_7770537498842372731.manifest)
setManifestid(367522,"7770537498842372731")
addappid(367523,0,"61dd4c0fd624c81feb31fc22cb61a228c4d8077cf3927e9058f736026d9dd838") -- Depot 2 (367523_5829533265112705522.manifest)
setManifestid(367523,"5829533265112705522")
addappid(367521,0,"de801b9b61e3385b333259cc0f04d2e5d976c4cb8f933cb859d75a4d0125a2a8") -- Depot 3 (367521_4539921744901848404.manifest)
setManifestid(367521,"4539921744901848404")