-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3678970
-- Name: TBH: Task Bar Hero
-- Updated: June 27, 2026 at 03:01:24 PM UTC
-- TBH: Task Bar Hero
-- Created: June 25, 2026 at 05:08:15 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 1
-- Total DLCs: 5

-- MAIN APPLICATION
addappid(3678970, 1, "3babc9b9da2b5ab2409cbd2037432aba399d9c12bedfa41269d1ee4a08d29954") -- TBH: Task Bar Hero
-- MAIN APP DEPOTS
addappid(3678971, 1, "8d0b4ba64ffc2eaa7b8f853cd4ad4e91d7a57d637bcf3f33aba1da9c6d6360f0") -- Depot 3678971
setManifestid(3678971, "4444895913187135859", 586913951)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(4427390) -- TBH  Task Bar Hero - Supporter Pack
addappid(4427400) -- TBH  Task Bar Hero - 3 Stash Pack
addappid(4427410) -- TBH  Task Bar Hero - Priest (Class)
addappid(4427420) -- TBH  Task Bar Hero - Hunter (Class)
addappid(4427430) -- TBH  Task Bar Hero - Slayer (Class)
-- EMPTY DEPOTS (no content on any branch)
-- addappid(3678972) -- Depot 3678972 (empty depot)
