-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3681810
-- Name: Blue Protocol: Star Resonance
addappid(3681810) -- Blue Protocol: Star Resonance
addappid(3681812,0,"93dc364cfd5230c092eea8b1ac3a6146af2f218a3f3ab806b4d9dd33d9d9cfe6") -- Depot 1 (3681812_6731312524786922478.manifest)
setManifestid(3681812,"6731312524786922478")