-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3682050
-- Name: Sickly Days and Summer Traces
addappid(3682050) -- Sickly Days and Summer Traces
addappid(3682051,0,"09652578b46fb04323a0df42c60d7d41225df719e923c430f528530ae6605d61") -- Depot 1 (3682051_75870302050589289.manifest)
setManifestid(3682051,"75870302050589289")