-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3716600
-- Name: Mage Arena
addappid(3716600) -- Mage Arena
addappid(3716601,0,"e310c1b9ef27e0d9ec00ac3593dc3851ee94ffa39699fed48341039f9ec50fc6") -- Depot 1 (3716601_7108582573526134211.manifest)
setManifestid(3716601,"7108582573526134211")