-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3717340
-- Name: Yakuza Kiwami 2
addappid(3717340) -- Yakuza Kiwami 2
-- MAIN APP DEPOTS
addappid(3717341, 1, "bac8c6f1b44d2997e2b9c459087502cf592e59908a5926914b9e2adba8e458b3") -- Depot 3717341
setManifestid(3717341, "6613510286615488986", 64790800610)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)