-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3734680
-- Name: 我只是想让她们都幸福
addappid(3734680) -- 我只是想让她们都幸福
-- MAIN APP DEPOTS
addappid(3734681, 1, "db3993f11c81cb1693119cdbdff4bec080decc4631285484c7a75612905210a1") -- Depot 3734681
setManifestid(3734681, "7103281127002407519", 45701631200)