-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 374320
-- Name: DARK SOULS™ III
addappid(374320) -- DARK SOULS™ III
addappid(374322,0,"2e8b33176e957bf7c6ed4ad3c34847d1eef1ee846e900e1b4a2b4fc3a51b6c09") -- Depot 1 (374322_6130303443397132373.manifest)
setManifestid(374322,"6130303443397132373")
addappid(506970,0,"2dc303f9e1fc1f45f385b5d262b3b481ed10f11d38e5ca44edf7096a4f280385") -- Depot 2 (506970_2441039608905796121.manifest)
setManifestid(506970,"2441039608905796121")
addappid(228984,0,"df7df98d3134f5e0009d5ebcaaf3bbb91ea2f7cbad81a37a9d16bc1835f57068") -- Depot 3 (228984_2547553897526095397.manifest)
setManifestid(228984,"2547553897526095397")
addappid(374321,0,"1e1f904451f44a8549008ac8152430dc18288dd22c8edda058afa86b926a4162") -- Depot 4 (374321_6652575487689169560.manifest)
setManifestid(374321,"6652575487689169560")
addappid(455380,0,"ee1942ee70f7707eb40415a87cd933fedf4de04aeab6f69421e106ff4b8d3228") -- Depot 5 (455380_398045694410355072.manifest)
setManifestid(455380,"398045694410355072")
addappid(506971,0,"0ce07245c46df4c8b1c5d7bef627f59f34b9fde6ea903ec21ea879cf6d9c10d5") -- Depot 6 (506971_266039425715139370.manifest)
setManifestid(506971,"266039425715139370")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 7 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")