-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3751730
-- Name: Loan Shark
addappid(3751730) -- Loan Shark
-- MAIN APP DEPOTS
addappid(3751731, 1, "47cd110d658fbbf8e22df9092734c6639b0a6d395cc9f643b056bcb5663d7e14") -- Depot 3751731
setManifestid(3751731, "7572179441738249952", 895647568)
-- SHARED DEPOTS (from other apps)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)