-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3768760
-- Name: 007 First Light
-- Updated: May 26, 2026 at 03:07:02 PM UTC
-- 007 First Light
-- Created: May 26, 2026 at 10:14:40 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 1
-- Total DLCs: 20

-- MAIN APPLICATION
addappid(3768760) -- 007 First Light
-- MAIN APP DEPOTS
addappid(3768761, 1, "8284c5e8921ec5acbe53f4d45af0260905841dc698ca179dd218ce5a2657ef09") -- Depot 3768761
setManifestid(3768761, "7322178669849310269", 57179326292)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(3950810) -- 007 First Light - Gleaming Earphones (Gadget Skin)
addappid(3950820) -- 007 First Light - Gleaming Lighter (Gadget Skin)
addappid(3950830) -- 007 First Light - Gleaming Pen (Gadget Skin)
addappid(3950850) -- 007 First Light - Gleaming Phone (Gadget Skin)
addappid(3950870) -- 007 First Light - Day of the Dead (Exclusive Outfit)
addappid(3950880) -- 007 First Light - Desert Explorer (Exclusive Outfit)
addappid(3950900) -- 007 First Light - Gentleman Operator (Exclusive Outfit)
addappid(3950910) -- 007 First Light - Silent Anchor (Exclusive Outfit) 
addappid(3950930) -- 007 First Light - Agents Mark (Weapon Skin)
addappid(3954230) -- 007 First Light - Golden Gun (Weapon Skin)
addappid(3954250) -- 007 First Light - Obsidian Suit (Exclusive Outfit)
addappid(3954260) -- 007 First Light - Classic Tuxedo (Exclusive Outfit) 
addappid(4521800) -- 007 First Light - First Class (Outfit)
addappid(4521810) -- 007 First Light - Forest Operative (Exclusive Outfit)
addappid(4521820) -- 007 First Light - Observant Spy (Outfit)
addappid(4521830) -- 007 First Light - Leisure Beam (Outfit)
addappid(4521840) -- 007 First Light - One More (Outfit)
addappid(4601250) -- 007 First Light - Diamond in the Rough (Outfit)
addappid(4626160) -- 007 First Light - Standard
addappid(4707780) -- 007 First Light - 00 Pack
