-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3769130
-- Name: Keep on Mining!
addappid(3769130) -- Keep on Mining!
addappid(3769131,0,"79dda683e39e3551788e59192e005fe2d8b3e5f3f3adecacf712b638a9e732b3") -- Depot 1 (3769131_5850267657624917866.manifest)
setManifestid(3769131,"5850267657624917866")
addappid(3769132,0,"4143d4c98337ddcbaa5a9c74444b143a9204495eca185108b268a76f237de3a6") -- Depot 2 (3769132_1869520104454938729.manifest)
setManifestid(3769132,"1869520104454938729")