-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3772330
-- Name: The Cheated Man's Revenge: Triple the Payback
addappid(3772330) -- The Cheated Man's Revenge: Triple the Payback
addappid(3905720,0,"9be08d1b275c39c5d6a46f5d619722cde96979a5c7f12987847550032308991c") -- Depot 1 (3905720_4727323581832112160.manifest)
setManifestid(3905720,"4727323581832112160")
addappid(3772331,0,"90461f1353f695e524bb9e2d812c7a2faf87c5240a180f8b55d55453a6150f74") -- Depot 2 (3772331_3035554100656800188.manifest)
setManifestid(3772331,"3035554100656800188")