-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3799100
-- Name: SIDE EFFECTS
addappid(3799100) -- Side Effects
-- MAIN APP DEPOTS
addappid(3799101, 1, "cb02a7ff0425aed0f5a9ea9376e2c2f0fb2a59cc14d14b7f23792e63fc6d0aa7") -- Depot 3799101
setManifestid(3799101, "5112222304742848737", 1798924464)