-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3805420
-- Name: A Few Quick Matches
addappid(3805420) -- A Few Quick Matches
addappid(3805421,0,"661c353751235821d956564e091dc84b43b7bc3af698460e04d6d1f0afa1d1b8") -- Depot 1 (3805421_5177103868141753891.manifest)
setManifestid(3805421,"5177103868141753891")