-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3818010
-- Name: BEYBLADE X EVOBATTLE
addappid(3818010) -- BEYBLADE X EVOBATTLE
-- MAIN APP DEPOTS
addappid(3818011, 1, "9e190331a1336edfff4571412d26622426d9895a4bf952d4c2d58470fd4c0780") -- Depot 3818011
setManifestid(3818011, "2612752008201298651", 2439020607)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(4128510) -- BEYBLADE X EVOBATTLE BEY COATING PATTERN  COLOR EXPANSION KIT
addappid(4128520) -- BEYBLADE X EVOBATTLE PART DROP 1 EXPANSION KIT
addappid(4128530) -- BEYBLADE X EVOBATTLE BEY COATING ITEM SET
addappid(4128540) -- BEYBLADE X EVOBATTLE XP  PRIZE MONEY BOOST KIT
addappid(4128550) -- BEYBLADE X EVOBATTLE BEY COATING SHOP EXPANSION KIT
addappid(4128560) -- BEYBLADE X EVOBATTLE DIGITAL BEYBOOSTER VOL.1
addappid(4139560) -- BEYBLADE X EVOBATTLE SEASON PASS