-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3821790
-- Name: Ys X: Proud Nordics
addappid(3821790) -- Ys X: Proud Nordics
addappid(3821791,0,"d191b0d664394bde5b875d94a7f2ea4a22d780e75b63a937d545bfad41d5702b") -- Depot 1 (3821791_7488167034441921374.manifest)
setManifestid(3821791,"7488167034441921374")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")