-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3837340
-- Name: FINAL FANTASY VII
addappid(3837340, 1, "f5b21f9ee6746920e2c74f32540b47103d1d4bc014415c81d68b181da5c7ea19") -- FINAL FANTASY VII
-- MAIN APP DEPOTS
addappid(3837341, 1, "3ea06167542e29078d0c64619d751c660286befe998d8bd1a1900fb72da09a25") -- Depot 3837341
setManifestid(3837341, "5022990313627134241", 3685520584)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
addappid(229007, 1, "eba9fa9ff4f811929c119074450f49f739113bcae9317ded9bea262aa21ec58d") -- .NET 4.8 Redist (Shared from App 228980)
setManifestid(229007, "4477590687906973371", 117381405)