-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3838290
-- Name: Refate: Echoes of Desire
addappid(3838290) -- Refate: Echoes of Desire
-- MAIN APP DEPOTS
addappid(3838291, 1, "19995f0429ceb14f5fc97f37732075399c7b74b19372a907fc2f525200c28110") -- Depot 3838291
setManifestid(3838291, "644196851234817297", 247977081)
addappid(3838292, 1, "29b92ea9e7920d2300190fa256d31a65403c537157d2d425ebc040038d5bb1c2") -- Depot 3838292
setManifestid(3838292, "4854273442003336074", 2508010919)
addappid(3838293, 1, "1d714385cb8dbf2bc09a6db07f2bc421a91efa061186af27924cf417c393c514") -- Depot 3838293
setManifestid(3838293, "6697035223332017428", 6843438)
addappid(3838294, 1, "88e8862b97ce5bafc437d9d40fce5e1e9803202bb7947e43d5b9004a1fa9dfbe") -- Depot 3838294
setManifestid(3838294, "4743512430883479420", 56678446576)