-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3869680
-- Name: Silent Still 2
addappid(3869680) -- Silent Still 2
addappid(3869681,0,"9ddce3458ea9f0dab580448841013dfb9d668d0424934a492bed2f8abbbafd86") -- Depot 1 (3869681_7765696579076621838.manifest)
setManifestid(3869681,"7765696579076621838")