-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3898750
-- Name: VoxMagic - Realtime Voice Changer
addappid(3898750) -- VoxMagic - Realtime Voice Changer
addappid(3898751,0,"2c14597c30fc36b7f0e8c0d1c6429b2873d3e594ecd538609bb4dfaf081ba849") -- Depot 1 (3898751_2688028011082383496.manifest)
setManifestid(3898751,"2688028011082383496")