-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3920610
-- Name: FATAL FRAME II: Crimson Butterfly REMAKE
-- Updated: March 12, 2026 at 11:58:17 AM UTC
-- FATAL FRAME II: Crimson Butterfly REMAKE
-- Created: March 11, 2026 at 22:15:42 EDT
-- Website: https://manifest.morrenus.xyz/
-- Total Depots: 3
-- Total DLCs: 5
-- Shared Depots: 1

-- MAIN APPLICATION
addappid(3920610, 1, "8c9b8ce81e2921eea49b102eed1821aa883ad85645ff92115830bb24cbfa0bfc") -- FATAL FRAME II: Crimson Butterfly REMAKE
-- MAIN APP DEPOTS
addappid(3920611, 1, "12bffaedca2f7ee446211ba60b97b8262a19e282d803fde20b020cdd0d8ab780") -- Depot 3920611
setManifestid(3920611, "7183038213745299682", 37447999995)
-- SHARED DEPOTS (from other apps)
addappid(228988, 1, "1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- VC 2019 Redist (Shared from App 228980)
setManifestid(228988, "6645201662696499616", 29212173)
-- DLCS WITH DEDICATED DEPOTS
-- FATAL FRAME II Crimson Butterfly REMAKE Digital Art Book  Digital Soundtrack (AppID: 4123380)
addappid(4123380)
addappid(4123380, 1, "373ac671ea014e7cf29c347bbb4f27efa8fb93238f339504fa412757e9bd6b0a") -- FATAL FRAME II Crimson Butterfly REMAKE Digital Art Book  Digital Soundtrack - Depot 4123380
setManifestid(4123380, "5477310769368099630", 1930386333)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(4122450) -- FATAL FRAME II Crimson Butterfly REMAKE Pre-Order Bonus Set
addappid(4123350) -- FATAL FRAME II Crimson Butterfly REMAKE Early Purchase Bonus Set
addappid(4123360) -- FATAL FRAME II Crimson Butterfly REMAKE Digital Deluxe Bonus Set
addappid(4123370) -- FATAL FRAME II Crimson Butterfly REMAKE Digital Deluxe Upgrade
