-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3928720
-- Name: Hollow Knight: Silksong - Official Soundtrack
addappid(3928720) -- Hollow Knight: Silksong - Official Soundtrack
addappid(3928721,0,"9e8285f4b529ce55e85dfefe797a57d8e186415988dbed1ee0a18b1901285d63") -- Depot 1 (3928721_7748525586300936826.manifest)
setManifestid(3928721,"7748525586300936826")
addappid(3928722,0,"f4101b8f87779f16d1030a016a0c579b5f031202ef788788e32b2f0be4d77721") -- Depot 2 (3928722_5502287679669921147.manifest)
setManifestid(3928722,"5502287679669921147")