-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3929740
-- Name: Tom Clancy's Splinter Cell: Pandora Tomorrow
addappid(3929740) -- Tom Clancy's Splinter Cell: Pandora Tomorrow
addappid(1716751,0,"84780b728a23b1dabbe8b064807ccd3dbd40c67139ed569101104a418c581675") -- Depot 1 (1716751_818295193716041715.manifest)
setManifestid(1716751,"818295193716041715")
addappid(3929744,0,"b8138faa0fbf89fe1ff1d717986d305b462dca6d2e0f69eecbf41cbf4b11e3ed") -- Depot 2 (3929744_1436522670055839786.manifest)
setManifestid(3929744,"1436522670055839786")
addappid(3929742,0,"2892178fb39e7761dc3e49ac7d3bb6f7bc0f8309ca2543aaf578f7de29cfb95e") -- Depot 3 (3929742_6915546572832318699.manifest)
setManifestid(3929742,"6915546572832318699")
addappid(3929743,0,"7b7c06a30aedb97951ba922fa00ee3ad58c6a03a15608b0c058a80fb1d52b778") -- Depot 4 (3929743_8284373307380388717.manifest)
setManifestid(3929743,"8284373307380388717")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 5 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(3929746,0,"db711b7327d3da24fef76d194f8843f7b01359a552d1378e6fa018b234c8bc05") -- Depot 6 (3929746_521831151215040465.manifest)
setManifestid(3929746,"521831151215040465")
addappid(3929745,0,"eff0a6451e562e1e47889ea7a32209e4a2dfc91b959097b3b62ff544af8e49a9") -- Depot 7 (3929745_5230515676687236275.manifest)
setManifestid(3929745,"5230515676687236275")
addappid(3929741,0,"b2c87c8501ea6789d1e9e8a0f45da5cacdd90b685f0da3d710485e82945d1b57") -- Depot 8 (3929741_3127817338763076110.manifest)
setManifestid(3929741,"3127817338763076110")