-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 394510
-- Name: HELLDIVERS™ Dive Harder Edition
addappid(394510) -- HELLDIVERS™ Dive Harder Edition
addappid(394511,0,"9354a50886239c53583780315103fac2c9ca6d9e6c4b80ec921a1b49c653e51a") -- Depot 1 (394511_9144075105577600930.manifest)
setManifestid(394511,"9144075105577600930")
addappid(229031,0,"98d01f1eaa90ae08f978994e043bcbbf1f23fc72a325528ca7d722c827c0eb54") -- Depot 2 (229031_7746630274301172884.manifest)
setManifestid(229031,"7746630274301172884")
addappid(394513,0,"1760bb243e446b5591684d821d4bfd318c8ba76d0af39f454786e7bfe01f3e9f") -- Depot 3 (394513_2709807232204005293.manifest)
setManifestid(394513,"2709807232204005293")
addappid(394512,0,"1094ae83b6e8a79e54aa77393680801204d7ab74e4556a08b6ced06933afdb68") -- Depot 4 (394512_5350944372617472127.manifest)
setManifestid(394512,"5350944372617472127")
addappid(228983,0,"77c8e812cd79e67e2d376721253ebb07e06b3646f05671c6c9517b27be14734b") -- Depot 5 (228983_8124929965194586177.manifest)
setManifestid(228983,"8124929965194586177")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 6 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")