-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3994370
-- Name: Five Hearts Under One Roof season2 - Soundtrack
addappid(3994370) -- Five Hearts Under One Roof season2 - Soundtrack
-- MAIN APP DEPOTS
addappid(3994371, 1, "9af044152f1ae5a909b05c146587e84a822ddfd19acda6264359eee283e0a810") -- Depot 3994371
setManifestid(3994371, "7584353851468313637", 1012764495)