-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3998800
-- Name: 恋爱吗？我家猫会后空翻
addappid(3998800) -- 恋爱吗？我家猫会后空翻
-- MAIN APP DEPOTS
addappid(3998801, 1, "f338475c0e275d289d04ec416d7ab6b6c5127619d5ceae3022bdeef6eef2a2bb") -- Depot 3998801
setManifestid(3998801, "8174234817653325475", 21765173467)