-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 4106150
-- Name: Detective Bass in Fish out of Water
addappid(4106150) -- Detective Bass 1: Fish out of Water
-- MAIN APP DEPOTS
addappid(4106151, 1, "ad37b807989ed91e0ce35904007baf739b788357f344b469928bf62ae638965c") -- Depot 4106151
setManifestid(4106151, "3514532226432032647", 100330783)
-- EMPTY DEPOTS (no content on any branch)
-- addappid(4106152) -- Depot 4106152 (empty depot)
-- addappid(4106153) -- Depot 4106153 (empty depot)