-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 414340
-- Name: Hellblade: Senua's Sacrifice
addappid(414340) -- Hellblade: Senua's Sacrifice
addappid(228986,0,"51dd3611d28621644730736f3bb1fd6b960053a45cd79123f2b9a80c9181dad5") -- Depot 1 (228986_8782296191957114623.manifest)
setManifestid(228986,"8782296191957114623")
addappid(862810,0,"bff67576eb180db1b53bb154652065393cbe27c50260b9869fce553e3fb9505e") -- Depot 2 (862810_1889844123931411647.manifest)
setManifestid(862810,"1889844123931411647")
addappid(862811,0,"b08bbe19b22d576f34ce8fe6f961d4684a04bac9026a61cea8922a53397eb1fe") -- Depot 3 (862811_645980760732735123.manifest)
setManifestid(862811,"645980760732735123")
addappid(228984,0,"df7df98d3134f5e0009d5ebcaaf3bbb91ea2f7cbad81a37a9d16bc1835f57068") -- Depot 4 (228984_2547553897526095397.manifest)
setManifestid(228984,"2547553897526095397")
addappid(626750,0,"da8b16e5fa6895ec08a5589fd5b68f1adfe6f1f24c7120e06dc2fdcda3219b4a") -- Depot 5 (626750_7617494232712978521.manifest)
setManifestid(626750,"7617494232712978521")
addappid(414341,0,"b52b49b1aa5b2931a20af4d509e604d4e96a00895d7e75bf04acaffa573ebe09") -- Depot 6 (414341_3390494925423867663.manifest)
setManifestid(414341,"3390494925423867663")
addappid(228985,0,"21a2f639584d9bd462c5c4b3e10f881cba8a17ae674c830c4f083551cd356e9c") -- Depot 7 (228985_3966345552745568756.manifest)
setManifestid(228985,"3966345552745568756")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 8 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")