-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 424840
-- Name: Little Nightmares
addappid(424840) -- Little Nightmares
addappid(228986,0,"51dd3611d28621644730736f3bb1fd6b960053a45cd79123f2b9a80c9181dad5") -- Depot 1 (228986_8782296191957114623.manifest)
setManifestid(228986,"8782296191957114623")
addappid(424841,0,"1823f166b7f7161144cc3fb35ba96c0c8526183cf77e66127c44b152c1fcad7e") -- Depot 2 (424841_4926539991083375660.manifest)
setManifestid(424841,"4926539991083375660")
addappid(601710,0,"6ef5cd05ac17d226a1897c8bd1cee696e7ecd67372f84f357a61b1df8aa69949") -- Depot 3 (601710_3933483467920670021.manifest)
setManifestid(601710,"3933483467920670021")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 4 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")