-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 4249100
-- Name: Resident Evil (1996)
-- Updated: April 2, 2026 at 11:23:01 AM UTC
-- Resident Evil (1996)
-- Created: April 01, 2026 at 23:01:30 EDT
-- Website: https://manifest.morrenus.xyz/
-- Total Depots: 3
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(4249100) -- Resident Evil (1996)
-- MAIN APP DEPOTS
addappid(4249101, 1, "53fc73ab0ec4b9e6fa4c415e4613c5bdc044ae2462c6c4d898c070822af245e0") -- Depot 4249101
setManifestid(4249101, "2720404463246186191", 1639063)
addappid(4249102, 1, "cb84cbcb9b6a7d9781651ff812f235d78189a6b8603a6a8d55e23029b727b5d6") -- Depot 4249102
setManifestid(4249102, "4977007747338078760", 12834432)
addappid(4249103, 1, "f118404bcd07c1213340ef0763197e9fcbce44aaeb046f5c467ffae95d585f20") -- Depot 4249103
setManifestid(4249103, "5764709108843764437", 2477714791)
