-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 4249110
-- Name: Resident Evil 2 (1998)
-- Updated: April 2, 2026 at 11:23:09 AM UTC
-- Resident Evil 2 (1998)
-- Created: April 01, 2026 at 23:00:08 EDT
-- Website: https://manifest.morrenus.xyz/
-- Total Depots: 3
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(4249110) -- Resident Evil 2 (1998)
-- MAIN APP DEPOTS
addappid(4249111, 1, "7e6d6cb1a6e136160805cc707943680e3b949fcd4614a89874f8f9005c22f69f") -- Depot 4249111
setManifestid(4249111, "4162242548040861635", 1612083)
addappid(4249112, 1, "f311e48330d6eb5320456deb32ff0dfc4afa77462ab3ef4f03c712976fd27013") -- Depot 4249112
setManifestid(4249112, "2015999630805652938", 39668096)
addappid(4249113, 1, "4e7a4a237210d1cd940175c55d7e47eed5cd69489edafba115a6477d2f15123b") -- Depot 4249113
setManifestid(4249113, "733389168188405052", 5646161564)
