-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 4249120
-- Name: Resident Evil 3 Nemesis (1999)
-- Updated: April 2, 2026 at 11:23:16 AM UTC
-- Resident Evil 3 Nemesis (1999)
-- Created: April 01, 2026 at 22:58:51 EDT
-- Website: https://manifest.morrenus.xyz/
-- Total Depots: 3
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(4249120) -- Resident Evil 3 Nemesis (1999)
-- MAIN APP DEPOTS
addappid(4249121, 1, "0a6f8590bf8328fa294f7102f3c7b6626d7b2acb1beb253984d33ebda81c71ac") -- Depot 4249121
setManifestid(4249121, "4813242977047693292", 1947258)
addappid(4249122, 1, "cf2be876833b58ed52ee5433bad25567cf3653cdbed97cba7a25587722d05894") -- Depot 4249122
setManifestid(4249122, "6812386929732299454", 40063872)
addappid(4249123, 1, "75355fe03a0ccb5b3cb8ed4db1ff846465f8b773738d1211e59e0ecdd39ef1a9") -- Depot 4249123
setManifestid(4249123, "7773311513018434435", 2650137648)
