-- Generated by SteamRiser
-- App ID: 431960
-- App Name: Wallpaper Engine
-- Generated at: 09/14/2025, 10:36:46 AM UTC
-- Total Depots: 2
-- Total DLCs: 1

-- MAIN APPLICATION
addappid(431960, 1, "db983bc58a8cb46d89d1d70cc962cc733956e6124c4025a0c932f82b3c37144a") --Wallpaper Engine
addappid(431961, 1, "62ac71786b9fbeecc473fccb8a14da04ea676371addd8820638ee6cddac8c344")
addappid(431966, 1, "3217352ccc45b8943d6af58c14d359a38f2897bcf4d2f7f7eb117f79f1887fc4")

-- DLCS WITHOUT DEDICATED DEPOTS
addappid(1790230) -- Wallpaper Engine - Editor Extensions

-- End of generated file