-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 459820
-- Name: Crush Crush
addappid(459820) -- Crush Crush
addappid(948683,0,"4aa195ea1741c34b8959f5623de844a063b5dfad2fdaa615438c5c44ccaa900f") -- Depot 1 (948683_6113504142127697334.manifest)
setManifestid(948683,"6113504142127697334")
addappid(459823,0,"f937c6c3585fef083d295ad35234e588cc1fc94cfecf1f5b5db510af7cd24516") -- Depot 2 (459823_596904206056821189.manifest)
setManifestid(459823,"596904206056821189")
addappid(459821,0,"aa604fcda9432e9771859c3e86da68938ee4ea9fe1ecef2756ecfa4b6a29e965") -- Depot 3 (459821_4854415202116555257.manifest)
setManifestid(459821,"4854415202116555257")
addappid(459822,0,"d6c6b792d89f44bf67940e24fd6fe4a380d469b022308bb03732ca3868f9cd36") -- Depot 4 (459822_867942555948033393.manifest)
setManifestid(459822,"867942555948033393")