-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 460790
-- Name: Bayonetta
addappid(460790) -- Bayonetta
addappid(460792,0,"e80066b74e53039c621ea6adf902751eb8f1dac4ca0d402199191086cf6302b7") -- Depot 1 (460792_3254100067932476528.manifest)
setManifestid(460792,"3254100067932476528")
addappid(460793,0,"cdea589ed071f14e0e3888afa183b8571b885073ac2994fad89e6830f5371cc8") -- Depot 2 (460793_2560085780250407658.manifest)
setManifestid(460793,"2560085780250407658")
addappid(228983,0,"77c8e812cd79e67e2d376721253ebb07e06b3646f05671c6c9517b27be14734b") -- Depot 3 (228983_8124929965194586177.manifest)
setManifestid(228983,"8124929965194586177")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 4 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")