-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 477160
-- Name: Human Fall Flat
addappid(477160) -- Human Fall Flat
addappid(477165,0,"91b02c0aecb8688c5844032fe30518f25ac754a1b32ca68c91a6021623d06ebd") -- Depot 1 (477165_6608739560476678045.manifest)
setManifestid(477165,"6608739560476678045")
addappid(477163,0,"48a9d63f348dcd848df0af0fe2eb01efddbb549c03d113bfca9d88015d8b6b7d") -- Depot 2 (477163_129240740414445083.manifest)
setManifestid(477163,"129240740414445083")
addappid(477162,0,"3e1b0a746178eda39e69d130aac41e225a61f7777ccd8907b3b81f02918242ac") -- Depot 3 (477162_5300550487073905687.manifest)
setManifestid(477162,"5300550487073905687")
addappid(632870,0,"292790c00ead9bdc3e2da82f59687f73b21c059eb0e98e3d6d55a9218b594ae9") -- Depot 4 (632870_6110178810839816362.manifest)
setManifestid(632870,"6110178810839816362")
addappid(477161,0,"8bc8773aa491fcab031c973d15bae81a5139cd9d28bdbe82776e9f39dba071d1") -- Depot 5 (477161_5198947667152828315.manifest)
setManifestid(477161,"5198947667152828315")
addappid(477166,0,"3efd94cbca4e47344be62115da0240c6b360356e1634b47f47dbbd82b4de329d") -- Depot 6 (477166_2111907740247976469.manifest)
setManifestid(477166,"2111907740247976469")
addappid(477164,0,"d05522bd5e3f6e7f6bc455253be55a9d3057b94b95da110d6365a246121a5fdc") -- Depot 7 (477164_7169187079178194878.manifest)
setManifestid(477164,"7169187079178194878")