-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 489830
-- Name: The Elder Scrolls V: Skyrim Special Edition
addappid(489830) -- The Elder Scrolls V: Skyrim Special Edition
addappid(228986,0,"51dd3611d28621644730736f3bb1fd6b960053a45cd79123f2b9a80c9181dad5") -- Depot 1 (228986_8782296191957114623.manifest)
setManifestid(228986,"8782296191957114623")
addappid(489832,0,"c6c5e29627073060ccf9fc8c6c9c7ec86dfdf16b51b3d1fbb0a2e7c1ad9f533e") -- Depot 2 (489832_8042843504692938467.manifest)
setManifestid(489832,"8042843504692938467")
addappid(544861,0,"586061c4ba80f7bf1fcf1da170aeffeacdc20869d4d5d622e69c935f42c26630") -- Depot 3 (544861_3494476046078906882.manifest)
setManifestid(544861,"3494476046078906882")
addappid(544860,0,"b0cdbf6da886a9083687985cffde7be07f2183afe615b10af508ff8ded2f8408") -- Depot 4 (544860_8476536650815851202.manifest)
setManifestid(544860,"8476536650815851202")
addappid(489835,0,"ed764444d4ab7b8d2f98100ddd951659a57f5df3c8825b2d14df99f8ab1b6447") -- Depot 5 (489835_9152699258833967999.manifest)
setManifestid(489835,"9152699258833967999")
addappid(489834,0,"eeb89a10bdac7b9b83b6d03cffd9c6225d9041a8130ea52ff0f96b7f6174e857") -- Depot 6 (489834_8562891139598763344.manifest)
setManifestid(489834,"8562891139598763344")
addappid(489836,0,"1ebc81b82a20b369c9c0335ed96a206b81b46846f2dc9a9f457e748d1ec48045") -- Depot 7 (489836_2360664012913025776.manifest)
setManifestid(489836,"2360664012913025776")
addappid(489833,0,"7c5e75890b4f59b4be2d3b68c88abad8b23b159a23bf25a00c5c3a4748752f36") -- Depot 8 (489833_1914580699073641964.manifest)
setManifestid(489833,"1914580699073641964")
addappid(489831,0,"a26da9ff1f2af2345ebfad1bd62bcb9ed1cbe6afcf4ced92d1a5fa944242b825") -- Depot 9 (489831_8442952117333549665.manifest)
setManifestid(489831,"8442952117333549665")
addappid(489837,0,"b2cf2cc8cadda88f33e707b79fb2b95b458553a6d768f7d1ab9ef657a18fa90c") -- Depot 10 (489837_8402094395440824039.manifest)
setManifestid(489837,"8402094395440824039")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 11 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(489838,0,"807c9db0782a0d03abbe9f123179b7428bb952dcb3c127abcb0455d65d772cdd") -- Depot 12 (489838_3873588632592923754.manifest)
setManifestid(489838,"3873588632592923754")
addappid(489839,0,"19028a477ba63d9a671eed7c6590e607370062aa3bf59446cc8b79022ab64de4") -- Depot 13 (489839_176511637554234126.manifest)
setManifestid(489839,"176511637554234126")