-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 491950
-- Name: Orwell: Keeping an Eye On You
addappid(491950) -- Orwell: Keeping an Eye On You
addappid(548850,0,"df9a1e3ddfe75927bda92d89818c41e87a26b6c01bcaaf6d6b930c6f13bbc530") -- Depot 1 (548850_6992446084312528488.manifest)
setManifestid(548850,"6992446084312528488")
addappid(548851,0,"e79c9606cc0b4fd84fc71518e528b468f0a5bf2ca955da07591a8a59f38b4642") -- Depot 2 (548851_4115719002154255368.manifest)
setManifestid(548851,"4115719002154255368")
addappid(491952,0,"3bd3e4d55278317a2e43905a165d9de014c0ce02ef6c0b463e1c834e7fc30673") -- Depot 3 (491952_4319983326930373322.manifest)
setManifestid(491952,"4319983326930373322")
addappid(491953,0,"7d3317a7e9583f049f2f4859acb565494534bc06bca4e206330dfe428d2a9de5") -- Depot 4 (491953_7283384054458950997.manifest)
setManifestid(491953,"7283384054458950997")
addappid(491951,0,"1f4ab188d37923aebe9f69765dddc56457cea51d81c4800676217680819900a3") -- Depot 5 (491951_6274470743431172946.manifest)
setManifestid(491951,"6274470743431172946")