-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 502280
-- Name: BERSERK and the Band of the Hawk
addappid(502280) -- BERSERK and the Band of the Hawk
addappid(228984,0,"df7df98d3134f5e0009d5ebcaaf3bbb91ea2f7cbad81a37a9d16bc1835f57068") -- Depot 1 (228984_2547553897526095397.manifest)
setManifestid(228984,"2547553897526095397")
addappid(569717,0,"120c2bb01b8a56f77b90e7306dad60454ae40482df36ded1c48086c3a411a6f5") -- Depot 2 (569717_1385187758477014680.manifest)
setManifestid(569717,"1385187758477014680")
addappid(569715,0,"d66b4ff26df4867771d389fc230b17d44fffb2a32d0256c50933a12cf5cdf92d") -- Depot 3 (569715_3996257644969501452.manifest)
setManifestid(569715,"3996257644969501452")
addappid(502281,0,"c7a22d692a5d4cf67b291b69245e19fe8e39d821a8447befde2e09f5c4a45503") -- Depot 4 (502281_9116490460199664248.manifest)
setManifestid(502281,"9116490460199664248")
addappid(569714,0,"8658ea8e34a7bcb854206153c2ddb93d63a57e8ae430b638475a707d52116f45") -- Depot 5 (569714_6114895084025994994.manifest)
setManifestid(569714,"6114895084025994994")
addappid(569712,0,"df483f2d6915c598126d60e40b303bbbd2228ebb84692a98335c9a4fa689ad6c") -- Depot 6 (569712_3492610512007693450.manifest)
setManifestid(569712,"3492610512007693450")
addappid(569710,0,"9347f1b7bcd6f854feb5d9cb4aea70cd058d9bea4f477f2f244578f70f618d5b") -- Depot 7 (569710_7209012737251640963.manifest)
setManifestid(569710,"7209012737251640963")
addappid(569716,0,"fb8f10cc60c3d670a5a72f3ca57b83903955610493fd28a27f036e678c881ff1") -- Depot 8 (569716_4981964324360954197.manifest)
setManifestid(569716,"4981964324360954197")
addappid(569713,0,"438971a6e6fdbed01b6f3eecd5dbe76ff701f80e14cbcfa3874eea57ba42fa8e") -- Depot 9 (569713_8394322771459551699.manifest)
setManifestid(569713,"8394322771459551699")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 10 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(569711,0,"2ed9308e6f152a3de13993abbc36f5490dac478341e0c62ad6ef983872c2c30a") -- Depot 11 (569711_6469517900105054797.manifest)
setManifestid(569711,"6469517900105054797")