-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 516750
-- Name: My Summer Car
addappid(516750) -- My Summer Car
addappid(228986,0,"51dd3611d28621644730736f3bb1fd6b960053a45cd79123f2b9a80c9181dad5") -- Depot 1 (228986_8782296191957114623.manifest)
setManifestid(228986,"8782296191957114623")
addappid(516751,0,"47b5c22aa9f52cb8b5d2fe2d9db70ed709bbc88a4ba4cf24bfab8f594141ff72") -- Depot 2 (516751_288061881745926019.manifest)
setManifestid(516751,"288061881745926019")