-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 518920
-- Name: Surgeon Simulator: Experience Reality
addappid(518920) -- Surgeon Simulator: Experience Reality
addappid(518921,0,"e7a6b03ece938c3fdca226ba4d7182f859e16ac17d0fd3a2dcecdae1d344accd") -- Depot 1 (518921_4986426083555691536.manifest)
setManifestid(518921,"4986426083555691536")