-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 524220
-- Name: NieR:Automata™
addappid(524220) -- NieR:Automata™
addappid(524221,0,"710eaf838fca522739fd6f0741fc539dbfb3e69df0bca4f0daed6d9789cac571") -- Depot 1 (524221_4633942970953135000.manifest)
setManifestid(524221,"4633942970953135000")
addappid(580610,0,"b6542835e2fd44948c08a553cab57020dce3620f6677ff161f908160be1de0dd") -- Depot 2 (580610_70539499618618565.manifest)
setManifestid(580610,"70539499618618565")
addappid(580600,0,"67169947379fca33e6a1fd52fd5d4c6f45234151a71bfd9f5e6cda8bdcfab349") -- Depot 3 (580600_6352626735786606959.manifest)
setManifestid(580600,"6352626735786606959")
addappid(583993,0,"8feaf96bd01fb95f5a288544933692972ad398cf76355a6589a6c85475f7cc95") -- Depot 4 (583993_3440919711813183915.manifest)
setManifestid(583993,"3440919711813183915")
addappid(583990,0,"cfe4dbbe0d5622ff101a177b2bd7e089e1fb1afd241cda936d0fc3ac7d4010d1") -- Depot 5 (583990_7857600567806192582.manifest)
setManifestid(583990,"7857600567806192582")
addappid(583994,0,"8b754108a01dcdb855841b04bdac5882b22d07844e6d364adbe5efd46d8ecdaa") -- Depot 6 (583994_6837545457254028528.manifest)
setManifestid(583994,"6837545457254028528")
addappid(1017430,0,"3f639279ce3e6f19d6e4093f0af4032334e31a0e1203288a5da6419f82d04720") -- Depot 7 (1017430_1820157406263693639.manifest)
setManifestid(1017430,"1820157406263693639")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 8 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(583991,0,"6d4ffe017d1c3b9a876f16684204feb1f303a3b6f8327a8cd5246c74799587f0") -- Depot 9 (583991_7822405453448242645.manifest)
setManifestid(583991,"7822405453448242645")
addappid(583992,0,"8f903ba92f0e6eb40ae27b57eb1a1ba3672599687013ec0a1685bffb8cf78a93") -- Depot 10 (583992_7955785643780797608.manifest)
setManifestid(583992,"7955785643780797608")