-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 561110
-- Name: Disney's The Jungle Book
addappid(561110) -- Disney's The Jungle Book
addappid(561111,0,"695916d590eb9af7b82cb3cbbceb7e0c1a365c3523ce5627cb7f1c8a1cb0ad34") -- Depot 1 (561111_6117234513599915015.manifest)
setManifestid(561111,"6117234513599915015")
addappid(561114,0,"a1f584202e5a64d1c04d14d611c85db6eb1fe9376ec41099c3f742c3d27f7265") -- Depot 2 (561114_7063676451616220501.manifest)
setManifestid(561114,"7063676451616220501")
addappid(561113,0,"5c4affcc2731f0f4c121ff32727d2a3ca1b8b58c67505fc5b8d68c0e773c1a76") -- Depot 3 (561113_382283441170717880.manifest)
setManifestid(561113,"382283441170717880")
addappid(561112,0,"2a437d8bdb258acff4c1ae82ee47b1b63ae69705afad0fb949b4495cc146a4d7") -- Depot 4 (561112_6520898589426183996.manifest)
setManifestid(561112,"6520898589426183996")