-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 561120
-- Name: Disney's The Lion King
addappid(561120) -- Disney's The Lion King
addappid(561122,0,"38e0ff889c9fb9ec98005695cf1c14219e885d804085e7368b4d98d1310af70c") -- Depot 1 (561122_9212138230596472026.manifest)
setManifestid(561122,"9212138230596472026")
addappid(561124,0,"fc1da0a3efb29fdc23ea74a2307ddd1e035a92beede216e5728ff48adae14607") -- Depot 2 (561124_4855274820979788558.manifest)
setManifestid(561124,"4855274820979788558")
addappid(561123,0,"89cb23a0aafa672fbdc114dcaf0be955150e0fae70d051e3904d85940d0d9444") -- Depot 3 (561123_6105484736900577622.manifest)
setManifestid(561123,"6105484736900577622")
addappid(561121,0,"0f2ec9bedd712b3b726e518d01bfac39a4a9799ecdcd74642f47fd1608e9cf80") -- Depot 4 (561121_6371702333941617964.manifest)
setManifestid(561121,"6371702333941617964")