-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 582010
-- Name: Monster Hunter: World
addappid(582010) -- Monster Hunter: World
addappid(582011,0,"da6b97dc25e43b8f7ceaf9bcdbfba960f2e3e855b855fc47975d58a68d3f7688") -- Depot 1 (582011_2525674006025364114.manifest)
setManifestid(582011,"2525674006025364114")
addappid(582012,0,"92d06583c95939873c5c33658cd8b1111fa209a4c7576207565e942fa78eb888") -- Depot 2 (582012_5526886592091189537.manifest)
setManifestid(582012,"5526886592091189537")