-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 587620
-- Name: Okami HD
addappid(587620) -- Okami HD
addappid(587623,0,"959eb7d1aa7418826034feb7e0fe4081f67974c4d0121cf9a451742fe660c3d4") -- Depot 1 (587623_71373641097201029.manifest)
setManifestid(587623,"71373641097201029")
addappid(587621,0,"dbef9c5a131af356bcee9780519c447ff2fcf3b38399004c4aa76bd0eb85adec") -- Depot 2 (587621_239798342841480155.manifest)
setManifestid(587621,"239798342841480155")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 3 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")