-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 631510
-- Name: Devil May Cry HD Collection
addappid(631510) -- Devil May Cry HD Collection
addappid(228986,0,"51dd3611d28621644730736f3bb1fd6b960053a45cd79123f2b9a80c9181dad5") -- Depot 1 (228986_8782296191957114623.manifest)
setManifestid(228986,"8782296191957114623")
addappid(631511,0,"79183f987f646ce0abe58d2a413285f83e8bc0d045c01864d28e30bb6ee37ae2") -- Depot 2 (631511_7018858071300627307.manifest)
setManifestid(631511,"7018858071300627307")
addappid(811840,0,"16b5d8916c93e2e48652438e21a29ca27db96cdf30f095c95d0ee9eec24cf34b") -- Depot 3 (811840_1956669955052522073.manifest)
setManifestid(811840,"1956669955052522073")