-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 644560
-- Name: Mirror
addappid(644560) -- Mirror
addappid(1120620,0,"bb39a13c2a98196821cb1925a59dce3b1f3edd8871c59c78d4bfd24d2a6f7c34") -- Depot 1 (1120620_8711778131516758362.manifest)
setManifestid(1120620,"8711778131516758362")
addappid(1120630,0,"6fcb676bfbd4a3b37100ff977e0f78d23aefc9f32d7efcd4836ec8b4d414d75d") -- Depot 2 (1120630_5362505210744167703.manifest)
setManifestid(1120630,"5362505210744167703")
addappid(644562,0,"5d8788750bae639da3bb9531f0928e03197c98f2a95428b7566cebb7216f10a7") -- Depot 3 (644562_4062378658438999991.manifest)
setManifestid(644562,"4062378658438999991")
addappid(774041,0,"cd8a3ed12833b6885c275448874e38aec7724cea4b0340029f016f24c9a00ec4") -- Depot 4 (774041_9021555567850477121.manifest)
setManifestid(774041,"9021555567850477121")
addappid(1011900,0,"c7eb9fee21ee5c880a5524df140aea09fe1f393707aa34621b90577911a0e5b2") -- Depot 5 (1011900_5876040460803207388.manifest)
setManifestid(1011900,"5876040460803207388")
addappid(844190,0,"f257601f2c5e8ed1c6d813a198978f280456613cfcb657921dff11c407f429d8") -- Depot 6 (844190_5124797400938664495.manifest)
setManifestid(844190,"5124797400938664495")
addappid(644561,0,"c84ccd0b119037080e819441a7a0c94fd35354d88e7f116cb9d5d7763f8a1b32") -- Depot 7 (644561_4070001346154308761.manifest)
setManifestid(644561,"4070001346154308761")
addappid(1011890,0,"c61a09a829dcd3c5487dec85272dd7799d117f559760da7f68ecc5904fa5b09c") -- Depot 8 (1011890_4408302898616918848.manifest)
setManifestid(1011890,"4408302898616918848")