-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 659300
-- Name: Super Farming Boy
addappid(659300) -- Super Farming Boy
addappid(659301,0,"ba41258c6cabf5e6f83ddcdb3a46e861d0296a487e2c422bf1f3925a200e9895") -- Depot 1 (659301_4503573511283696772.manifest)
setManifestid(659301,"4503573511283696772")