-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 665300
-- Name: Stream Avatars
addappid(665300) -- Stream Avatars
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 1 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(665301,0,"3dcf4555a8f4a9b92f642d2de7e8b125fd06f8455d560852c4bedf7a808dc8c8") -- Depot 2 (665301_7977473417291090922.manifest)
setManifestid(665301,"7977473417291090922")