-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 668580
-- Name: Atomic Heart
addappid(668580) -- Atomic Heart
addappid(668581,0,"b331448756a6614f7b9b52f56b71e329928370afb8034b8474e264ace0048928") -- Depot 1 (668581_1673467964514218551.manifest)
setManifestid(668581,"1673467964514218551")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")