-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 678950
-- Name: DRAGON BALL FighterZ
addappid(678950) -- DRAGON BALL FighterZ
addappid(228986,0,"51dd3611d28621644730736f3bb1fd6b960053a45cd79123f2b9a80c9181dad5") -- Depot 1 (228986_8782296191957114623.manifest)
setManifestid(228986,"8782296191957114623")
addappid(678951,0,"cd01842cde6ddf8bae5ce50cdaa221bf46f81a94091514fad68425f49bbb028d") -- Depot 2 (678951_8079912243422982324.manifest)
setManifestid(678951,"8079912243422982324")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")