-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 686060
-- Name: Mewgenics
addappid(686060, 1, "47a5496d8d545c7aaa2a190f2d3d1b55ec5686b8a83b5ae643415dd58bdd151b") -- Mewgenics
-- MAIN APP DEPOTS
addappid(686061, 1, "632bb9334c4d72a84090a9998ec0bf0c8eac465df723928f022b40b6ff04119a") -- Depot 686061
setManifestid(686061, "1658271609472887639", 4914428011)