-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 752590
-- Name: A Plague Tale: Innocence
addappid(752590) -- A Plague Tale: Innocence
-- MAIN APP DEPOTS
addappid(752591, 1, "31c0eb1a38b3926e0e589c25300225886ac653a8415d3612864cd26664681460") -- A Plague Tale: Innocence Content
setManifestid(752591, "476939438164423828", 44611560254)
-- SHARED DEPOTS (from other apps)
addappid(228987, 1, "cf0622b6dec67606fdc42e7afa5ede78cb33e38dfab82670c5ec7e1404e4984e") -- VC 2017 Redist (Shared from App 228980)
setManifestid(228987, "4302102680580581867", 29664201)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(967380) -- A Plague Tale Innocence - Coats of Arms DLC