-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 767320
-- Name: Granblue Fantasy
addappid(767320) -- Granblue Fantasy
-- MAIN APP DEPOTS
addappid(767321, 1, "a59b2e271b7dccebb86cf97a8be93f199add7213306a933dd8bc4baf2fcd4550") -- Depot 767321
setManifestid(767321, "1135010537738626834", 392550492)