-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 774171
-- Name: Muse Dash
addappid(774171) -- Muse Dash
addappid(1055810,0,"ecf8e8de3bbebc8dc0a0f6aecb1c46d919f2172bb7e3611cd56ba636d523d880") -- Depot 1 (1055810_3071104558056225302.manifest)
setManifestid(1055810,"3071104558056225302")
addappid(774172,0,"c4fdeb37adb91f019b5f8f1378c0a63c3a3b90ffec89c7e0394b32a28206d2ec") -- Depot 2 (774172_883518171169029182.manifest)
setManifestid(774172,"883518171169029182")
addappid(774173,0,"e3c55a2a1de897657fb5347590d09a3c41d944a2b041848d5cdacb44afed102f") -- Depot 3 (774173_2007789377902191925.manifest)
setManifestid(774173,"2007789377902191925")