-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 794600
-- Name: LET IT DIE
addappid(794600) -- LET IT DIE
addappid(794601,0,"202385b8bc3029959378251990b973817a80888b1d4792b65f34476813fecd2c") -- Depot 1 (794601_894304746660392729.manifest)
setManifestid(794601,"894304746660392729")
addappid(228984,0,"df7df98d3134f5e0009d5ebcaaf3bbb91ea2f7cbad81a37a9d16bc1835f57068") -- Depot 2 (228984_2547553897526095397.manifest)
setManifestid(228984,"2547553897526095397")
addappid(228983,0,"77c8e812cd79e67e2d376721253ebb07e06b3646f05671c6c9517b27be14734b") -- Depot 3 (228983_8124929965194586177.manifest)
setManifestid(228983,"8124929965194586177")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 4 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")