-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 825630
-- Name: STEINS;GATE 0
addappid(825630) -- STEINS;GATE 0
addappid(825633,0,"6e52df2d665a0a86727a0ac82152d4d3a29fb09e9d1331bd644fc1d7b6bfeb62") -- Depot 1 (825633_989290602639422364.manifest)
setManifestid(825633,"989290602639422364")
addappid(825634,0,"6a322f897cfdd28ab04750b2547f554513251aa769ff828723c40e8907a241aa") -- Depot 2 (825634_934975517331353754.manifest)
setManifestid(825634,"934975517331353754")
addappid(825635,0,"efcbbd8adef0b300f121cb3e2dc2981b0384bbb5108525c6e66a7e3b4126290c") -- Depot 3 (825635_9197845446988398808.manifest)
setManifestid(825635,"9197845446988398808")
addappid(825632,0,"57b3859a5400960dfd2f28cde339bc763997eb76e5020644ec5760d0e836bca3") -- Depot 4 (825632_29171768538633351.manifest)
setManifestid(825632,"29171768538633351")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 5 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(825631,0,"7272d6df7ae168e82d805f977c206d71014577137fdbee034e37d72263bf7356") -- Depot 6 (825631_6416888918427989549.manifest)
setManifestid(825631,"6416888918427989549")