-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 860510
-- Name: Little Nightmares II
addappid(860510) -- Little Nightmares II
addappid(1413420,0,"8c10dd752f9e566421902b5f300bfc5098b40beaf62ba20c7ab8d223c1423dbf") -- Depot 1 (1413420_2584754337176686908.manifest)
setManifestid(1413420,"2584754337176686908")
addappid(229005,0,"aa18a527cdc103aeb3d12caafd6f581689a14467aa55658ba583a9af6e90313a") -- Depot 2 (229005_7992454656023763365.manifest)
setManifestid(229005,"7992454656023763365")
addappid(860511,0,"b4785c13c7b51e8a08e3f16332ef4839c28d6e7544230b06535bd5ee180cbfea") -- Depot 3 (860511_1340413818607528556.manifest)
setManifestid(860511,"1340413818607528556")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 4 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 5 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(1282531,0,"1bf86c1151867753629f54ffb559c02482ff71f34f59476a0a058093e0635ddd") -- Depot 6 (1282531_4972151890057558212.manifest)
setManifestid(1282531,"4972151890057558212")