-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 892970
-- Name: Valheim
addappid(892970) -- Valheim
addappid(892973,0,"6c4d88d54997dcc4234f7ed792e946c0386a6c9a4f242a2bc8c89b49d50f3975") -- Depot 1 (892973_4739876371804987354.manifest)
setManifestid(892973,"4739876371804987354")
addappid(892972,0,"10d286383a9248b6de0c8a160231b4d6332bce1da1fce424d4156329dda3ecf6") -- Depot 2 (892972_6211762228196561354.manifest)
setManifestid(892972,"6211762228196561354")
addappid(892971,0,"fb041c748eb3303b0bb18fbad3b813d19052060d14953e0d7d735943075833fd") -- Depot 3 (892971_1204638473923936036.manifest)
setManifestid(892971,"1204638473923936036")