-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 952060
-- Name: Resident Evil 3
addappid(952060) -- Resident Evil 3
addappid(952063,0,"e5e87afc561b9663966c6f3fb6a9de1dac7466dfb32db183fbcfbeb5f011257b") -- Depot 1 (952063_7504296696893507629.manifest)
setManifestid(952063,"7504296696893507629")
addappid(952062,0,"fdfbc9447d8302b8a7b325ec2bccaa81e77cef9d8289ead20348a702cce53e40") -- Depot 2 (952062_8863028453226553691.manifest)
setManifestid(952062,"8863028453226553691")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 3 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 4 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(952064,0,"438a8c22458963cec5059bec6e195c24b9988cf2c2d2a33298db12146597812c") -- Depot 5 (952064_4916965303803227400.manifest)
setManifestid(952064,"4916965303803227400")