-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 958260
-- Name: Unknown Game
addappid(958260) -- Unknown Game
addappid(958261,0,"47a7073965d982c132fbec7844f17a3acf0ec4133cd86f8f39ab239ae4942718") -- Depot 1 (958261_4601851988060457602.manifest)
setManifestid(958261,"4601851988060457602")
addappid(228987,0,"cf0622b6dec67606fdc42e7afa5ede78cb33e38dfab82670c5ec7e1404e4984e") -- Depot 2 (228987_4302102680580581867.manifest)
setManifestid(228987,"4302102680580581867")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")