-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 962130
-- Name: Grounded
addappid(962130) -- Grounded
addappid(2161395,0,"ed265f9dff9638276834957bc3aed74a221b084e7673afc8f03a3c419166c9c9") -- Depot 1 (2161395_8535256987980260995.manifest)
setManifestid(2161395,"8535256987980260995")
addappid(228984,0,"df7df98d3134f5e0009d5ebcaaf3bbb91ea2f7cbad81a37a9d16bc1835f57068") -- Depot 2 (228984_2547553897526095397.manifest)
setManifestid(228984,"2547553897526095397")
addappid(962131,0,"809ed5f98fa8a3d2c3636c33504157cf05fc683e1810d35e554d7976573a4424") -- Depot 3 (962131_1768200224774657340.manifest)
setManifestid(962131,"1768200224774657340")
addappid(228983,0,"77c8e812cd79e67e2d376721253ebb07e06b3646f05671c6c9517b27be14734b") -- Depot 4 (228983_8124929965194586177.manifest)
setManifestid(228983,"8124929965194586177")
addappid(962134,0,"d8b1b4a7d68cf73a4aade13a9d230c6f1b7b397273cfad6b1a5713c631170002") -- Depot 5 (962134_5364155453177518539.manifest)
setManifestid(962134,"5364155453177518539")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 6 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 7 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(2161391,0,"adb76f3ad9c7f4c95c59498f667d65b7bfad81c41b694adfdbfd22652067dc0d") -- Depot 8 (2161391_2624411356095240629.manifest)
setManifestid(2161391,"2624411356095240629")