-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 962130
-- Name: Grounded
addappid(962130) -- Grounded
addappid(962131,0,"809ed5f98fa8a3d2c3636c33504157cf05fc683e1810d35e554d7976573a4424") -- Depot 1 (962131_6864063491286066765.manifest)
setManifestid(962131,"6864063491286066765")
addappid(962134,0,"d8b1b4a7d68cf73a4aade13a9d230c6f1b7b397273cfad6b1a5713c631170002") -- Depot 2 (962134_5364155453177518539.manifest)
setManifestid(962134,"5364155453177518539")