-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 990380
-- Name: METAL EDEN
addappid(990380) -- METAL EDEN
addappid(990381,0,"8609143fc4bd7b68bc154ba5e0ca2a7f6a148b3ff593cbaf70b9938821696267") -- Depot 1 (990381_9156672187503150458.manifest)
setManifestid(990381,"9156672187503150458")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")