-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 993090
-- Name: Lossless Scaling
addappid(993090) -- Lossless Scaling
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_550968249685141759.manifest)
setManifestid(228989,"550968249685141759")
addappid(229007,0,"eba9fa9ff4f811929c119074450f49f739113bcae9317ded9bea262aa21ec58d") -- Depot 2 (229007_4477590687906973371.manifest)
setManifestid(229007,"4477590687906973371")
addappid(993091,0,"3a02317ffe8c475c236c603a9fcd31c7cd8e4a109240f4c3d9fa28081bdc02bd") -- Depot 3 (993091_2222626553372093171.manifest)
setManifestid(993091,"2222626553372093171")