-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 993340
-- Name: Virtual Surfing
addappid(993340) -- Virtual Surfing
addappid(228987,0,"cf0622b6dec67606fdc42e7afa5ede78cb33e38dfab82670c5ec7e1404e4984e") -- Depot 1 (228987_4302102680580581867.manifest)
setManifestid(228987,"4302102680580581867")
addappid(993342,0,"9d034170c4ccedfddfcf2c6fc82163e22b4a2ac12bee78f70f30175d6eb00445") -- Depot 2 (993342_7598843477682368789.manifest)
setManifestid(993342,"7598843477682368789")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")